unpackaged/main/default/objects/ServiceResource/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>This is the Franchisee&#39;s Account Number</description>
    <inlineHelpText>This is the Franchisee&#39;s Account Number</inlineHelpText>
    <label>Bank Account Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>This is the Company Name of the Engineer. Required for Crystal Tax.</description>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Company_Registered_Number__c.field-meta.xml
<CustomField>
    <fullName>Company_Registered_Number__c</fullName>
    <label>Company Registered Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>Resource birth date</description>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Date_of_VAT_Registration__c.field-meta.xml
<CustomField>
    <fullName>Date_of_VAT_Registration__c</fullName>
    <description>Date the VAT registration took place</description>
    <label>Date of VAT Registration</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Resource Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Employee_No__c.field-meta.xml
<CustomField>
    <fullName>Employee_No__c</fullName>
    <description>Employee Number used for pay purposes</description>
    <label>Employee No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>The main role the resource takes</description>
    <label>Engineer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <description>Resource Mobile No</description>
    <label>Mobile No</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Payment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Payment_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Resource Phone No</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Residential_City__c.field-meta.xml
<CustomField>
    <fullName>Residential_City__c</fullName>
    <description>Residential City of the resource</description>
    <label>Residential City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Residential_Country__c.field-meta.xml
<CustomField>
    <fullName>Residential_Country__c</fullName>
    <description>Residential Country of the resource</description>
    <label>Residential Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Residential_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Residential_PostalCode__c</fullName>
    <description>Residential Postal Code of the resource</description>
    <label>Residential PostalCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Residential_State__c.field-meta.xml
<CustomField>
    <fullName>Residential_State__c</fullName>
    <description>Residential State of the resource</description>
    <label>Residential State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Residential_Street__c.field-meta.xml
<CustomField>
    <fullName>Residential_Street__c</fullName>
    <description>Residential Street of the resource</description>
    <label>Residential Street</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Service_Resource_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource_User_Id__c</fullName>
    <label>Service Resource User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Engineer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service_Resource</fullName>
        <label>Service Resource</label>
    </customValue>
    <customValue>
        <fullName>Franchisee</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
        <isActive>false</isActive>
        <label>Engineer</label>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
        <isActive>false</isActive>
        <label>Manager</label>
    </customValue>
    <customValue>
        <fullName>Estimator</fullName>
        <isActive>false</isActive>
        <label>Estimator</label>
    </customValue>
    <description>The main role the resource takes</description>
    <masterLabel>Engineer Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ParentDetailsCmpController.cls
public without sharing  class ParentDetailsCmpController {
    @AuraEnabled
    public static wrapAccount getAccount(){
        wrapAccount wrap = new wrapAccount();
        wrap.hasRecord = false;
        Id usrid = UserInfo.getUserId();
        System.debug('@@@@@@@@ acc usrid'+usrid);
        List<ServiceResource> acc =[SELECT id,Name,Company_Name__c,Company_Registered_Number__c,Date_of_Birth__c,Bank_Account_Number__c,
                                    Date_of_VAT_Registration__c,Email__c,Employee_No__c,Engineer_Role__c,
                                    Mobile_No__c,Payment_Provider__c,Phone__c,Residential_Street__c,
                                    Residential_City__c,Residential_State__c,Residential_Country__c,Residential_PostalCode__c,
                                    Service_Resource_User_Id__c
                                                from ServiceResource 
                            where RelatedRecordId	=: usrid];
        System.debug('@@@@@@@@ acc'+acc);
        if(!acc.isEmpty()){
            wrap.acc = acc[0];
            wrap.hasRecord = true;
        }
        return wrap;
    }
    public class wrapAccount {
        @AuraEnabled
        public ServiceResource acc {get; set;}
        @AuraEnabled
        public Boolean hasRecord {get; set;}
        
        public wrapAccount( ) {
            acc = null;
            hasRecord = false;
        }
    }
}