unpackaged/main/default/objects/ServiceResource/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>The main role the resource takes</description>
    <label>Engineer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Estimate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Limit__c</fullName>
    <description>Created in relation to Monday task &#39;Conditions to bypass ONSA App - to send to office - for validtion prior to sending&#39;.</description>
    <label>Estimate Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Resource first name</description>
    <label>FirstName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Resource last name</description>
    <label>LastName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Qualifying_WTs_Count__c.field-meta.xml
<CustomField>
    <fullName>Qualifying_WTs_Count__c</fullName>
    <label>Qualifying WTs Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Rate_of_Pay_Tier__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay_Tier__c</fullName>
    <description>Rate at which the Engineer receives Pay</description>
    <inlineHelpText>Rate at which the Engineer receives Pay</inlineHelpText>
    <label>Rate of Pay Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Tier_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkType/fields/Qualified_Inactive_Resource_Count__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Inactive_Resource_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qualified Inactive Resource Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/WorkType/fields/Qualified_Resource_Count__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Resource_Count__c</fullName>
    <label>Qualified Resource Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Engineer_Tier_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 4</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 6</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 8</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 10</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1</fullName>
        <isActive>false</isActive>
        <label>Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Tier 3</fullName>
        <isActive>false</isActive>
        <label>Tier 3</label>
    </customValue>
    <masterLabel>Engineer Tier Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Engineer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service_Resource</fullName>
        <label>Service Resource</label>
    </customValue>
    <customValue>
        <fullName>Franchisee</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
        <isActive>false</isActive>
        <label>Engineer</label>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
        <isActive>false</isActive>
        <label>Manager</label>
    </customValue>
    <customValue>
        <fullName>Estimator</fullName>
        <isActive>false</isActive>
        <label>Estimator</label>
    </customValue>
    <description>The main role the resource takes</description>
    <masterLabel>Engineer Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Phase_2_SR_activation_change_triggerTest.cls
@isTest
public class Phase_2_SR_activation_change_triggerTest {
   static testmethod void  triggerTest(){
                    
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];        
        User u1 = new User(Alias = 'stand1', Email='standarduser1@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='wt_list_test_1@testorg.com');
        insert u1;
        
        ServiceResource sr1 = new ServiceResource();

        sr1.RelatedRecordId = u1.Id;
        sr1.Name = 'test 01res';
        sr1.FirstName__c = 'test';
        sr1.LastName__c = '01res';
        sr1.IsActive = True;
        sr1.ResourceType = 'T';
        sr1.Engineer_Role__c = 'Service_Resource';
        sr1.Rate_of_Pay_Tier__c = 'Tier 2';
        sr1.Estimate_Limit__c = 1000;
        
        insert sr1;
          
        
        
        WorkType wt = new WorkType();
        wt.DurationType = 'Hours';
        wt.EstimatedDuration = 2;
        wt.Name = 'tmp';
        wt.Qualified_Resource_Count__c = 0;
        wt.Qualified_Inactive_Resource_Count__c = 0;
        insert wt;
        
        List<Skill> skills = [SELECT id FROM Skill LIMIT 2 ];
        
        SkillRequirement sreq = new SkillRequirement();
        sreq.RelatedRecordId = wt.id;
        sreq.SkillId = skills[0].id;
        insert sreq;
        
        
        ServiceResourceSkill srskill1 = new ServiceResourceSkill();
        srskill1.ServiceResourceId = sr1.id;
        srskill1.SkillId = skills[0].id;
        srskill1.EffectiveStartDate = DateTime.newInstance(1997, 1, 31, 7, 8, 16);
         
        Test.startTest();
        decimal actual, expected;

        
        insert srskill1;
        actual = [SELECT id, Qualifying_WTs_Count__c FROM ServiceResource WHERE Name='test 01res' LIMIT 1 ].Qualifying_WTs_Count__c;
        System.assertEquals(1, actual);
        ServiceResourceSkill srskill2 = new ServiceResourceSkill();
        srskill2.ServiceResourceId = sr1.id;
        srskill2.SkillId = skills[1].id;
        srskill2.EffectiveStartDate = DateTime.newInstance(1997, 1, 31, 7, 8, 16);
        insert srskill2;
        

        sr1.IsActive = FALSE;
        update sr1;
        actual = [SELECT id, Qualified_Resource_Count__c FROM WorkType WHERE Name = 'tmp' LIMIT 1 ].Qualified_Resource_Count__c;
        System.assertEquals(0, actual);
            
            
        sr1.IsActive = TRUE;
        update sr1;
        actual = [SELECT id, Qualified_Resource_Count__c FROM WorkType WHERE Name = 'tmp' LIMIT 1 ].Qualified_Resource_Count__c;
        System.assertEquals(1, actual);
        
        SkillRequirement sreq2 = new SkillRequirement();
        sreq2.RelatedRecordId = wt.id;
        sreq2.SkillId = skills[0].id;
      //  insert sreq2;
         



        
        Test.stopTest();
    }
}