unpackaged/main/default/objects/ServiceResource/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Resource first name</description>
    <label>FirstName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/Survey_Form__c.object-meta.xml
<CustomObject>
    <description>A Custom Object created for Engineer Satisfaction level monitoring. The data comes from a modal pop-up on Engineer Community Portal once a month for every Active SR with &quot;Engineer Partner Community&quot; profile (excludes new Starters, up to 30 days). &quot;Satisfied&quot; = 100 points, &quot;Neutral&quot; = 50 points and &quot;Dissatisfied&quot; = 0 points.</description>
    <label>Survey Form</label>
    <nameField>
        <displayFormat>SUFM-{0000}</displayFormat>
        <label>Survey Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Survey_Form__c/fields/Access_to_Records_Community_Portal__c.field-meta.xml
<CustomField>
    <fullName>Access_to_Records_Community_Portal__c</fullName>
    <label>Access to Records/Community Portal</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Crystal_Tax_Umbrella_Company__c.field-meta.xml
<CustomField>
    <fullName>Crystal_Tax_Umbrella_Company__c</fullName>
    <label>Crystal Tax/Umbrella Company</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Ease_of_Field_Service_App__c.field-meta.xml
<CustomField>
    <fullName>Ease_of_Field_Service_App__c</fullName>
    <label>Ease of Field Service App</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Office_Admin_Support__c.field-meta.xml
<CustomField>
    <fullName>Office_Admin_Support__c</fullName>
    <label>Office/Admin Support</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Overall_Earnings__c.field-meta.xml
<CustomField>
    <fullName>Overall_Earnings__c</fullName>
    <label>Overall Earnings</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Plant_Hire__c.field-meta.xml
<CustomField>
    <fullName>Plant_Hire__c</fullName>
    <label>Plant Hire</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Quality_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Quality_of_Leads__c</fullName>
    <label>Quality of Leads</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Quantity_Volume_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Volume_of_Leads__c</fullName>
    <label>Quantity/Volume of Leads</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Rates_of_Pay__c.field-meta.xml
<CustomField>
    <fullName>Rates_of_Pay__c</fullName>
    <label>Rates of Pay</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Survey Forms</relationshipLabel>
    <relationshipName>Survey_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Shift_Patterns__c.field-meta.xml
<CustomField>
    <fullName>Shift_Patterns__c</fullName>
    <label>Shift Patterns</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Technical_Manager_Support__c.field-meta.xml
<CustomField>
    <fullName>Technical_Manager_Support__c</fullName>
    <label>Technical Manager Support</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Travel_Time_Distance__c.field-meta.xml
<CustomField>
    <fullName>Travel_Time_Distance__c</fullName>
    <label>Travel Time/Distance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Uniform__c.field-meta.xml
<CustomField>
    <fullName>Uniform__c</fullName>
    <label>Uniform</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Work_Life_Balance__c.field-meta.xml
<CustomField>
    <fullName>Work_Life_Balance__c</fullName>
    <label>Work/Life Balance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Working_for_Aspect__c.field-meta.xml
<CustomField>
    <fullName>Working_for_Aspect__c</fullName>
    <label>Working for Aspect</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>VEH-{0000}</displayFormat>
        <label>VEH</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/PORTAL_EngineerSurveyController.cls
public with sharing class PORTAL_EngineerSurveyController {

    public static final Integer MONTH_IN_DAYS = 30;

    public static ServiceResource srForCurrentUser {
        get {
            List<ServiceResource> activeServiceResources = new List<ServiceResource>();
            if (srForCurrentUser == null) {
                activeServiceResources = [
                        SELECT Id, FirstName__c, Name, CreatedDate, IsActive
                        FROM ServiceResource
                        WHERE RelatedRecord.Id = :UserInfo.getUserId()
                        AND IsActive = TRUE
                        AND (RelatedRecord.Profile.Name = 'Engineer Partner Community'
                        OR RelatedRecord.Profile.Name = 'System Administrator')
                        LIMIT 1
                ];
            }
            if (!activeServiceResources.isEmpty()) {
                return activeServiceResources[0];
            } else {
                return null;
            }
        }
        set;
    }

    @AuraEnabled
    public static String getServiceResourceFirstName() {
        if (srForCurrentUser != null) {
            if (srForCurrentUser.FirstName__c != null) {
                return srForCurrentUser.FirstName__c;
            } if (srForCurrentUser.Name != null) {
                return srForCurrentUser.Name;
            }
        }
        return 'Guest User';
    }

    @AuraEnabled
    public static Boolean isServiceResourceOlderThan30Days() {
        if (srForCurrentUser != null) {
            Integer daysDif = (Date.valueOf(srForCurrentUser.CreatedDate)).daysBetween(System.today());
            return daysDif > MONTH_IN_DAYS;
        } else {
            return true;
        }
    }

    @AuraEnabled
    public static List<Survey_Form__c> getSurveyRecordFromThisMonth() {
        if (srForCurrentUser != null) {
            return [
                    SELECT Service_Resource__r.Id,
                            Vehicle__c, Uniform__c, Plant_Hire__c, Shift_Patterns__c, Rates_of_Pay__c,
                            Ease_of_Field_Service_App__c, Quality_of_Leads__c, Quantity_Volume_of_Leads__c,
                            Travel_Time_Distance__c, Overall_Earnings__c, Office_Admin_Support__c,
                            Technical_Manager_Support__c, Access_to_Records_Community_Portal__c,
                            Crystal_Tax_Umbrella_Company__c, Work_Life_Balance__c, Working_for_Aspect__c
                    FROM Survey_Form__c
                    WHERE Service_Resource__c = :srForCurrentUser.Id
                    AND CreatedDate = THIS_MONTH
                    ORDER BY CreatedDate DESC
                    LIMIT 1
            ];
        } else {
            return null;
        }
    }

    @AuraEnabled
    public static void insertSurvey(Survey_Form__c surveyRecord) {
        if (srForCurrentUser == null) {
            return;
        }
        if (surveyRecord.Service_Resource__c == null) {
            surveyRecord.Service_Resource__c = srForCurrentUser.Id;
        }
        SurveyWoSharingHelper surveyHelper = new SurveyWoSharingHelper();
        surveyHelper.insertNewSurvey(surveyRecord);
    }

    public without sharing class SurveyWoSharingHelper {
        public void insertNewSurvey(Survey_Form__c surveyRecord) {
            insert surveyRecord;
        }
    }
}