unpackaged/main/default/objects/ResourceAbsence/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not yet Approved</fullName>
                <default>true</default>
                <label>Not yet Approved</label>
            </value>
            <value>
                <fullName>Leave Approved</fullName>
                <isActive>false</isActive>
                <label>Leave Approved</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
                <isActive>false</isActive>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <isActive>false</isActive>
                <label>Waiting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Resource Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>The main role the resource takes</description>
    <label>Engineer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Estimate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Limit__c</fullName>
    <description>Created in relation to Monday task &#39;Conditions to bypass ONSA App - to send to office - for validtion prior to sending&#39;.</description>
    <label>Estimate Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Rate_of_Pay_Tier__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay_Tier__c</fullName>
    <description>Rate at which the Engineer receives Pay</description>
    <inlineHelpText>Rate at which the Engineer receives Pay</inlineHelpText>
    <label>Rate of Pay Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Tier_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Engineer_Tier_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 4</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 6</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 8</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 10</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1</fullName>
        <isActive>false</isActive>
        <label>Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Tier 3</fullName>
        <isActive>false</isActive>
        <label>Tier 3</label>
    </customValue>
    <masterLabel>Engineer Tier Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Engineer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service_Resource</fullName>
        <label>Service Resource</label>
    </customValue>
    <customValue>
        <fullName>Franchisee</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
        <isActive>false</isActive>
        <label>Engineer</label>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
        <isActive>false</isActive>
        <label>Manager</label>
    </customValue>
    <customValue>
        <fullName>Estimator</fullName>
        <isActive>false</isActive>
        <label>Estimator</label>
    </customValue>
    <description>The main role the resource takes</description>
    <masterLabel>Engineer Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CalenderClassTest.cls
@isTest
public class CalenderClassTest {
    static testMethod void calendarMethod(){
        
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduse21344555r@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standfefdsfdarduser@testorg.com');
        insert u;
        System.runAs(u){
            String RecordTypeIdContact = Schema.SObjectType.ResourceAbsence.getRecordTypeInfosByName().get('Non Availability').getRecordTypeId();
            ServiceResource SR = new ServiceResource();
            SR.Email__c = ' Test@gmail.com';
            SR.Engineer_Role__c ='Service_Resource';
            SR.ResourceType = 'T';
            SR.Rate_of_Pay_Tier__c = 'Tier 2';
            SR.RelatedRecordId =u.id;
            SR.Estimate_Limit__c =100;
            SR.Name ='Test';
            insert SR;
            SR.IsActive = true;
            Update SR;
            OperatingHours oh = new OperatingHours();
            oh.Name = 'Day';
            insert oh;
            
            OperatingHours oh1 = new OperatingHours();
            oh1.Name = 'Aspect Operating Hours (24/7/365)';
            insert oh1;
            
            ResourceAbsence ra = new ResourceAbsence();
            ra.Type ='Meeting';
           
            ra.Start = SYstem.today();
            ra.End = System.today()+1;
            ra.ResourceId =SR.id;
            ra.Status__c ='Approved';
            insert ra;
            
             ResourceAbsence ra1 = new ResourceAbsence();
            ra1.Type ='Meeting';
           
            ra1.Start = SYstem.today();
            ra1.End = System.today()+1;
            ra1.ResourceId =SR.id;
            ra1.Status__c ='Not yet Approved';
            insert ra1;
            
            
             ResourceAbsence ra2 = new ResourceAbsence();
            ra2.Type ='Meeting';
           
            ra2.Start = SYstem.today();
            ra2.End = System.today()+4;
            ra2.ResourceId =SR.id;
            ra2.Status__c ='Rejected';
            insert ra2;
            
            ServiceTerritory objST = new ServiceTerritory();
            objST.Name = 'Test Territory';
            objST.OperatingHoursId = oh1.Id;
            objST.IsActive = TRUE;
            insert objST;
            
            
            ServiceTerritoryMember objSTM = new ServiceTerritoryMember();
            objSTM.TerritoryType = 'P';
            objSTM.ServiceTerritoryId = objST.Id;
            objSTM.ServiceResourceId = SR.Id;
            objSTM.EffectiveStartDate = Date.today().addDays(10);
            objSTM.EffectiveEndDate = Date.today().addDays(12);
         objSTM.OperatingHoursId = oh1.id;
            insert objSTM;
            
            Shift sh = new Shift();
            sh.Status ='Tentative';
            sh.EndTime = System.today()+7;
            sh.StartTime = System.today();
            sh.TimeSlotType ='Normal';
            sh.ServiceResourceId = SR.id;
            insert sh;
            
            test.StartTest();
            List<String> s =  CalenderClass.getPickListValuesIntoList();
            String s1 =   CalenderClass.getServiceResourceId();
            String s3 = CalenderClass.createPermissionorabsence(System.today(),System.today()+1,SR.id,RecordTypeIdContact,'','','','');
            String s4 = CalenderClass.createPermissionorabsence(System.today(),System.today()+1,SR.id,RecordTypeIdContact,'Absence','','','');
            String s5 = CalenderClass.createPermissionorabsence(System.today(),System.today()+1,SR.id,RecordTypeIdContact,'Permission','','','');
            String s6 = CalenderClass.getrecordTYpe();
            Map<Date,String> s7=  CalenderClass.getWeeksDay(System.today(),System.today()+7);
            list<CalenderClass.wrapTimeSlot> s8= CalenderClass.getAllEvents();
              List<OperatingHours> sq1 =CalenderClass.getAllOperationHour();
          Datetime dq1=  CalenderClass.getdateMinus(System.today());
            test.stopTest();
        }
    }
    
}