unpackaged/main/default/objects/ResourceAbsence/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not yet Approved</fullName>
                <default>true</default>
                <label>Not yet Approved</label>
            </value>
            <value>
                <fullName>Leave Approved</fullName>
                <isActive>false</isActive>
                <label>Leave Approved</label>
            </value>
            <value>
                <fullName>Submitted for Approval</fullName>
                <isActive>false</isActive>
                <label>Submitted for Approval</label>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <isActive>false</isActive>
                <label>Waiting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ResourceAbsenceTriggerHandler.cls
public class ResourceAbsenceTriggerHandler {
    public static void beforeInsert(List<ResourceAbsence > resc){
        for(ResourceAbsence res :resc){
            if( res.FSL__Approved__c ==true ){
                res.Status__c= 'Approved';
            }
        }
    }
    public static void beforeupdate(List<ResourceAbsence > resc,Map<id,ResourceAbsence>mapold){
        for(ResourceAbsence res :resc){
            if(res.FSL__Approved__c != mapold.get(res.id).FSL__Approved__c && res.FSL__Approved__c==true  )
            {
                res.Status__c= 'Approved';
            }else  if(res.FSL__Approved__c != mapold.get(res.id).FSL__Approved__c && res.FSL__Approved__c==false  )
            {
                res.Status__c= 'Not yet Approved';
            }
        }
        
    }
    
}