unpackaged/main/default/objects/Account/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Site related to the Contact</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Costs_and_Charges__c/Costs_and_Charges__c.object-meta.xml
<CustomObject>
    <label>Costs and Charges</label>
    <nameField>
        <displayFormat>CandC-{000000}</displayFormat>
        <label>Costs and Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Costs_and_Charges__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Costs and Charges</relationshipLabel>
    <relationshipName>Costs_and_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Allocated_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Allocated Engineer</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>This will be from the Assigned Resources</description>
    <label>Engineer Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Resource Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>The main role the resource takes</description>
    <label>Engineer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Estimate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Limit__c</fullName>
    <description>Created in relation to Monday task &#39;Conditions to bypass ONSA App - to send to office - for validtion prior to sending&#39;.</description>
    <label>Estimate Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Rate_of_Pay_Tier__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay_Tier__c</fullName>
    <description>Rate at which the Engineer receives Pay</description>
    <inlineHelpText>Rate at which the Engineer receives Pay</inlineHelpText>
    <label>Rate of Pay Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Tier_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site__c/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <description>Information to access the site</description>
    <label>Access Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email to contact the related Site</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Primary_Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Site_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Primary contact at this Site</inlineHelpText>
    <label>Primary Site Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Primary_Sites_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_Country__c.field-meta.xml
<CustomField>
    <fullName>Site_Country__c</fullName>
    <defaultValue>&#39;United Kingdom&#39;</defaultValue>
    <description>Site country</description>
    <label>Site Country</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Site_PostalCode__c</fullName>
    <description>Site postal address</description>
    <label>Site PostalCode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_Street__c.field-meta.xml
<CustomField>
    <fullName>Site_Street__c</fullName>
    <description>Site street address</description>
    <label>Site Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Costs_and_Charges__c.field-meta.xml
<CustomField>
    <fullName>Costs_and_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Costs and Charges</label>
    <referenceTo>Costs_and_Charges__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Appointment_Status__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Status__c</fullName>
    <description>For Engineer to see on their mobile in FSL</description>
    <inlineHelpText>Status of the Service Appointment with additional statuses for On site conversions/Estimates accepted/declined</inlineHelpText>
    <label>Service Appointment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>On site</fullName>
            </value>
            <value>
                <fullName>Visit Complete</fullName>
            </value>
            <value>
                <fullName>Job Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated only through the flow</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Reactive.recordType-meta.xml
<RecordType>
    <fullName>Reactive</fullName>
    <active>true</active>
    <label>Reactive</label>
</RecordType>

unpackaged/main/default/objects/WorkType/recordTypes/Reactive.recordType-meta.xml
<RecordType>
    <fullName>Reactive</fullName>
    <active>true</active>
    <label>Reactive</label>
</RecordType>

unpackaged/main/default/globalValueSets/Engineer_Tier_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 4</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 6</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 8</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 10</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1</fullName>
        <isActive>false</isActive>
        <label>Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Tier 3</fullName>
        <isActive>false</isActive>
        <label>Tier 3</label>
    </customValue>
    <masterLabel>Engineer Tier Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Engineer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service_Resource</fullName>
        <label>Service Resource</label>
    </customValue>
    <customValue>
        <fullName>Franchisee</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
        <isActive>false</isActive>
        <label>Engineer</label>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
        <isActive>false</isActive>
        <label>Manager</label>
    </customValue>
    <customValue>
        <fullName>Estimator</fullName>
        <isActive>false</isActive>
        <label>Estimator</label>
    </customValue>
    <description>The main role the resource takes</description>
    <masterLabel>Engineer Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/FileUploadControllerTest.cls
@isTest
public class FileUploadControllerTest {
static testMethod void calendarMethod(){
        
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduse21344555r@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standfefdsfdarduser@testorg.com');
        insert u;
        System.runAs(u){
            Account acc = new Account();
            acc.name =' test';
            acc.BillingStreet = 'First street'; 
            insert acc;
            
            Contact con = new Contact();
            con.LastName = 'John';
            insert con;
            
            String RecordTypeIdContact = Schema.SObjectType.ResourceAbsence.getRecordTypeInfosByName().get('Non Availability').getRecordTypeId();
            ServiceResource SR = new ServiceResource();
            SR.Email__c = ' Test@gmail.com';
            SR.Estimate_Limit__c =100; 
            SR.Engineer_Role__c ='Service_Resource';
            SR.ResourceType = 'T';
            SR.Rate_of_Pay_Tier__c = 'Tier 2';
            SR.RelatedRecordId =u.id;
            
            SR.Name ='Test';
            insert SR;
            
            Site__c site = new Site__c();
            site.Account__c  = acc.id;
            site.Name = 'test';
            site.Site_Street__c ='Test';
            site.Site_PostalCode__c ='12345';
            Site.Site_Country__c ='Uk'; 
             site.Primary_Site_Contact__c =con.id;
            insert site; 
            
            Job__c job = new Job__c();
            Job.Account__c = acc.id;
            Job.Site__c =site.id;
            insert Job;
            
            Costs_and_Charges__c costs = new Costs_and_Charges__c();
            costs.Job__c = job.id;
            insert costs;
            
            //String RecordTypeIdWorkType = Schema.SObjectType.WorkType.getRecordTypeInfosByName().get('Reactive').getRecordTypeId();
            WorkType WT = new WorkType();
            WT.Name = 'Test';
            WT.EstimatedDuration = 2;
            insert WT;
            
            
            
            String RecordTypeIdWorkOrder = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Reactive').getRecordTypeId();
            WorkOrder WO = new WorkOrder();
            WO.Subject = 'Testing';
            WO.Status = 'Pending';
            WO.AccountId = acc.id;
            WO.Costs_and_Charges__c = costs.id;
            WO.Job__c = job.id;
            WO.WorkTypeId = WT.id;
            WO.Priority = 'Low';
            WO.Service_Appointment_Status__c = 'Dispatched';
            WO.ContactId = con.id;
            WO.Service_Resource__c = SR.id;
            WO.Duration = 2.00;
            WO.Description = 'Test'; 
            WO.Access_Details__c = 'code 1245';
            WO.Requested_Date__c = System.today();
            WO.RecordTypeId =RecordTypeIdWorkOrder;
            insert WO;
            
            ServiceAppointment SA = new ServiceAppointment();
            SA.Status	 ='Visit Complete';
            SA.ParentRecordId = WO.id;
            SA.SchedStartTime = System.today();
            SA.SchedEndTime = System.today()+1;
            SA.Allocated_Engineer__c =SR.id;
            insert SA;
            Test.startTest();
            String s = FileUploadController.saveFile(null,'Test','fsdsgfdgdfbgfngfn','','',SA.id);
            Test.stopTest();
        }
}
}