unpackaged/main/default/objects/Account/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pending_Referrer__c.field-meta.xml
<CustomField>
    <fullName>Pending_Referrer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Referrer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>On Stop</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <isActive>false</isActive>
        <label>On Hold</label>
    </customValue>
    <customValue>
        <fullName>See Credit Control</fullName>
        <isActive>false</isActive>
        <label>See Credit Control</label>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
        <isActive>false</isActive>
        <label>Close</label>
    </customValue>
    <description>Status of the Account</description>
    <masterLabel>Account Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/BuyapowaGetURLsBatch_Test.cls
/*
* Class  : BuyapowaGetURLsBatch_Test
* Use    : This test class is written to get test coverage of BuyapowaGetURLsBatch class.
* Auther : Bharat Vyas, 21/7/2022
*/
@isTest
public class BuyapowaGetURLsBatch_Test {
    
    static testMethod void testMethodForGetURLs() 
    {
        List<Account> lstAccount= new List<Account>();
        
        Account acc = new Account(
            Name = 'Account Test1',
            Email__c = 'test_here1@gmail.com',
            Pending_Referrer__c = true,
            Account_Type__c = 'Cash',
            Account_Status__c = 'Open',
            BillingStreet = '8 Allington way',
            BillingCity = 'Swanley',
            BillingCountry = 'United Kingdom',
            BillingPostalCode = 'BR8 8FG',
            Access_Details__c = '2333'
        );
        lstAccount.add(acc);
        acc = new Account(
            Name = 'Account Test2',
            Email__c = 'test_here2@gmail.com',
            Pending_Referrer__c = false,
            Account_Type__c = 'Cash',
            Account_Status__c = 'Open',
            BillingStreet = '8 Allington way',
            BillingCity = 'Swanley',
            BillingCountry = 'United Kingdom',
            BillingPostalCode = 'BR8 8FG',
            Access_Details__c = '2333'
        );
        lstAccount.add(acc);
        
        insert lstAccount;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseForBuyapowaGetURLsBatch());
        String CRON_EXP = '0 15 * * * ? 2022';
        String jobId = System.schedule('buyapowaGetURLsBatch', CRON_EXP, new BuyapowaGetURLsBatch());
        Test.stopTest();
    }
}