unpackaged/main/default/objects/Account/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Community.recordType-meta.xml
<RecordType>
    <fullName>Community</fullName>
    <active>false</active>
    <businessProcess>Default Support Process</businessProcess>
    <description>This is a record type for community users</description>
    <label>Community</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Complaint.recordType-meta.xml
<RecordType>
    <fullName>Complaint</fullName>
    <active>false</active>
    <businessProcess>Default Support Process</businessProcess>
    <label>Complaint</label>
</RecordType>

unpackaged/main/default/objects/ServiceAppointment/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Allocated_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Allocated Engineer</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>This will be from the Assigned Resources</description>
    <label>Engineer Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Resource Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>The main role the resource takes</description>
    <label>Engineer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Rate_of_Pay_Tier__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay_Tier__c</fullName>
    <description>Rate at which the Engineer receives Pay</description>
    <inlineHelpText>Rate at which the Engineer receives Pay</inlineHelpText>
    <label>Rate of Pay Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Tier_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Appointment_Status__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Status__c</fullName>
    <description>For Engineer to see on their mobile in FSL</description>
    <inlineHelpText>Status of the Service Appointment with additional statuses for On site conversions/Estimates accepted/declined</inlineHelpText>
    <label>Service Appointment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>On site</fullName>
            </value>
            <value>
                <fullName>Visit Complete</fullName>
            </value>
            <value>
                <fullName>Job Closure</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Reactive.recordType-meta.xml
<RecordType>
    <fullName>Reactive</fullName>
    <active>true</active>
    <label>Reactive</label>
</RecordType>

unpackaged/main/default/globalValueSets/Engineer_Tier_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 4</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 6</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 8</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 10</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1</fullName>
        <isActive>false</isActive>
        <label>Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Tier 3</fullName>
        <isActive>false</isActive>
        <label>Tier 3</label>
    </customValue>
    <masterLabel>Engineer Tier Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Engineer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service_Resource</fullName>
        <label>Service Resource</label>
    </customValue>
    <customValue>
        <fullName>Franchisee</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
        <isActive>false</isActive>
        <label>Engineer</label>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
        <isActive>false</isActive>
        <label>Manager</label>
    </customValue>
    <customValue>
        <fullName>Estimator</fullName>
        <isActive>false</isActive>
        <label>Estimator</label>
    </customValue>
    <description>The main role the resource takes</description>
    <masterLabel>Engineer Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CaseListControllerTest.cls
@isTest
public class CaseListControllerTest {
    static testMethod void CaseListMethod() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduse21344555r@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standfefdsfdarduser@testorg.com');
        insert u;
        System.runAs(u) {
            
            Account acc = new Account();
            acc.name =' test';
            acc.BillingStreet = 'First street'; 
            insert acc;
            
            Contact con = new Contact();
            con.LastName = 'One';
            insert con;
            
            String RecordTypeIdContact = Schema.SObjectType.ResourceAbsence.getRecordTypeInfosByName().get('Non Availability').getRecordTypeId();
            ServiceResource SR = new ServiceResource();
            SR.Email__c = ' Test@gmail.com';
            SR.Engineer_Role__c ='Service_Resource';
            SR.ResourceType = 'T';
            SR.Rate_of_Pay_Tier__c = 'Tier 2';
            SR.RelatedRecordId =u.id;
            SR.Name ='Test';
            insert SR;
            
            String RecordTypeIdWorkOrder = Schema.SObjectType.WorkOrder.getRecordTypeInfosByName().get('Reactive').getRecordTypeId();
            WorkOrder WO = new WorkOrder();
            WO.Subject = 'Testing';
            WO.Status = 'Pending';
            WO.AccountId = acc.id;
            WO.Priority = 'Low';
            WO.Service_Appointment_Status__c = 'Dispatched';
            WO.ContactId = con.id;
            WO.Service_Resource__c = SR.id;
            WO.Duration = 2.00;
            WO.Description = 'Test'; 
            WO.Access_Details__c = 'code 1245';
            WO.RecordTypeId =RecordTypeIdWorkOrder;
            insert WO;
            
            ServiceAppointment SA = new ServiceAppointment();
            SA.Status	 ='Visit Complete';
            SA.ParentRecordId = WO.id;
            SA.SchedStartTime = System.today();
            SA.SchedEndTime = System.today()+1;
            SA.Allocated_Engineer__c =SR.id;
            insert SA;
            
            Case cs = new Case();
            cs.Status = 'Complaint';
            cs.Description = 'anything';
            cs.ContactId = con.Id;
            cs.Origin = 'Community';
            insert cs;
            cs.Status = 'Closed';
            update cs;
            
            Case cs1 = new case();
            cs1.Priority = 'Low';
            cs1.Status = 'Review';
            cs1.Subject = 'Anything';
            cs1.Description = 'Nothing';
            cs1.ParentId = cs.Id;
            cs1.SuppliedEmail = u.Email;
            cs1.Service_Appointment__c = SA.Id;
            cs1.Origin = 'Office';
            insert cs1;
            
            test.StartTest();
            List<CaseListController.CaseWrapper> s = CaseListController.getCaseList('All',cs.Id);
             List<CaseListController.CaseWrapper> s12 = CaseListController.getCaseList('Service Appointment',cs.Id);
             List<CaseListController.CaseWrapper> s13 = CaseListController.getCaseList('requisition',cs.Id);
             List<CaseListController.CaseWrapper> s14 = CaseListController.getCaseList('deduc',cs.Id);
            List<CaseListController.CaseWrapper> s1 = CaseListController.getCaseListbyfilter('Community');
            List<caseComment> s2 = CaseListController.getCaseCommnets(cs.Id);
            List<String> s3 = CaseListController.getCaselistvalues();
            String s4 = CaseListController.getCaseListtoClose(cs.Id);
            Boolean s5 = CaseListController.getStatusValue(cs.ID);
            CaseListController.CasecommentWrapper s6 = CaseListController.createCaseComment(cs.Id, '');
            List<CaseComment> s7 = CaseListController.getCasecommes(new List<CaseComment>{  
            });
            
            test.StopTest();
        }
    }
}