unpackaged/main/default/objects/Account/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Invoicing_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email_Address__c</fullName>
    <description>Purpose is to send bulk invoices to a Customer. If this field is populated then the system should send the email to the email address on the field else it should use the Customer&#39;s email address</description>
    <label>Invoicing Email Address</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/Customer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Invoices</relationshipLabel>
    <relationshipName>Customer_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Cash, Credit or Key Account</description>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <inlineHelpText>Cash, Credit or Key Account</inlineHelpText>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Charge_Net__c.field-meta.xml
<CustomField>
    <fullName>Charge_Net__c</fullName>
    <formula>Charge_Rollup_Net__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Charge Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>This will show the Date the invoice was raised</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Sum_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>Sum_of_Payments__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Populated via a Flow due to lack of Master-Detail relationship between Customer Inv and Payment (managed package)</description>
    <inlineHelpText>Sum of the Payments for a Customer Invoice</inlineHelpText>
    <label>Sum of Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/recordTypes/Deposit.recordType-meta.xml
<RecordType>
    <fullName>Deposit</fullName>
    <active>true</active>
    <label>Deposit</label>
</RecordType>

unpackaged/main/default/objects/Customer_Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

unpackaged/main/default/objects/Customer_Invoice_Line_Item__c/Customer_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice Line Item</label>
    <nameField>
        <displayFormat>CILI-{000000}</displayFormat>
        <label>Customer Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice_Line_Item__c/fields/Charge_Net__c.field-meta.xml
<CustomField>
    <fullName>Charge_Net__c</fullName>
    <label>Charge Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice_Line_Item__c/fields/Customer_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Customer_Invoice__c</fullName>
    <label>Customer Invoice</label>
    <referenceTo>Customer_Invoice__c</referenceTo>
    <relationshipLabel>Customer Invoice Line Items</relationshipLabel>
    <relationshipName>Customer_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice_Line_Item__c/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <label>VAT Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>17.5</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/VAT_Rate__c/VAT_Rate__c.object-meta.xml
<CustomObject>
    <description>Stores the vat codes and rates to be used in the system</description>
    <label>VAT Rate</label>
    <nameField>
        <label>VAT Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VAT Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/VAT_Rate__c/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <description>Vat Rate Applicable e.g 2 for 20% and Z for 0%</description>
    <label>VAT Rate</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>On Stop</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <isActive>false</isActive>
        <label>On Hold</label>
    </customValue>
    <customValue>
        <fullName>See Credit Control</fullName>
        <isActive>false</isActive>
        <label>See Credit Control</label>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
        <isActive>false</isActive>
        <label>Close</label>
    </customValue>
    <description>Status of the Account</description>
    <masterLabel>Account Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountStatementControllerTest.cls
@istest
public class AccountStatementControllerTest {

    static testmethod void wt_resource_list_test(){
        
        
        Account acc = new Account(
                Name = 'Invoice Test',
                First_Name__c = 'Invoice',
                Last_Name__c = 'Test',
                Email__c = 'dasfrog.web@gmail.com',
                Invoicing_Email_Address__c = 'dasfrog.web@gmail.com',
                Account_Type__c = 'Cash',
                Account_Status__c = 'Open',
                BillingStreet = '8 Allington way',
                BillingCity = 'Swanley',
                BillingCountry = 'United Kingdom',
                BillingPostalCode = 'BR8 8FG',
                Access_Details__c = '2333'
            );
            insert acc;
        
        Customer_Invoice__c inv =   new Customer_Invoice__c(
            Account__c = acc.id,
            Date__c = DATE.today()-31,
            Sum_of_Payments__c = 0,
            RecordTypeID = Schema.SObjectType.Customer_Invoice__c.getRecordTypeInfosByName().get('Deposit').getRecordTypeId()
        );
        insert inv;
    	insert new Customer_Invoice_Line_Item__c(
            Customer_Invoice__c = inv.id,
            Charge_Net__c = 100,
            VAT_Rate__c = '20'
        );
   
             Customer_Invoice__c inv2 =   new Customer_Invoice__c(
            Account__c = acc.id,
            Date__c = DATE.today()-61,
            Sum_of_Payments__c = 0,
            RecordTypeID = Schema.SObjectType.Customer_Invoice__c.getRecordTypeInfosByName().get('Deposit').getRecordTypeId()
        );
        insert inv2;
    	insert new Customer_Invoice_Line_Item__c(
            Customer_Invoice__c = inv2.id,
            Charge_Net__c = 100,
            VAT_Rate__c = '20'
        );
                Customer_Invoice__c inv3 =   new Customer_Invoice__c(
            Account__c = acc.id,
            Date__c = DATE.today()-91,
            Sum_of_Payments__c = 0,
            RecordTypeID = Schema.SObjectType.Customer_Invoice__c.getRecordTypeInfosByName().get('Deposit').getRecordTypeId()
        );
        insert inv3;
    	insert new Customer_Invoice_Line_Item__c(
            Customer_Invoice__c = inv3.id,
            Charge_Net__c = 100,
            VAT_Rate__c = '20'
        );
                Customer_Invoice__c inv4 =   new Customer_Invoice__c(
            Account__c = acc.id,
            Date__c = DATE.today()-121,
            Sum_of_Payments__c = 0,
            RecordTypeID = Schema.SObjectType.Customer_Invoice__c.getRecordTypeInfosByName().get('Deposit').getRecordTypeId()
        );
        insert inv4;
    	insert new Customer_Invoice_Line_Item__c(
            Customer_Invoice__c = inv4.id,
            Charge_Net__c = 100,
            VAT_Rate__c = '20'
        );
        
        
        ///////////////////////////////////
        Test.startTest();
        
        //ApexPages.StandardController sc = new ApexPages.StandardController(acc);
  		//myControllerExtension testAccPlan = new myControllerExtension(sc);

  		PageReference pageRef = Page.Account_Statement_Page; // Add your VF page Name here
  		pageRef.getParameters().put('id', String.valueOf(acc.Id));
        
        
        Test.setCurrentPage(pageRef);
        AccountStatementController wt_controller = new AccountStatementController();
  
        Test.stopTest();
        
    }
    
}