unpackaged/main/default/objects/Account/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Invoicing_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email_Address__c</fullName>
    <description>Purpose is to send bulk invoices to a Customer. If this field is populated then the system should send the email to the email address on the field else it should use the Customer&#39;s email address</description>
    <label>Invoicing Email Address</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Site related to the Contact</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Costs_and_Charges__c/Costs_and_Charges__c.object-meta.xml
<CustomObject>
    <label>Costs and Charges</label>
    <nameField>
        <displayFormat>CandC-{000000}</displayFormat>
        <label>Costs and Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Costs_and_Charges__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The Status of the Costs and Charges record</description>
    <inlineHelpText>The Status of the Costs and Charges record</inlineHelpText>
    <label>C&amp;C Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info Incomplete</fullName>
                <default>true</default>
                <label>Info Incomplete</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Info Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/Engineer_Pay_Requisition__c.object-meta.xml
<CustomObject>
    <label>Engineer Pay Requisition</label>
    <nameField>
        <displayFormat>EPR-{000000}</displayFormat>
        <label>Engineer Pay Requisition  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineer Pay Requisitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(Job__r.Account__r.Account_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Rate_of_Pay_Tier__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay_Tier__c</fullName>
    <formula>Text(Service_Resource__r.Rate_of_Pay_Tier__c)</formula>
    <inlineHelpText>This field reflects current tier of pay value of the Engineer</inlineHelpText>
    <label>Current Rate of Pay Tier</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Is the Account: Cash, Credit or Key Account?</description>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <inlineHelpText>Is the Account: Cash, Credit or Key Account?</inlineHelpText>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>For Client Approval</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved by Client</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Resource Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>The main role the resource takes</description>
    <label>Engineer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Estimate_Limit__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Limit__c</fullName>
    <description>Created in relation to Monday task &#39;Conditions to bypass ONSA App - to send to office - for validtion prior to sending&#39;.</description>
    <label>Estimate Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Resource first name</description>
    <label>FirstName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Resource last name</description>
    <label>LastName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Rate_of_Pay_Tier__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay_Tier__c</fullName>
    <description>Rate at which the Engineer receives Pay</description>
    <inlineHelpText>Rate at which the Engineer receives Pay</inlineHelpText>
    <label>Rate of Pay Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Tier_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site__c/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <description>Information to access the site</description>
    <label>Access Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email to contact the related Site</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Primary_Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Site_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Primary contact at this Site</inlineHelpText>
    <label>Primary Site Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Primary_Sites_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_City__c.field-meta.xml
<CustomField>
    <fullName>Site_City__c</fullName>
    <description>Site city address</description>
    <label>Site City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Site_PostalCode__c</fullName>
    <description>Site postal address</description>
    <label>Site PostalCode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_Street__c.field-meta.xml
<CustomField>
    <fullName>Site_Street__c</fullName>
    <description>Site street address</description>
    <label>Site Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status form Account object</description>
    <formula>TEXT( Account.Account_Status__c )</formula>
    <inlineHelpText>Account Status</inlineHelpText>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TRIM(TEXT(Account.Account_Type__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated only through the flow</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>On Stop</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <isActive>false</isActive>
        <label>On Hold</label>
    </customValue>
    <customValue>
        <fullName>See Credit Control</fullName>
        <isActive>false</isActive>
        <label>See Credit Control</label>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
        <isActive>false</isActive>
        <label>Close</label>
    </customValue>
    <description>Status of the Account</description>
    <masterLabel>Account Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Engineer_Tier_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 4</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 6</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 8</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 10</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1</fullName>
        <isActive>false</isActive>
        <label>Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Tier 3</fullName>
        <isActive>false</isActive>
        <label>Tier 3</label>
    </customValue>
    <masterLabel>Engineer Tier Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Engineer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service_Resource</fullName>
        <label>Service Resource</label>
    </customValue>
    <customValue>
        <fullName>Franchisee</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
        <isActive>false</isActive>
        <label>Engineer</label>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
        <isActive>false</isActive>
        <label>Manager</label>
    </customValue>
    <customValue>
        <fullName>Estimator</fullName>
        <isActive>false</isActive>
        <label>Estimator</label>
    </customValue>
    <description>The main role the resource takes</description>
    <masterLabel>Engineer Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/epr_create_edit_delete_controller_test.cls
@isTest
public class epr_create_edit_delete_controller_test {
    
    static testmethod void erp_test(){
        

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];        
        User u1 = new User(Alias = 'stand1', Email='standarduser1@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='wt_list_test_1@testorg.com');
        insert u1;
        
        ServiceResource sr1 = new ServiceResource();

        sr1.RelatedRecordId = u1.Id;
        sr1.Name = 'test 01res';
        sr1.FirstName__c = 'test';
        sr1.LastName__c = '01res';
        sr1.IsActive = True;
        sr1.ResourceType = 'T';
        sr1.Engineer_Role__c = 'Service_Resource';
        sr1.Rate_of_Pay_Tier__c = 'Tier 2';
        sr1.Estimate_Limit__c = 1000;
        
        insert sr1;
        
                
        Account acc = new Account();
        acc.Name = 'Invoice Test';
        acc.First_Name__c = 'Invoice';
        acc.Last_Name__c = 'Test';
        acc.Email__c = 'dasfrog.web@gmail.com';
        acc.Invoicing_Email_Address__c = 'dasfrog.web@gmail.com';
        acc.Account_Type__c = 'Cash';
        acc.Account_Status__c = 'Open';
        acc.BillingStreet = '8 Allington way';
        acc.BillingCity = 'Swanley';
        acc.BillingCountry = 'United Kingdom';
        acc.BillingPostalCode = 'BR8 8FG';
        acc.Access_Details__c = '2333';
        insert acc;
        
        Contact con = new Contact();
        con.AccountId = acc.Id;
        con.FirstName = acc.First_Name__c;
        con.LastName = acc.Last_Name__c;
        con.Email = acc.Email__c;
        insert con;
        
        Site__c site = new Site__c();
        site.Name = acc.Name +'-'+ acc.BillingStreet+'-'+ acc.BillingPostalCode;
        site.Site_Street__c = acc.BillingStreet;
        site.Access_Details__c = acc.Access_Details__c;
        site.Site_PostalCode__c = acc.BillingPostalCode;
        site.Site_City__c = acc.BillingCity;
        site.Account__c = acc.Id;
        site.Primary_Site_Contact__c = con.id;
        insert site;

        
        WorkType wt = new WorkType();
        wt.DurationType = 'Hours';
        wt.EstimatedDuration = 2;
        wt.Name = 'tmp';
        insert wt;
        
        Job__c job = new Job__c();
        job.Account__c = acc.id;
        job.Job_Type__c = wt.id;
        Job.Site__c = site.id;
        insert job;
        
       	Costs_and_Charges__c cct = new Costs_and_Charges__c();
        cct.Job__c = job.Id;
        cct.Record_Type__c = 'F';
        cct.Hourly_Charge_R1__c = 80;//onb.Hourly_rate__c
        cct.Hourly_Charge_R2__c = 80;//onb.Hourly_rate__c
        cct.Hourly_Charge_R3__c = 80;//onb.Hourly_rate__c
        cct.Chargeable_Duration_R1__c = 1;
        cct.Chargeable_Duration_R2__c = 1;
        cct.Chargeable_Duration_R3__c = 1;
        cct.Call_Out_Fee__c = 0;
        cct.Charge_List_Price_Services__c = 1000;
        cct.Rate_of_Pay__c = 99;
        cct.Discount_Manual_Percentage__c = 0;
        insert cct;
        
        cct.Discount_Manual_Percentage__c = 5;
        update cct;
        
        
        WorkOrder wo = new WorkOrder();
        wo.Job__c = job.Id;
        wo.WorkTypeId = wt.Id;//Id input from the form submitted online
        wo.Description = 'Blah blah';
        wo.ContactId = con.Id;
        wo.AccountId = acc.Id;
        wo.Site__c = site.Id;
        wo.Duration = wt.EstimatedDuration;
        wo.country = 'United Kingdom';
        wo.Scope_of_Works_Amended_by_Operative__c = 'test';
        wo.Arrival_Window_Start_Date_Time__c = system.now();
        wo.Arrival_Window_End_Date_Time__c = system.now();
        wo.Costs_and_Charges__c = cct.id;
        insert wo;
        
        Engineer_Pay_Requisition__c epr = new Engineer_Pay_Requisition__c();
        epr.Service_Resource__c = sr1.id;
        epr.Job__c = job.id;
        epr.Work_Order__c = wo.id;
        epr.Chargeable_Units_R1__c = 1;
        epr.Rate_of_Charge_R1__c = 100;
        epr.Pay_Materials__c = 0;
        epr.Pay_Fixed_Price__c = 50;
        epr.Status__c = 'New';
        insert epr;
        
        epr.Pay_Materials__c = 10;
        update epr;
        
        delete epr;
    }

}