unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <label>Commercial</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Site related to the Contact</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>Purchase Order for Material and Sub Contractor.</description>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Purchase_Order_Line_Item__c/Purchase_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Purchase Order Line Item</description>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>POLI-{000000}</displayFormat>
        <label>Purchase Order Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Purchase_Order_Line_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <description>This is the Main Purchase Order that each Line Item relates to</description>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Line Items</relationshipLabel>
    <relationshipName>Purchase_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Region_Area__c/Region_Area__c.object-meta.xml
<CustomObject>
    <description>This will show all of the Areas within regions that Aspect operates within. Whenever a new expansion happens, A region record is created or data loaded, a new region public group is created and the Sharing settings based on Region Areas are updated.</description>
    <label>Region Area</label>
    <nameField>
        <label>Region Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Region Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Region_Area__c/fields/Region_Area_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Area_Code__c</fullName>
    <label>Region Area Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email to contact the related Site</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Primary_Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Site_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Primary contact at this Site</inlineHelpText>
    <label>Primary Site Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Primary_Sites_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Region_Area__c.field-meta.xml
<CustomField>
    <fullName>Region_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Will be used to Lookup up the region code from the site postcode</description>
    <label>Region Area</label>
    <referenceTo>Region_Area__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Region_Area_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Area_Code__c</fullName>
    <formula>Region_Area__r.Region_Area_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region Area Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Site_PostalCode__c</fullName>
    <description>Site postal address</description>
    <label>Site PostalCode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/SiteGeo_Latitude__c.field-meta.xml
<CustomField>
    <fullName>SiteGeo_Latitude__c</fullName>
    <description>This field stores the latitude of the address from FLS Visitour</description>
    <label>SiteGeo Latitude</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/SiteGeo_Longitude__c.field-meta.xml
<CustomField>
    <fullName>SiteGeo_Longitude__c</fullName>
    <description>This field stores the longitude of the Address from FLS Visitour</description>
    <label>SiteGeo Longitude</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Site__c/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <label>Commercial</label>
</RecordType>

unpackaged/main/default/objects/Supplier_Invoice__c/Supplier_Invoice__c.object-meta.xml
<CustomObject>
    <description>Supplier Invoice</description>
    <label>Supplier Invoice</label>
    <nameField>
        <displayFormat>SI-{000000}</displayFormat>
        <label>Salesforce Internal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(Purchase_Order__r.Supplier_Account__r.Account_Type__c)</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Supplier Invoices</relationshipLabel>
    <relationshipName>Supplier_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WorkOrder/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status form Account object</description>
    <formula>TEXT( Account.Account_Status__c )</formula>
    <inlineHelpText>Account Status</inlineHelpText>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TRIM(TEXT(Account.Account_Type__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Region_Area_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Area_Code__c</fullName>
    <description>This shows which Region Area that the Work Order belongs to</description>
    <formula>Site__r.Region_Area_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region Area Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated only through the flow</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <description>Deletion Candidate</description>
    <label>Time (delete)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1AM</fullName>
            </value>
            <value>
                <fullName>2AM</fullName>
            </value>
            <value>
                <fullName>3AM</fullName>
            </value>
            <value>
                <fullName>4AM</fullName>
            </value>
            <value>
                <fullName>5AM</fullName>
            </value>
            <value>
                <fullName>6AM</fullName>
            </value>
            <value>
                <fullName>7AM</fullName>
            </value>
            <value>
                <fullName>8AM</fullName>
            </value>
            <value>
                <fullName>9AM</fullName>
            </value>
            <value>
                <fullName>10AM</fullName>
            </value>
            <value>
                <fullName>11AM</fullName>
            </value>
            <value>
                <fullName>12PM</fullName>
            </value>
            <value>
                <fullName>1PM</fullName>
            </value>
            <value>
                <fullName>2PM</fullName>
            </value>
            <value>
                <fullName>3PM</fullName>
            </value>
            <value>
                <fullName>4PM</fullName>
            </value>
            <value>
                <fullName>5PM</fullName>
            </value>
            <value>
                <fullName>6PM</fullName>
            </value>
            <value>
                <fullName>7PM</fullName>
            </value>
            <value>
                <fullName>8PM</fullName>
            </value>
            <value>
                <fullName>9PM</fullName>
            </value>
            <value>
                <fullName>10PM</fullName>
            </value>
            <value>
                <fullName>11PM</fullName>
            </value>
            <value>
                <fullName>12AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <description>Trade for the Work Type - added this for the H&amp;S Flow + thought it better to use a formula than look it up each time.</description>
    <formula>TEXT( WorkType.Trade__c )</formula>
    <inlineHelpText>Trade for the Work Type</inlineHelpText>
    <label>Trade</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Reactive.recordType-meta.xml
<RecordType>
    <fullName>Reactive</fullName>
    <active>true</active>
    <label>Reactive</label>
</RecordType>

unpackaged/main/default/objects/WorkType/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trade</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkType/recordTypes/Reactive.recordType-meta.xml
<RecordType>
    <fullName>Reactive</fullName>
    <active>true</active>
    <label>Reactive</label>
</RecordType>

unpackaged/main/default/globalValueSets/Account_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>On Stop</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <isActive>false</isActive>
        <label>On Hold</label>
    </customValue>
    <customValue>
        <fullName>See Credit Control</fullName>
        <isActive>false</isActive>
        <label>See Credit Control</label>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
        <isActive>false</isActive>
        <label>Close</label>
    </customValue>
    <description>Status of the Account</description>
    <masterLabel>Account Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Trade.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Access</fullName>
    </customValue>
    <customValue>
        <fullName>Air Con, Ventilation &amp; Refrigeration</fullName>
    </customValue>
    <customValue>
        <fullName>Brickwork &amp; Paving</fullName>
    </customValue>
    <customValue>
        <fullName>Carpentry</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Decorating</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Soil Water)</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Tanker)</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Wastewater)</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Fencing</fullName>
    </customValue>
    <customValue>
        <fullName>Flooring</fullName>
    </customValue>
    <customValue>
        <fullName>Gardening</fullName>
    </customValue>
    <customValue>
        <fullName>Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>Handyman</fullName>
    </customValue>
    <customValue>
        <fullName>Heating &amp; Hot Water (Commercial)</fullName>
    </customValue>
    <customValue>
        <fullName>Heating &amp; Hot Water (Domestic)</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Central Heating</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Drainage</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Plumbing</fullName>
    </customValue>
    <customValue>
        <fullName>Locksmithing</fullName>
    </customValue>
    <customValue>
        <fullName>OSA</fullName>
    </customValue>
    <customValue>
        <fullName>Partition Walls &amp; Ceilings</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Control</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Proofing</fullName>
    </customValue>
    <customValue>
        <fullName>Plastering</fullName>
    </customValue>
    <customValue>
        <fullName>Plumbing &amp; Cold Water</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management Decoration</fullName>
    </customValue>
    <description>This holds all of the types of trade in the company</description>
    <masterLabel>Trade</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/PurchaseOrderLineItemDeleteTest.cls
@isTest
private class PurchaseOrderLineItemDeleteTest {
    
    @isTest
    private static void PurchaseOrderLineItemDeleteTest() {
        Account acc = new Account (
            Name = 'TestAccountWorkOrder '+String.valueOf(Math.round((Math.random() * (900000) + 100000))),
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Commercial').getRecordTypeId(),
            Account_Type__c = 'Cash',
            Account_Status__c = 'Open',
            Email__c = 'testAccountEmailWork@email.test',
            BillingPostalCode = 'NW1 3HG',
            BillingStreet = '4 Triton Square',
            BillingCity = 'London',
            BillingCountry = 'United Kingdom',
            Last_Name__c = 'Last Name'
    );
    insert acc;
    Region_Area__c regionArea = new Region_Area__c (
        Region_Area_Code__c = 'aa2a'
    );
    insert regionArea;
    
    Contact primContact = new Contact(
    LastName='LastName',
        Account  = acc
        );
    insert primContact;
    /*[Select Id
                           From Contact
                           Where AccountId = :acc.Id];
    //record type should be created by builder process alread*/
    Site__c site = new Site__c (
        Site_PostalCode__c = 'aa2a 2aa',//a-zA-Z]{2}\\d[a-zA-Z]\\s\\d[a-zA-Z]{2}"),
        Region_Area__c = regionArea.Id,
        RecordTypeId = Schema.SObjectType.Site__c.getRecordTypeInfosByDeveloperName().get('Commercial').getRecordTypeId(),
        Account__c = acc.Id,
        SiteGeo_Longitude__c = 1212335,
        SiteGeo_Latitude__c = 5675346,
        Primary_Site_Contact__c = primContact.id
    );
    insert site;/*
    Site__c site = [Select Id
                    From Site__c
                    Where Account__c = :acc.Id];*/
    String wt_trade = (WorkType.Trade__c.getDescribe().getPicklistValues())[0].getLabel();

                    
    WorkType workType = new WorkType (
        Trade__c = wt_trade,
        Name = 'tmp',
        DurationType = 'Hours',
        EstimatedDuration = 2.00
    );
    insert workType;
    
    
        WorkOrder wo = new WorkOrder (
            AccountId = acc.Id,
//                Client_Status__c = 'New',
            Status = 'New',
            RecordTypeId = OnlineBookingProcessHelper.getRecordTypeIdbyName('WorkOrder','Reactive'),
            //Contact_Email__c = 'testAccountEmailWork@email.test',
            Site__c = site.Id,
            Time__c = '8AM',
            WorkTypeId = workType.Id
        );
        insert wo;
        Purchase_Order__c po = new Purchase_Order__c(
            Work_Order__c = wo.id
            //Supplier_Invoice__c = inv.id
        );
        insert po;
        Purchase_Order_Line_Item__c li = new Purchase_Order_Line_Item__c(
            Purchase_Order__c = po.id
        );
        insert li;
        Test.startTest();
        delete li;
        Test.stopTest();        
    }
}