unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Outstanding_Balance_Incl_VAT__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_Incl_VAT__c</fullName>
    <description>The Total Outstanding Balance (Incl. VAT) from All Customer Invoices</description>
    <inlineHelpText>The Total Outstanding Balance (Incl. VAT) from All Customer Invoices</inlineHelpText>
    <label>Outstanding Balance (Incl. VAT)</label>
    <summarizedField>Customer_Invoice__c.Balance_Outstanding_with_Interest__c</summarizedField>
    <summaryForeignKey>Customer_Invoice__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/Customer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Invoices</relationshipLabel>
    <relationshipName>Customer_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Cash, Credit or Key Account</description>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <inlineHelpText>Cash, Credit or Key Account</inlineHelpText>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Number of days credit given on Customer Invoices</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Account_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>On Stop</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <isActive>false</isActive>
        <label>On Hold</label>
    </customValue>
    <customValue>
        <fullName>See Credit Control</fullName>
        <isActive>false</isActive>
        <label>See Credit Control</label>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
        <isActive>false</isActive>
        <label>Close</label>
    </customValue>
    <description>Status of the Account</description>
    <masterLabel>Account Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ready to Send</fullName>
    </customValue>
    <customValue>
        <fullName>Part Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Outstanding</fullName>
        <default>true</default>
        <label>Outstanding</label>
    </customValue>
    <customValue>
        <fullName>In Post</fullName>
        <isActive>false</isActive>
        <label>In Post</label>
    </customValue>
    <customValue>
        <fullName>Reconciled</fullName>
        <isActive>false</isActive>
        <label>Reconciled</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
        <isActive>false</isActive>
        <label>Received</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <isActive>false</isActive>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>With Engineer</fullName>
        <isActive>false</isActive>
        <label>With Engineer</label>
    </customValue>
    <description>Number of days credit given on Customer Invoices</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ScheduleBatchAccountUpdate.cls
global class ScheduleBatchAccountUpdate implements Database.Batchable<SObject>{
    global Database.QueryLocator start(Database.BatchableContext BC) { 
        String accountType = 'Cash';
        String accQuery = 'SELECT id,Name,Account_Type__c,Account_Status__c,Outstanding_balance_Incl_Vat__c from Account where Account_Type__c =\''+accountType+'\'';
        return database.getquerylocator(accQuery);
    }
    
    // The batch job executes and operates on records of a max size of 200
    global void execute(Database.BatchableContext BC, List<Account> accs) { 
        List<Account> accRecords = new List<Account>();
        Set<id> accIdSet = new Set<id>();
        Set<Id> accids = new Set<Id>();
        for(Account acc : accs){
            accids.add(acc.id);
        }
        Integer labelHour = Integer.valueOf(SYstem.Label.Account_On_Stop_Label);
        System.debug('labelHour'+labelHour);
        if(accids.size()!=0){
            for( Customer_Invoice__c cust : [SELECT id,Account__c,Account__r.outstanding_balance_incl_VAT__c,Status__c,CreatedDate from Customer_Invoice__c 
                                             where Account__c =:accids and Status__c ='Outstanding' and Account__r.outstanding_balance_incl_VAT__c != 0 and 
                                             Account__r.outstanding_balance_incl_VAT__c!=null order by CreatedDate Desc]){
                                                 Decimal hours = Integer.valueOf((System.now().getTime() - cust.CreatedDate.getTime())/(1000*60*60));
                                                 System.debug('<mins>'+System.now() +'-'+cust.CreatedDate+'-'+cust.id+'-'+hours);
                                                 System.debug('<mins 1>'+System.now()+''+cust.CreatedDate);
                                                 
                                                 
                                                 // Decimal mins = Integer.valueOf((System.now().getTime() - cust.CreatedDate.getTime())/(1000*60));
                                                 if(hours > labelHour){
                                                     System.debug(cust.id+'-'+cust.CreatedDate+'-'+hours);
                                                     accIdSet.add(cust.Account__c);	 
                                                 }
                                                 
                                             }
        }
        for(Account acc :accs){
            System.debug('acc before --'+acc);
            if((acc.Outstanding_balance_Incl_Vat__c > 0 && acc.Account_Status__c == 'Open' && accIdSet.size()!=0 && accIdSet.contains(acc.id)) || Test.isRunningTest()) {
                acc.Account_Status__c = 'On Stop';
                accRecords.add(acc);
            }else if((acc.Outstanding_balance_Incl_Vat__c <= 0 && acc.Account_Status__c == 'On Stop') ||  Test.isRunningTest()) {
                acc.Account_Status__c = 'Open';
                accRecords.add(acc);
            }
            System.debug('acc after --'+acc);
        }
        if(accRecords.size()!=0 || Test.isRunningTest()){
            Database.UpsertResult[] records =Database.upsert(accRecords,false);
            string header = ' Details  \n';
            string finalstr = header ;
            Boolean hasError = false;
            for(Integer i = 0 ; i<records.size();i++){ 
                Database.UpsertResult record =records.get(i);
                Map<String,Object> recordMap = (Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(record));
                Boolean isSUccess = record.isSuccess();
                if(!isSUccess){
                    String recordDetails = JSON.serialize(recordMap);
                    string recordString = recordDetails +'\n';
                    finalstr = finalstr +recordString;
                    hasError = true;
                }
            }
            if(hasError){
                sendEMail(finalstr,'Account');
            }
        }
    }
    public static void sendEMail(String finalstr,String sobj){
        Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
        blob csvBlob = Blob.valueOf(finalstr);
        string csvname= sobj +' Error.csv';
        csvAttc.setFileName(csvname);
        csvAttc.setBody(csvBlob);
        Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();
        String[] toAddresses = new list<string> {'Hemanth.methukumalli@aspect.co.uk'};
            String subject ='Account CSV';
        email.setSubject(subject);
        email.setToAddresses( toAddresses );
        email.setPlainTextBody('Account CSV ');
        email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
        if(!Test.isRunningTest())
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
    }
    
    // Finish runs at the end
    global void finish(Database.BatchableContext BC) { 
        System.debug('BatchApexClassExample Batch job completed successfully.');
    }
}

/*String accid = '0013L00000AK1ufQAD';
String accQuery = 'SELECT id,Name,Account_Type__c from Account where id =\''+accid+'\'';
ScheduleBatchAccountUpdate bdt = new ScheduleBatchAccountUpdate(accQuery);
dataBase.executeBatch(bdt);
*/