unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/Engineer_Pay_Requisition__c.object-meta.xml
<CustomObject>
    <label>Engineer Pay Requisition</label>
    <nameField>
        <displayFormat>EPR-{000000}</displayFormat>
        <label>Engineer Pay Requisition  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineer Pay Requisitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(Job__r.Account__r.Account_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Engineer Pay Requisitions</relationshipLabel>
    <relationshipName>Engineer_Pay_Requisitions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Engineer Pay Requisitions</relationshipLabel>
    <relationshipName>Engineer_Pay_Requisitions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Is the Account: Cash, Credit or Key Account?</description>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <inlineHelpText>Is the Account: Cash, Credit or Key Account?</inlineHelpText>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/All_Work_Order_in_Status_of_Complete__c.field-meta.xml
<CustomField>
    <fullName>All_Work_Order_in_Status_of_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Will be ticked when All Work Orders are in a Status of Complete</description>
    <inlineHelpText>Will be ticked when All Work Orders are in a Status of Complete</inlineHelpText>
    <label>All Work Order in Status of Complete</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>For Client Approval</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved by Client</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Temp_Key_Account_Req_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Temp_Key_Account_Req_Tracking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Temporary field created by Matthew Radoja to track jobs which have been processed by the &quot;retrospectively generate EPRs for completed Key account Jobs&quot; process. To be removed once auto process in place.</description>
    <inlineHelpText>Temporary field created by Matthew Radoja to track jobs which have been processed by the &quot;retrospectively generate EPRs for completed Key account Jobs&quot; process. To be removed once auto process in place.</inlineHelpText>
    <label>Temp Key Account Req Tracking</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>Earliest_Work_Order_by_Requested_Date__r.Record_Type_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TRIM(TEXT(Account.Account_Type__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CreateEPRforJob_Batch.cls
global class CreateEPRforJob_Batch implements Database.Batchable<sObject> {
    global static   Set<String> userId  ;
    global static  Set<String> userEmailids;
    global CreateEPRforJob_Batch( ){
        userId =  new Set<String>();
        userEmailids =  new Set<String>();
        
        System.debug('userId'+userId);
        System.debug('userEmailids'+userEmailids);
    }
    global Database.QueryLocator start(Database.BatchableContext BC) { 
        System.debug('userId'+userId);
        System.debug('userEmailids'+userEmailids);
        String query='';
        if(!test.isrunningtest())
            query = System.Label.JobEPRCreationQuery ;  
        else
            query ='SELECT id, CreatedDate, Temp_Key_Account_Req_Tracking__c,Status__c, Type__c, Account__r.Account_Type__c , Name, (SELECT Status FROM Work_Orders__r), (SELECT Name FROM Engineer_Pay_Requisitions__r), All_Work_Order_in_Status_of_Complete__c FROM Job__c';
      //  query = query +  ' LIMIT 1 '; 
        System.debug('query'+query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Job__c> Jobs) {
        GetUserDetailsFromMetadata.wrapUser wrap =  GetUserDetailsFromMetadata.getUserEmailIds();
        userId = wrap.userIds;
        userEmailids= wrap.userEmailIds;
        System.debug('userId'+userId);
        System.debug('userEmailids'+userEmailids);
        List<Job__c> jobRecord = new List<Job__c>();
        string header = 'Job Name with Error Message \n';
        string finalstr = header ;
        Boolean hasError = false;
        for(Job__c job:jobs)
        {
            if(job.Engineer_Pay_Requisitions__r.size()==0 ){
                System.debug('job'+job.id);
                try{
                    job_LabourRequisitionsController.genReqs(job);     
                }
                catch(Exception ex){
                    if(userId.size()!=0)
                        sendCustomNotificationToUser.sendCustomnotification(ex.getMessage(),job.id,userId);
                    if(userEmailids.size()!=0)
                        sendCustomNotificationToUser.sendEMailerrorMessage('EPR Creation Section ',
                                                                           ex.getMessage(),job.id,userEmailids,
                                                                           'EPR');
                }
                
                job.Temp_Key_Account_Req_Tracking__c = TRUE;
                jobRecord.add(job);
                System.debug('success on job '+job.id+' ('+job.name+')');
            }
        }
        
        Set<String> errMessage = new Set<String>();
        if(jobRecord.size()!=0){
            List<Database.upsertResult> jobUpdations = Database.upsert(jobRecord,false);
            for(Integer i=0;i<jobUpdations.size();i++){
                Database.UpsertResult result = jobUpdations.get(i);
                Job__c jobRec = jobRecord.get(i);
                Boolean isSuccess =  result.isSuccess();
                String statusKey = isSuccess ?'success':'failed';
                if(!isSuccess   )
                {
                    string recordString = 'Job Id :' +result.id+'  '+'Error Message :'+result.getErrors().get(0).getMessage()+'\n';
                    finalstr = finalstr +recordString;
                    hasError = true;
                    if(userId.size()!=0   )
                        sendCustomNotificationToUser.sendCustomnotification(recordString,jobRec.id,userId);
                }
            }
        }
        if(hasError && userEmailids.size()!=0 || test.isrunningtest()){
            sendCustomNotificationToUser.sendEMailerrorMessage('JOb Update Temp_Key_Account_Req_Tracking__c Section '
                                                               ,finalstr ,null ,userEmailids, 'Job');
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        updateEprStatusApproved bCon = new updateEprStatusApproved();
        Database.ExecuteBatch(bCon,10);
    }
}