unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>The main role the resource takes</description>
    <label>Engineer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>Resource first name</description>
    <label>FirstName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Resource last name</description>
    <label>LastName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/Survey_Form__c.object-meta.xml
<CustomObject>
    <description>A Custom Object created for Engineer Satisfaction level monitoring. The data comes from a modal pop-up on Engineer Community Portal once a month for every Active SR with &quot;Engineer Partner Community&quot; profile (excludes new Starters, up to 30 days). &quot;Satisfied&quot; = 100 points, &quot;Neutral&quot; = 50 points and &quot;Dissatisfied&quot; = 0 points.</description>
    <label>Survey Form</label>
    <nameField>
        <displayFormat>SUFM-{0000}</displayFormat>
        <label>Survey Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Survey_Form__c/fields/Access_to_Records_Community_Portal__c.field-meta.xml
<CustomField>
    <fullName>Access_to_Records_Community_Portal__c</fullName>
    <label>Access to Records/Community Portal</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Crystal_Tax_Umbrella_Company__c.field-meta.xml
<CustomField>
    <fullName>Crystal_Tax_Umbrella_Company__c</fullName>
    <label>Crystal Tax/Umbrella Company</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Ease_of_Field_Service_App__c.field-meta.xml
<CustomField>
    <fullName>Ease_of_Field_Service_App__c</fullName>
    <label>Ease of Field Service App</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Office_Admin_Support__c.field-meta.xml
<CustomField>
    <fullName>Office_Admin_Support__c</fullName>
    <label>Office/Admin Support</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Overall_Earnings__c.field-meta.xml
<CustomField>
    <fullName>Overall_Earnings__c</fullName>
    <label>Overall Earnings</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Plant_Hire__c.field-meta.xml
<CustomField>
    <fullName>Plant_Hire__c</fullName>
    <label>Plant Hire</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Quality_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Quality_of_Leads__c</fullName>
    <label>Quality of Leads</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Quantity_Volume_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Volume_of_Leads__c</fullName>
    <label>Quantity/Volume of Leads</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Rates_of_Pay__c.field-meta.xml
<CustomField>
    <fullName>Rates_of_Pay__c</fullName>
    <label>Rates of Pay</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Survey Forms</relationshipLabel>
    <relationshipName>Survey_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Shift_Patterns__c.field-meta.xml
<CustomField>
    <fullName>Shift_Patterns__c</fullName>
    <label>Shift Patterns</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Technical_Manager_Support__c.field-meta.xml
<CustomField>
    <fullName>Technical_Manager_Support__c</fullName>
    <label>Technical Manager Support</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Travel_Time_Distance__c.field-meta.xml
<CustomField>
    <fullName>Travel_Time_Distance__c</fullName>
    <label>Travel Time/Distance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Uniform__c.field-meta.xml
<CustomField>
    <fullName>Uniform__c</fullName>
    <label>Uniform</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Work_Life_Balance__c.field-meta.xml
<CustomField>
    <fullName>Work_Life_Balance__c</fullName>
    <label>Work/Life Balance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Survey_Form__c/fields/Working_for_Aspect__c.field-meta.xml
<CustomField>
    <fullName>Working_for_Aspect__c</fullName>
    <label>Working for Aspect</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>VEH-{0000}</displayFormat>
        <label>VEH</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/Account_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>On Stop</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <isActive>false</isActive>
        <label>On Hold</label>
    </customValue>
    <customValue>
        <fullName>See Credit Control</fullName>
        <isActive>false</isActive>
        <label>See Credit Control</label>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
        <isActive>false</isActive>
        <label>Close</label>
    </customValue>
    <description>Status of the Account</description>
    <masterLabel>Account Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Engineer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service_Resource</fullName>
        <label>Service Resource</label>
    </customValue>
    <customValue>
        <fullName>Franchisee</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
        <isActive>false</isActive>
        <label>Engineer</label>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
        <isActive>false</isActive>
        <label>Manager</label>
    </customValue>
    <customValue>
        <fullName>Estimator</fullName>
        <isActive>false</isActive>
        <label>Estimator</label>
    </customValue>
    <description>The main role the resource takes</description>
    <masterLabel>Engineer Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/PORTAL_EngineerSurveyControllerTest.cls
@IsTest
private class PORTAL_EngineerSurveyControllerTest {

    @TestSetup
    private static void setup() {
        UserRole adminRole = [SELECT Id FROM UserRole WHERE Name = 'root'];
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];

        User adminUser = new User(
                Alias = 'admin',
                Email = 'testcommunityadmin@gmail.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'AdminLastName',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_GB',
                ProfileId = adminProfile.Id,
                TimeZoneSidKey = 'Europe/London',
                Username = 'testcommunityadmin@gmail.com',
                UserRoleId = adminRole.Id
        );
        insert adminUser;

        System.runAs(adminUser) {
            Profile communityProfile = [SELECT Id FROM Profile WHERE Name = 'Engineer Partner Community'];

            Account acc = new Account();
            acc.Name = 'TestAccountName';
            acc.Account_Type__c = 'Cash';
            acc.Account_Status__c = 'Open';
            insert acc;

            Contact testContact = new Contact();
            testContact.LastName = 'TestContactLastName';
            testContact.AccountId = acc.Id;
            insert testContact;

            User communityUser = new User(
                    ContactId = testContact.Id,
                    Alias = 'srUser',
                    Email = 'testSRcommunity@gmail.com',
                    EmailEncodingKey = 'UTF-8',
                    FirstName = 'UserFirstName',
                    LastName = 'UserLastName',
                    LanguageLocaleKey = 'en_US',
                    LocaleSidKey = 'en_GB',
                    ProfileId = communityProfile.Id,
                    TimeZoneSidKey = 'Europe/London',
                    Username = 'testcommunitysr@gmail.com',
                    IsActive = true
            );
            insert communityUser;

            ServiceResource serviceResourceForCommunityUser = new ServiceResource(
                    Name = 'SRName',
                    FirstName__c = 'SRFirstName',
                    LastName__c = 'SRLastName',
                    IsActive = true,
                    RelatedRecordId = communityUser.Id,
                    ResourceType = 'T',
                    Engineer_Role__c = 'Service_Resource');
            insert serviceResourceForCommunityUser;
        }
    }

    @IsTest
    static void getServiceResourceWithFirstNameTest() {
        User srUser = [SELECT Id, FirstName, IsActive FROM User WHERE Username = 'testcommunitysr@gmail.com'];

        System.runAs(srUser) {
            Test.startTest();
            System.assertEquals('SRFirstName', PORTAL_EngineerSurveyController.getServiceResourceFirstName());
            Test.stopTest();
        }
    }

    @IsTest
    static void getServiceResourceWithoutFirstNameTest() {
        User srUser = [SELECT Id, FirstName, IsActive FROM User WHERE Username = 'testcommunitysr@gmail.com'];
        ServiceResource sr = [SELECT Id, FirstName__c FROM ServiceResource WHERE Name = 'SRName'];
        sr.FirstName__c = null;
        update sr;

        System.runAs(srUser) {
            Test.startTest();
            System.assertEquals('SRName', PORTAL_EngineerSurveyController.getServiceResourceFirstName());
            Test.stopTest();
        }
    }

    @IsTest
    static void getServiceResourceNameWithoutSRTest() {
        User adminWithoutSR = [SELECT Id, FirstName, Name FROM User WHERE Alias = 'admin'];

        System.runAs(adminWithoutSR) {
            Test.startTest();
            System.assertEquals('Guest User', PORTAL_EngineerSurveyController.getServiceResourceFirstName());
            Test.stopTest();
        }
    }

    @IsTest
    static void isServiceResourceOlderThan30DaysTest() {
        User srUser = [SELECT Id, FirstName, IsActive FROM User WHERE Username = 'testcommunitysr@gmail.com'];

        System.runAs(srUser) {
            Test.startTest();
            System.assertEquals(false, PORTAL_EngineerSurveyController.isServiceResourceOlderThan30Days());
            Test.stopTest();
        }
    }

    @IsTest
    static void getSurveyRecordFromThisMonthTest() {
        User srUser = [SELECT Id, FirstName, IsActive FROM User WHERE Alias = 'srUser'];
        ServiceResource sr = [SELECT Id FROM ServiceResource WHERE RelatedRecordId = :srUser.Id];
        Survey_Form__c newSurveyForm = new Survey_Form__c(
                Service_Resource__c = sr.Id
        );
        insert newSurveyForm;

        System.runAs(srUser) {
            Test.startTest();
            PORTAL_EngineerSurveyController.getSurveyRecordFromThisMonth();
            Test.stopTest();
        }
        List<Survey_Form__c> surveyForm = [SELECT Id FROM Survey_Form__c];
        System.assertEquals(1, surveyForm.size());
    }

    @IsTest
    static void insertSurveyTest() {
        User srUser = [
                SELECT Id,FirstName, IsActive, (SELECT Id FROM ServiceResources)
                FROM User
                WHERE Alias = 'srUser'
        ];

        System.runAs(srUser) {
            Survey_Form__c newSurveyForm = new Survey_Form__c(
                    Service_Resource__c = srUser.ServiceResources[0].Id, Vehicle__c = 50, Uniform__c = 100,
                    Plant_Hire__c = 0, Shift_Patterns__c = 100, Rates_of_Pay__c = 100,
                    Ease_of_Field_Service_App__c = 50, Quality_of_Leads__c = 100, Quantity_Volume_of_Leads__c = 50,
                    Travel_Time_Distance__c = 100, Overall_Earnings__c = 100, Office_Admin_Support__c = 50,
                    Technical_Manager_Support__c = 100, Access_to_Records_Community_Portal__c = 50,
                    Crystal_Tax_Umbrella_Company__c = 50, Work_Life_Balance__c = 100, Working_for_Aspect__c = 100
            );
            Test.startTest();
            PORTAL_EngineerSurveyController.insertSurvey(newSurveyForm);
            Test.stopTest();

            Survey_Form__c updatedSurveyForm = [
                    SELECT Vehicle__c, Uniform__c, Ease_of_Field_Service_App__c,Plant_Hire__c, Shift_Patterns__c,
                            Quantity_Volume_of_Leads__c, Office_Admin_Support__c,Working_for_Aspect__c
                    FROM Survey_Form__c
            ];
            System.assertEquals(50, updatedSurveyForm.Vehicle__c);
            System.assertEquals(100, updatedSurveyForm.Uniform__c);
            System.assertEquals(50, updatedSurveyForm.Ease_of_Field_Service_App__c);
            System.assertEquals(0, updatedSurveyForm.Plant_Hire__c);
            System.assertEquals(100, updatedSurveyForm.Shift_Patterns__c);
            System.assertEquals(50, updatedSurveyForm.Quantity_Volume_of_Leads__c);
            System.assertEquals(50, updatedSurveyForm.Office_Admin_Support__c);
            System.assertEquals(100, updatedSurveyForm.Working_for_Aspect__c);
        }
    }
}