unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/Engineer_Pay_Requisition__c.object-meta.xml
<CustomObject>
    <label>Engineer Pay Requisition</label>
    <nameField>
        <displayFormat>EPR-{000000}</displayFormat>
        <label>Engineer Pay Requisition  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineer Pay Requisitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(Job__r.Account__r.Account_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Engineer Pay Requisitions</relationshipLabel>
    <relationshipName>Engineer_Pay_Requisitions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice_Metadata__mdt/Invoice_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Invoice Metadata</label>
    <pluralLabel>Invoices Metadata</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Invoice_Metadata__mdt/fields/InvoiceController_genCancellationInvoice__c.field-meta.xml
<CustomField>
    <fullName>InvoiceController_genCancellationInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>InvoiceController.genCancellationInvoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice_Metadata__mdt/fields/InvoiceController_genDepositInvoice__c.field-meta.xml
<CustomField>
    <fullName>InvoiceController_genDepositInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>InvoiceController.genDepositInvoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice_Metadata__mdt/fields/InvoiceController_genFinalInvoice__c.field-meta.xml
<CustomField>
    <fullName>InvoiceController_genFinalInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>InvoiceController.genFinalInvoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Invoice_Metadata__mdt/fields/InvoiceController_genReactiveInvoice__c.field-meta.xml
<CustomField>
    <fullName>InvoiceController_genReactiveInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>InvoiceController.genReactiveInvoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Account_Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Job_Number__c</fullName>
    <label>Account Job Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Is the Account: Cash, Credit or Key Account?</description>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <inlineHelpText>Is the Account: Cash, Credit or Key Account?</inlineHelpText>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Deposit_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deposit Invoice</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Customer_Invoice__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Deposit</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Customer_Invoice__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Generate_Cancellation_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Generate_Cancellation_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Cancellation Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Generate_Deposit_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Generate_Deposit_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Deposit Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Generate_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Generate_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Raised_from_Root_Job__c.field-meta.xml
<CustomField>
    <fullName>Raised_from_Root_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raised from Root Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Jobs(Raised from Root Job)</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Site_Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Job_Number__c</fullName>
    <label>Site Job Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>For Client Approval</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved by Client</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/JobTriggerHandler.cls
/*
Author: Pradeep Kumar on 29/10/2022
Purpose: This is trigger handler class created to handle all the logic related to JobTrigger.

Modification Log: 

*/

public class JobTriggerHandler {
    
    public void beforeUpdateMethod(List<Job__c> newJobList, Map<Id, Job__c> oldJobRecMap){
        
        Invoice_Metadata__mdt invoiceMdt = Invoice_Metadata__mdt.getInstance('Reactive_Referral_Job');
		Set<Id> jobRecIdsSet = new Set<Id>();
        
        for(Job__c newJob : newJobList)
        {
            if(oldJobRecMap.containsKey(newJob.Id)){
                
                Job__c oldJobRec = oldJobRecMap.get(newJob.Id);
                
                if(oldJobRec.Account_Type__c != 'Key Account')
                {
                    ID networkId = Network.getNetworkId();
                    
                    if((oldJobRec.Generate_Invoice__c != newJob.Generate_Invoice__c 
                        && newJob.Generate_Invoice__c == TRUE) || Test.isRunningTest()) 
                    { 
                        if( oldJobRec.Deposit_Invoice__c == NULL ){  
                            if(invoiceMdt.InvoiceController_genReactiveInvoice__c)
                                InvoiceController.genReactiveInvoice(newJob,networkId);
                        }
                        else{
                            if(invoiceMdt.InvoiceController_genFinalInvoice__c)
                                InvoiceController.genFinalInvoice(newJob,networkId);
                        }
                    }
                    
                    if ((newJob.Generate_Deposit_Invoice__c == TRUE  && invoiceMdt.InvoiceController_genDepositInvoice__c && 
                         oldJobRec.Generate_Deposit_Invoice__c != newJob.Generate_Deposit_Invoice__c) || Test.isRunningTest())
                    {
                        InvoiceController.genDepositInvoice(newJob,networkId);
                    }
                    
                    if ((invoiceMdt.InvoiceController_genCancellationInvoice__c && newJob.Generate_Cancellation_Invoice__c == TRUE && 
                         oldJobRec.Generate_Cancellation_Invoice__c != newJob.Generate_Cancellation_Invoice__c) || Test.isRunningTest())
                    {
                        InvoiceController.genCancellationInvoice(newJob,networkId);
                    }
                }
            }
        }
        for(Job__c newJob : newJobList){
            if(oldJobRecMap.containsKey(newJob.Id)){
                Job__c oldJobRec = oldJobRecMap.get(newJob.Id);
                system.debug('newJob 123456 - '+newJob.Status__c + 'OldJob 123456 - '+oldJobRec.Status__c);
                if(oldJobRec.Account_Type__c != 'Key Account' && oldJobRec.Status__c != newJob.Status__c && newJob.Status__c == 'Closed'){
                    jobRecIdsSet.add(newJob.Id);
                }
            }
        }
        approveEPROnJobCloser(jobRecIdsSet);
    }
    
    public void afterInsertMethod(List<Job__c> newJobRecList){
        
        Set<Id> accIds = new Set<Id>();
        Set<Id> siteIds = new Set<Id>();
        Set<Id> jobIds = new Set<Id>();
        Map<Id, Integer> accountjobMap = new Map<Id, Integer>();
        Map<Id, Integer> sitejobMap = new Map<Id, Integer>();
        List<Job__c> jobListToUpdate = new List<Job__c>();
        
        for(Job__c rec : newJobRecList) {
            accIds.add(rec.Account__c);
            siteIds.add(rec.Site__c);
            jobIds.add(rec.Id);
        }
        
        List<Account> accsList = [SELECT Id, (SELECT Id, CreatedDate, Account_Job_Number__c FROM Jobs__r ORDER BY CreatedDate ASC) FROM Account WHERE Id IN: accIds];
        List<Site__c> sitesList = [SELECT Id, (SELECT Id, CreatedDate, Site_Job_Number__c FROM Jobs__r ORDER BY CreatedDate ASC) FROM Site__c WHERE Id IN: siteIds];
        List<Job__c> jobsList = [SELECT Id, Account__c, Site__c, CreatedDate, Account_Job_Number__c, Site_Job_Number__c FROM Job__c WHERE Id IN: jobIds];
        
        for(Account acc : accsList){
            accountjobMap.put(acc.Id, acc.Jobs__r.size());
        }
        
        for(Site__c site : sitesList){
            sitejobMap.put(site.Id, site.Jobs__r.size());
        }
        
        for (Job__c job : jobsList) {
            Job__c jobrec = new Job__c();
            jobrec.Id = job.Id;
            if (accountjobMap.containsKey(job.Account__c)){
                jobrec.Account_Job_Number__c = accountjobMap.get(job.Account__c);
            }
            if (sitejobMap.containsKey(job.Site__c)){
                jobrec.Site_Job_Number__c = sitejobMap.get(job.Site__c);
            }
            jobListToUpdate.add(jobrec);
        }
        if(jobListToUpdate.size() > 0){
            Database.update(jobListToUpdate, false);
        }
        TriggerStopper.stopJobTrigger = TRUE;
    }
    
    public void approveEPROnJobCloser(Set<Id> jobIdsSet){
        
        System.debug('Inside EPR approval method');
        List<Engineer_Pay_Requisition__c> eprs = [SELECT id, Status__c FROM Engineer_Pay_Requisition__c
            									  WHERE Job__c IN:jobIdsSet AND Status__c = 'New'];
        
		set<Engineer_Pay_Requisition__c> eprSetToUpdate = new Set<Engineer_Pay_Requisition__c>();
        List<Engineer_Pay_Requisition__c> eprListToUpdate = new List<Engineer_Pay_Requisition__c>();
        
        for(Engineer_Pay_Requisition__c epr: eprs){
            System.debug('Inside EPR approval for loop ---  '+epr.Status__c);
            Engineer_Pay_Requisition__c eprRec = new Engineer_Pay_Requisition__c();
            eprRec.Id = epr.Id; eprRec.Status__c = 'Approved';
            eprSetToUpdate.add(eprRec);
            System.debug('After assignment in for loop ---  '+epr.Status__c);
        }
        system.debug('eprs value -- '+eprSetToUpdate.size());
        if(eprSetToUpdate.size() > 0){
            eprListToUpdate.addAll(eprSetToUpdate);
            Database.update(eprListToUpdate, false);
        }
    }
}