unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Credit_Note__c/Customer_Credit_Note__c.object-meta.xml
<CustomObject>
    <label>Customer Credit Note</label>
    <nameField>
        <displayFormat>CCR-{000000}</displayFormat>
        <label>Customer Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Credit_Note__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Customer_Invoice__r.Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Credit_Note__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>Customer_Invoice__r.Account_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Credit_Note__c/fields/Customer_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Customer_Invoice__c</fullName>
    <label>Customer Invoice</label>
    <referenceTo>Customer_Invoice__c</referenceTo>
    <relationshipLabel>Customer Credit Notes</relationshipLabel>
    <relationshipName>Credit_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/Customer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Invoices</relationshipLabel>
    <relationshipName>Customer_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Cash, Credit or Key Account</description>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <inlineHelpText>Cash, Credit or Key Account</inlineHelpText>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>This will show the Date the invoice was raised</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Number of days credit given on Customer Invoices</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Exchequer_Export_Job__c/Exchequer_Export_Job__c.object-meta.xml
<CustomObject>
    <label>Exchequer Export Job</label>
    <nameField>
        <label>Exchequer_Export_Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchequer_Export_Job</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Exchequer_Export_Job__c/fields/Job_Category__c.field-meta.xml
<CustomField>
    <fullName>Job_Category__c</fullName>
    <label>Job Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchases</fullName>
            </value>
            <value>
                <fullName>Engineer Costs</fullName>
            </value>
            <value>
                <fullName>Sales Cash</fullName>
            </value>
            <value>
                <fullName>Sales Credit</fullName>
            </value>
            <value>
                <fullName>Sales Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Exchequer_Export_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Exchequer_Export_Job__c/fields/Submitted__c.field-meta.xml
<CustomField>
    <fullName>Submitted__c</fullName>
    <label>Submitted</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Exchequer_Export_Job__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exchequer_Export_Job</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Finance_App_Date_Ranges__mdt/Finance_App_Date_Ranges__mdt.object-meta.xml
<CustomObject>
    <label>Finance App Date Ranges</label>
    <pluralLabel>Finance App Date Ranges</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Finance_App_Date_Ranges__mdt/fields/Job_Category__c.field-meta.xml
<CustomField>
    <fullName>Job_Category__c</fullName>
    <label>Job Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchases</fullName>
                <default>true</default>
                <label>Purchases</label>
            </value>
            <value>
                <fullName>Engineer Costs</fullName>
            </value>
            <value>
                <fullName>Sales Cash</fullName>
            </value>
            <value>
                <fullName>Sales Credit</fullName>
            </value>
            <value>
                <fullName>Sales Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Finance_App_Date_Ranges__mdt/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Note__c/Supplier_Credit_Note__c.object-meta.xml
<CustomObject>
    <label>Supplier Credit Note</label>
    <nameField>
        <displayFormat>SCN{000000}</displayFormat>
        <label>Chumley Supplier Credit Note Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Credit Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier_Credit_Note__c/fields/Supplier_Credit_Note_Date__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Credit_Note_Date__c</fullName>
    <label>Supplier Credit Note Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Credit_Note__c/fields/Supplier_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Invoice__c</fullName>
    <label>Supplier Invoice</label>
    <referenceTo>Supplier_Invoice__c</referenceTo>
    <relationshipLabel>Supplier Credit Notes</relationshipLabel>
    <relationshipName>Supplier_Credit_Notes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/Supplier_Invoice__c.object-meta.xml
<CustomObject>
    <description>Supplier Invoice</description>
    <label>Supplier Invoice</label>
    <nameField>
        <displayFormat>SI-{000000}</displayFormat>
        <label>Salesforce Internal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(Purchase_Order__r.Supplier_Account__r.Account_Type__c)</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>Date on Supplier’s Invoice</description>
    <label>Invoice Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Supplier Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Supplier_Invoice_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ready to Send</fullName>
    </customValue>
    <customValue>
        <fullName>Part Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Outstanding</fullName>
        <default>true</default>
        <label>Outstanding</label>
    </customValue>
    <customValue>
        <fullName>In Post</fullName>
        <isActive>false</isActive>
        <label>In Post</label>
    </customValue>
    <customValue>
        <fullName>Reconciled</fullName>
        <isActive>false</isActive>
        <label>Reconciled</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
        <isActive>false</isActive>
        <label>Received</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <isActive>false</isActive>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>With Engineer</fullName>
        <isActive>false</isActive>
        <label>With Engineer</label>
    </customValue>
    <description>Number of days credit given on Customer Invoices</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Supplier_Invoice_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
    </customValue>
    <customValue>
        <fullName>Post_to_Exchequer</fullName>
        <label>Post to Exchequer</label>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <isActive>false</isActive>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Invoice</fullName>
        <isActive>false</isActive>
        <label>Invoice</label>
    </customValue>
    <customValue>
        <fullName>Update</fullName>
        <isActive>false</isActive>
        <label>Update</label>
    </customValue>
    <customValue>
        <fullName>Exported</fullName>
        <isActive>false</isActive>
        <label>Exported</label>
    </customValue>
    <customValue>
        <fullName>Ready to Export</fullName>
        <isActive>false</isActive>
        <label>Ready to Export</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
        <isActive>false</isActive>
        <label>Open</label>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <isActive>false</isActive>
        <label>Draft</label>
    </customValue>
    <description>Status of the invoice</description>
    <masterLabel>Supplier Invoice Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/FinanceAppController.cls
public with sharing class FinanceAppController implements Metadata.DeployCallback {
    @AuraEnabled
    public static List<Exchequer_Export_Job__c> getJobs() {
		return [
            SELECT Id, Name, Job_Category__c, Status__c, User__r.Name, Completed__c, Submitted__c, Start_Date__c, End_Date__c
            FROM Exchequer_Export_Job__c
            WHERE Start_Date__c >: Date.today() - 62 OR End_Date__c >: Date.today() - 62 OR (Start_Date__c <: Date.today() + 3 AND End_Date__c >: Date.today() - 62)
        ];
    }
    
    @AuraEnabled
    public static Map<String, List<sObject>> getInfoFromDateRange(String type, Date startDate, Date endDate) {
        Map<String, List<sObject>> resultMap = new Map<String, List<sObject>>();
        
        
/*        
        if (type != null && type.split(' ').size() != 1) {
            resultMap.put('Invoices' , [SELECT Id FROM Customer_Invoice__c WHERE Date__c >=: startDate AND Date__c <=: endDate
                               						  AND Account__r.Account_Type__c =: type.split(' ').get(1)]);
            resultMap.put('Refunds' , [SELECT Id FROM asp04__Refund__c WHERE
                                  				asp04__Payment_Date__c >=: startDate AND asp04__Payment_Date__c <=: endDate
                          AND Account__r.Account_Type__c =: type.split(' ').get(1)]);
            resultMap.put('Accounts' , [SELECT Id FROM Account WHERE
                        CreatedDate >=: startDate AND CreatedDate <=: endDate AND Account_Type__c =: type.split(' ').get(1)]);
        } else {
            resultMap.put('Invoices' , [SELECT Id FROM Customer_Invoice__c WHERE Date__c >=: startDate AND Date__c <=: endDate]);
            resultMap.put('Refunds' , [SELECT Id  FROM asp04__Refund__c WHERE
                                  				asp04__Payment_Date__c >=: startDate AND asp04__Payment_Date__c <=: endDate]);
            resultMap.put('Accounts' , [SELECT Id FROM Account WHERE
                        CreatedDate >=: startDate AND CreatedDate <=: endDate AND Account_Type__c =: type]);
        }*/
        
		resultMap.put('Invoices' , [
            SELECT Id FROM Customer_Invoice__c 
            WHERE Date__c >=: startDate 
            AND Date__c <=: endDate 
            AND id NOT IN (SELECT Customer_Invoice__c FROM asp04__Payment__c  
            WHERE asp04__Payment_Date__c >=: startDate 
            AND asp04__Payment_Date__c <=: endDate
            AND asp04__Payment_Stage__c = 'Collected from customer'
            AND asp04__Payment_Route_Selected__c = 'Card'
            AND Is_SRI_Candidate__c = TRUE)
        ]);
         
        resultMap.put('MatchedInvoices' , [
            SELECT Id FROM asp04__Payment__c  
            WHERE asp04__Payment_Date__c >=: startDate 
            AND asp04__Payment_Date__c <=: endDate
            AND asp04__Payment_Stage__c = 'Collected from customer'
            AND asp04__Payment_Route_Selected__c = 'Card'
            AND Is_SRI_Candidate__c = TRUE
        ]);
        
        resultMap.put('Payments' , [
            SELECT Id FROM asp04__Payment__c  
            WHERE asp04__Payment_Date__c >=: startDate 
            AND asp04__Payment_Date__c <=: endDate 
            AND Is_SRI_Candidate__c = FALSE
            AND asp04__Payment_Stage__c = 'Collected from customer'
            AND asp04__Payment_Route_Selected__c = 'Card'
        ]);
        
        resultMap.put('Accounts' , [
            SELECT Id FROM Account 
            WHERE CreatedDate >=: startDate 
            AND CreatedDate <=: endDate 
        ]);
         resultMap.put('Refunds' , [
             SELECT Id FROM asp04__Refund__c 
             WHERE asp04__Payment_Date__c >=: startDate 
             AND asp04__Payment_Date__c <=: endDate
             AND asp04__Payment_Route__c = 'Card'
             AND asp04__Refund_Stage__c = 'Refunded to customer'
         ]);
        resultMap.put('CreditNotes' , [
            SELECT Id FROM Customer_Credit_Note__c 
            WHERE Date__c >=: startDate AND Date__c <=: endDate
        ]);
        resultMap.put('SupplierInvoices' , [
            SELECT Id FROM Supplier_Invoice__c 
            WHERE Invoice_Date__c >=: startDate 
            AND Invoice_Date__c <=: endDate]);
        
        resultMap.put('SupplierCreditNotes' , [
            SELECT Id FROM Supplier_Credit_Note__c 
            WHERE Supplier_Credit_Note_Date__c >=: startDate AND Supplier_Credit_Note_Date__c <=: endDate
        ]);
        return resultMap;
    }

    @AuraEnabled
    public static Map<String, Integer> getDataFromDateRange(String type, Date startDate, Date endDate) {
        Map<String, List<sObject>> newMap = FinanceAppController.getInfoFromDateRange(type, startDate, endDate);
        Map<String, Integer> resultMap = new Map<String, Integer>();
        resultMap.put('Invoices' , newMap.get('Invoices').size());
        resultMap.put('MatchedInvoices' , newMap.get('MatchedInvoices').size());
        resultMap.put('Payments' , newMap.get('Payments').size());
        resultMap.put('Refunds' , newMap.get('Refunds').size());
        resultMap.put('CreditNotes' , newMap.get('CreditNotes').size());
        resultMap.put('Accounts' , newMap.get('Accounts').size());
        return resultMap;
    }

    @AuraEnabled
    public static Date getStartDateFromMetadata(String type) {
        Date result;
        List<Finance_App_Date_Ranges__mdt> mcs = Finance_App_Date_Ranges__mdt.getAll().values();
        for (Finance_App_Date_Ranges__mdt range : mcs) {
            if (range.Job_Category__c == type) {
                result = range.Start_Date__c;
            }
        }
        return result;
    }

    @AuraEnabled
    public static void createExportJob(String type, Date startDate, Date endDate) {
        List<Exchequer_Export_Job__c> pJob = [
            SELECT Id, Name, Job_Category__c
            FROM Exchequer_Export_Job__c
            WHERE Job_Category__c =: 'Purchases'
            OR Job_Category__c =: 'Engineer Costs'
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
        List<Exchequer_Export_Job__c> sJob = [
            SELECT Id, Name, Job_Category__c
            FROM Exchequer_Export_Job__c
            WHERE Job_Category__c =: 'Sales Cash'
            OR Job_Category__c =: 'Sales Credit'
            OR Job_Category__c =: 'Sales Key'
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        Exchequer_Export_Job__c job = new Exchequer_Export_Job__c();
        if (pJob.size() == 0 && (type == 'Purchases' || type == 'Engineer Costs')) {
            job.Name = 'P1';
        } else if (sJob.size() == 0 && (type != 'Purchases' && type != 'Engineer Costs')) {
            job.Name = 'S1';
        } else if (sJob.size() != 0 && pJob.size() != 0) {
            Integer pNumber = Integer.valueOf(pJob[0].Name.split('P')[1]);
            Integer sNumber = Integer.valueOf(sJob[0].Name.split('S')[1]);
            job.Name = type == 'Purchases' || type == 'Engineer Costs' ? 'P' + ++pNumber : 'S' + ++sNumber;
        }
        job.Job_Category__c = type;
        job.Status__c = 'Queued';
        job.User__c = UserInfo.getUserId();
        job.Submitted__c = System.now();
        job.Start_Date__c = startDate;
        job.End_Date__c = endDate;
        insert job;
		
        Map<String, List<SObject>> newMap = FinanceAppController.getInfoFromDateRange(type, startDate, endDate);
        List <FinanceImportFiles.CSVObjectWrapper1> csvObjectWrapperList1 = new List<FinanceImportFiles.CSVObjectWrapper1>();
        FinanceImportFiles.CSVObjectWrapper1 wrap = new FinanceImportFiles.CSVObjectWrapper1();
        
        System.debug('in FinanceAppController1 limits.getLimitHeapSize() >>> '+limits.getLimitHeapSize());
        System.debug('in FinanceAppController1 limits.getHeapSize() >>> '+limits.getHeapSize());
        
        
        wrap.excJobRecId = job.Id;
        wrap.accList = newMap.get('Accounts');
        newMap.remove('Accounts');
        wrap.custCreditNoteList = newMap.get('CreditNotes');
        newMap.remove('CreditNotes');
        //[SELECT Id FROM Customer_Credit_Note__c WHERE Date__c >: startDate AND Date__c <: endDate];
        wrap.suppInvoiceList = newMap.get('SupplierInvoices');
        newMap.remove('SupplierInvoices');
        //[SELECT Id FROM Supplier_Invoice__c WHERE Invoice_Date__c >: startDate AND Invoice_Date__c <: endDate];
        wrap.refundList = newMap.get('Refunds');
         newMap.remove('Refunds');
        //[SELECT Id FROM asp04__Refund__c WHERE asp04__Payment_Date__c >: startDate AND asp04__Payment_Date__c <: endDate];
        wrap.custInvoiceList = newMap.get('Invoices');
         newMap.remove('Invoices');
        //[ SELECT Id FROM Customer_Invoice__c WHERE Date__c >: startDate AND Date__c <: endDate];
        wrap.paymentList = newMap.get('Payments');
        System.debug('*** newMap get Payments: '+newMap.get('Payments'));
         newMap.remove('Payments');
        System.debug('*** wrap: '+wrap.paymentList);
        
         wrap.MatchedInvoiceList = newMap.get('MatchedInvoices');
         newMap.remove('MatchedInvoices');
        //[SELECT Id FROM asp04__Payment__c WHERE asp04__Payment_Date__c >: startDate AND asp04__Payment_Date__c <: endDate AND Is_SRI_Candidate__c = FALSE];
        wrap.suppCreditNoteList = newMap.get('SupplierCreditNotes');
         newMap.remove('SupplierCreditNotes');
        //[SELECT Id FROM Supplier_Credit_Note__c WHERE Supplier_Credit_Note_Date__c >: startDate AND Supplier_Credit_Note_Date__c <: endDate];
        csvObjectWrapperList1.add(wrap);
     
        System.debug('in FinanceAppController2 limits.getLimitHeapSize() >>> '+limits.getLimitHeapSize());
        System.debug('in FinanceAppController2 limits.getHeapSize() >>> '+limits.getHeapSize());
        
        System.enqueueJob(new FinanceImportFiles(csvObjectWrapperList1));
        FinanceAppController.updateMetadataDate(endDate, type);
    }

    @future
    public static void updateMetadataDate(Date endDate, String type) {
        List<Finance_App_Date_Ranges__mdt> mcs = Finance_App_Date_Ranges__mdt.getAll().values();
        Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
        for (Finance_App_Date_Ranges__mdt range : mcs) {
            if (range.Job_Category__c == type) {
                Metadata.CustomMetadata customMetadata = new Metadata.CustomMetadata();
                customMetadata.fullName = 'Finance_App_Date_Ranges.' + range.QualifiedApiName;
                customMetadata.label = range.label;

                Metadata.CustomMetadataValue customField = new Metadata.CustomMetadataValue();
                customField.field = 'Start_Date__c';
                customField.value = endDate + 1;
                customMetadata.values.add(customField);

                mdContainer.addMetadata(customMetadata);
            }
        }
        FinanceAppController callback = new FinanceAppController();
        if (!Test.isRunningTest()) {
            Id jobId = Metadata.Operations.enqueueDeployment(mdContainer, callback);
        }
    }

    public void handleResult(Metadata.DeployResult result, Metadata.DeployCallbackContext context) {
        if (result.status == Metadata.DeployStatus.Succeeded) {
            System.debug('Success: ' + result);
        } else {
            System.debug('Fail: ' + result);
        }
    }
       
}