unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Status of the Account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Is_Provider_a_Franchisee__c.field-meta.xml
<CustomField>
    <fullName>Is_Provider_a_Franchisee__c</fullName>
    <description>Determines whether the Provider is a Franchisee or not</description>
    <label>Is Provider a Franchisee?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <label>Commercial</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Domestic.recordType-meta.xml
<RecordType>
    <fullName>Domestic</fullName>
    <active>true</active>
    <label>Domestic</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Payment_Provider.recordType-meta.xml
<RecordType>
    <fullName>Payment_Provider</fullName>
    <active>true</active>
    <description>Engineer payment provider e.g InSync and Crystal Tax</description>
    <label>Payment Provider</label>
</RecordType>

unpackaged/main/default/objects/AssignedResource/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>This is the Engineer Role from the Service Resource</description>
    <label>Engineer Role</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Site related to the Contact</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Deduction__c/Deduction__c.object-meta.xml
<CustomObject>
    <description>All deductions to the Engineer will be logged here. This will affect the Engineer wages</description>
    <label>Engineer Deduction</label>
    <nameField>
        <displayFormat>ED-{000000}</displayFormat>
        <label>Deduction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineer Deductions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Deduction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount to be deducted</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Deduction__c/fields/Deduction_Type__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Type__c</fullName>
    <label>Deduction Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deduction_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Deduction_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Deduction__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <description>The service resource associated with the deduction</description>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Engineer Deductions</relationshipLabel>
    <relationshipName>Deductions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Group__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <referenceTo>Trade__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Region_Area__c/Region_Area__c.object-meta.xml
<CustomObject>
    <description>This will show all of the Areas within regions that Aspect operates within. Whenever a new expansion happens, A region record is created or data loaded, a new region public group is created and the Sharing settings based on Region Areas are updated.</description>
    <label>Region Area</label>
    <nameField>
        <label>Region Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Region Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Region_Area__c/fields/Region_Area_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Area_Code__c</fullName>
    <label>Region Area Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(Account.Account_Type__c)</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>This will be from the Assigned Resources</description>
    <label>Engineer Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Deduction__c.field-meta.xml
<CustomField>
    <fullName>Deduction__c</fullName>
    <label>Deduction</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Resource Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>The main role the resource takes</description>
    <label>Engineer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <description>Resource Mobile No</description>
    <label>Mobile No</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trade</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Visitour_Engineer_ID__c.field-meta.xml
<CustomField>
    <fullName>Visitour_Engineer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Visitour Engineer ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email to contact the related Site</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Region_Area__c.field-meta.xml
<CustomField>
    <fullName>Region_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Will be used to Lookup up the region code from the site postcode</description>
    <label>Region Area</label>
    <referenceTo>Region_Area__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Region_Area_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Area_Code__c</fullName>
    <formula>Region_Area__r.Region_Area_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region Area Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Site_PostalCode__c</fullName>
    <description>Site postal address</description>
    <label>Site PostalCode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/SiteGeo_Latitude__c.field-meta.xml
<CustomField>
    <fullName>SiteGeo_Latitude__c</fullName>
    <description>This field stores the latitude of the address from FLS Visitour</description>
    <label>SiteGeo Latitude</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/SiteGeo_Longitude__c.field-meta.xml
<CustomField>
    <fullName>SiteGeo_Longitude__c</fullName>
    <description>This field stores the longitude of the Address from FLS Visitour</description>
    <label>SiteGeo Longitude</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Site__c/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <label>Commercial</label>
</RecordType>

unpackaged/main/default/objects/Site__c/recordTypes/Domestic.recordType-meta.xml
<RecordType>
    <fullName>Domestic</fullName>
    <active>true</active>
    <label>Domestic</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status form Account object</description>
    <formula>TEXT( Account.Account_Status__c )</formula>
    <inlineHelpText>Account Status</inlineHelpText>
    <label>Account Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TRIM(TEXT(Account.Account_Type__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Region_Area_Code__c.field-meta.xml
<CustomField>
    <fullName>Region_Area_Code__c</fullName>
    <description>This shows which Region Area that the Work Order belongs to</description>
    <formula>Site__r.Region_Area_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region Area Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated only through the flow</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <description>Trade for the Work Type - added this for the H&amp;S Flow + thought it better to use a formula than look it up each time.</description>
    <formula>TEXT( WorkType.Trade__c )</formula>
    <inlineHelpText>Trade for the Work Type</inlineHelpText>
    <label>Trade</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Fixed_Price.recordType-meta.xml
<RecordType>
    <fullName>Fixed_Price</fullName>
    <active>true</active>
    <label>Fixed Price</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/recordTypes/Reactive.recordType-meta.xml
<RecordType>
    <fullName>Reactive</fullName>
    <active>true</active>
    <label>Reactive</label>
</RecordType>

unpackaged/main/default/objects/WorkType/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trade</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkType/recordTypes/Fixed_Price.recordType-meta.xml
<RecordType>
    <fullName>Fixed_Price</fullName>
    <active>true</active>
    <label>Fixed Price</label>
</RecordType>

unpackaged/main/default/objects/WorkType/recordTypes/Reactive.recordType-meta.xml
<RecordType>
    <fullName>Reactive</fullName>
    <active>true</active>
    <label>Reactive</label>
</RecordType>

unpackaged/main/default/globalValueSets/Account_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>On Stop</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
        <isActive>false</isActive>
        <label>On Hold</label>
    </customValue>
    <customValue>
        <fullName>See Credit Control</fullName>
        <isActive>false</isActive>
        <label>See Credit Control</label>
    </customValue>
    <customValue>
        <fullName>Close</fullName>
        <isActive>false</isActive>
        <label>Close</label>
    </customValue>
    <description>Status of the Account</description>
    <masterLabel>Account Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Deduction_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Air Conditioning Labels</fullName>
    </customValue>
    <customValue>
        <fullName>Aspect Folder</fullName>
    </customValue>
    <customValue>
        <fullName>Aspect Purchase Order</fullName>
    </customValue>
    <customValue>
        <fullName>Bank Transfer Fee (for advance)</fullName>
    </customValue>
    <customValue>
        <fullName>Box Junction (PCN)</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Lane (PCN)</fullName>
    </customValue>
    <customValue>
        <fullName>Call backs</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Kept</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Kept Admin Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Congestion Charge (PCN)</fullName>
    </customValue>
    <customValue>
        <fullName>CRB deduction</fullName>
    </customValue>
    <customValue>
        <fullName>Dart Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Dartford Charge (PCN)</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Safe Register Deduction</fullName>
    </customValue>
    <customValue>
        <fullName>ID Card</fullName>
    </customValue>
    <customValue>
        <fullName>IT Deduction - Other</fullName>
    </customValue>
    <customValue>
        <fullName>Job Deduction - Other</fullName>
    </customValue>
    <customValue>
        <fullName>Laptop</fullName>
    </customValue>
    <customValue>
        <fullName>Laptop Charger</fullName>
    </customValue>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Phone Car Charger</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Phone Case</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Phone Charger</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Phone Hands Free</fullName>
    </customValue>
    <customValue>
        <fullName>Negative Pay Balance (From Previous Month)</fullName>
    </customValue>
    <customValue>
        <fullName>No Entry (PCN)</fullName>
    </customValue>
    <customValue>
        <fullName>No Turn (PCN)</fullName>
    </customValue>
    <customValue>
        <fullName>Overpaid</fullName>
    </customValue>
    <customValue>
        <fullName>MV Repair Deduction</fullName>
        <isActive>false</isActive>
        <label>MV Repair Deduction</label>
    </customValue>
    <masterLabel>Deduction Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Engineer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service_Resource</fullName>
        <label>Service Resource</label>
    </customValue>
    <customValue>
        <fullName>Franchisee</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
        <isActive>false</isActive>
        <label>Engineer</label>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
        <isActive>false</isActive>
        <label>Manager</label>
    </customValue>
    <customValue>
        <fullName>Estimator</fullName>
        <isActive>false</isActive>
        <label>Estimator</label>
    </customValue>
    <description>The main role the resource takes</description>
    <masterLabel>Engineer Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TestDataFactory.cls
/**
 * @author      Andrey Gorun
 * @version     1.0
 */

@isTest
public class TestDataFactory {
    public final static Map<String,Schema.RecordTypeInfo> workOrderRecordTypes = Schema.SObjectType.WorkOrder.getRecordTypeInfosByDeveloperName();

    public static List<Account> createAccounts(Integer numberAccounts) {
        Id defaultRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Payment_Provider').getRecordTypeId();
        return createAccounts(numberAccounts, defaultRecordTypeId);
    }
    public static List<Account> createAccounts(Integer numberAccounts, Id recordTypeId) {
        List<Account> accounts = new List<Account>();

        for (Integer i = 0; i < numberAccounts; i++) {
            Account acc = new Account (
                Name = 'TestAccount' + i,
                RecordTypeId = recordTypeId,
                Account_Type__c = 'Cash',
                Email__c = 'testAccountEmail' + i + '@email.test',
                Account_Status__c = 'Open',
                BillingPostalCode = 'NW1 3HG',
                BillingStreet = '4 Triton Square, , LONDON,',
                BillingCity = 'London',
                BillingCountry = 'United Kingdom',
                Last_Name__c = 'Last Name'
                //Is_Provider_a_Franchisee__c = 'No'
            );
            accounts.add(acc);
        }
        return accounts;
    }

  /*  public static List<Payment_Batch__c> createPaymentBatches(Integer numberPaymentBatches) {
        List<Payment_Batch__c> paymentBatches = new List<Payment_Batch__c>();

        for (Integer i = 0; i < numberPaymentBatches; i++) {
            Payment_Batch__c paymentBatch = new Payment_Batch__c (
                Description__c = 'TestPaymentBatch' + i,
                Payment_Run_From_Date__c = System.Date.today().addMonths(-1),
                Payment_Run_To_Date__c = System.Date.today()
            );
            paymentBatches.add(paymentBatch);
        }
        return paymentBatches;
    }
 */

    public static List<ServiceResource> createServiceResources(List<User> users) {
        List<ServiceResource> serviceResources = new List<ServiceResource>();

        for (Integer i = 0; i < users.size(); i++) {
            ServiceResource serviceResource = new ServiceResource (
                Name = 'TestServiceResource' + i,
                RelatedRecordId = users.get(i).Id,
                isActive = true,
                Engineer_Role__c = 'Service_Resource',
                Visitour_Engineer_ID__c = '123',
                Email__c = 'blahblah@test.com',
                Mobile_No__c = '7876567849'
            );
            serviceResources.add(serviceResource);
        }
        return serviceResources;
    }

    public  static List<User> createUsers(String profileName, Integer numberUsers) {
        Id profileId = [SELECT Id FROM Profile WHERE Name = :profileName].Id;
        List<User> users = new List<User>();

        for (Integer i = 0; i < numberUsers; i++) {
            User usr = new User (
                ProfileId = profileId,
                LastName = 'TestUser' + i,
                Email = 'TestUser' + i + '@testoism.com',
                Username = 'TestUser' + i + '@testoism.com',
                CompanyName = 'TestCompany',
                Title = 'title',
                Alias = 'alias',
                TimeZoneSidKey = 'America/Los_Angeles',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US'
            );
            users.add(usr);
        }
        return users;
    }

    public  static User createUser(String profileName, String userName) {
        Id profileId = [SELECT Id FROM Profile WHERE Name = :profileName].Id;
        User usr = new User (
                ProfileId = profileId,
                LastName = userName,
                Email = userName + '@testoism.com',
                Username = userName + '@testoism.com',
                CompanyName = 'TestCompany',
                Title = 'title',
                Alias = 'alias',
                TimeZoneSidKey = 'America/Los_Angeles',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US'
        );
        return usr;
    }


    public static List<Deduction__c> createEngineerDeductions(Integer numberEngineerDeductions, ServiceResource serviceResourceEngineer) {
        List<Deduction__c> engineerDeductions = new List<Deduction__c>();

        for (Integer i = 0; i < numberEngineerDeductions; i++) {
            Deduction__c engineerDeduction = new Deduction__c (Service_Resource__c= serviceResourceEngineer.Id, Amount__c=150, Deduction_Type__c='MV Repair Deduction'
            );
            engineerDeductions.add(engineerDeduction);
        }
        return engineerDeductions;
    }
    
    public static List<WorkType> createWorkTypes(Integer numberWorkTypes) {
      List<WorkType> lstworkTypes = new List<WorkType>();
        WorkType workType = new WorkType (
           // Trade__c = 'Plumbing',
            Name = 'Test Plumbing',
            RecordTypeId = Schema.SObjectType.WorkType.getRecordTypeInfosByDeveloperName().get('Reactive').getRecordTypeId(),
            DurationType = 'Hours',
            EstimatedDuration = 2.00
        );
        lstworkTypes.add(workType);
        return lstworkTypes;
    }
    
    public static Site__c createSite(Account acc){
      Region_Area__c regionArea = new Region_Area__c (
            Region_Area_Code__c = 'aa2a'
        );
        insert regionArea;
        Site__c site = new Site__c (
            Site_PostalCode__c = 'aa2a 2aa',//a-zA-Z]{2}\\d[a-zA-Z]\\s\\d[a-zA-Z]{2}"),
            Region_Area__c = regionArea.Id,
            //RecordTypeId = Schema.SObjectType.Site__c.getRecordTypeInfosByDeveloperName().get(acc.RecordType.DeveloperName).getRecordTypeId(),
            RecordTypeId = Schema.SObjectType.Site__c.getRecordTypeInfosByDeveloperName().get('Domestic').getRecordTypeId(),
            Account__c = acc.Id,
            SiteGeo_Longitude__c = 1212335,
            SiteGeo_Latitude__c = 5675346
        );
        return site;
    }
    
    public static List<WorkOrder> createWorkorders(Integer numberWorkOrders, Site__c site, WorkType wt) {
      List<WorkOrder> workOrders = new List<WorkOrder>();
      for (Integer i = 0; i < numberWorkOrders; i++) {
            WorkOrder workOrder = new WorkOrder (
         //       Client_Status__c = 'New',
                Status = 'New',
                RecordTypeId = workOrderRecordTypes.get('Reactive').getRecordTypeId(),
                //Contact_Email__c = 'testAccountEmailWork@email.test',
                Site__c = site.Id,
                Time__c = '8AM',
                WorkTypeId = wt.Id
            );
            workOrders.add(workOrder);
        }
        return workOrders;
    }

    public static List<WorkOrder> createWorkorders(Integer numberWorkOrders) {
         Account acc = new Account (
                Name = 'TestAccountWorkOrder '+String.valueOf(Math.round((Math.random() * (900000) + 100000))),
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Commercial').getRecordTypeId(),
                Account_Type__c = 'Cash',
                Account_Status__c = 'Open',
                Email__c = 'testAccountEmailWork@email.test',
                BillingPostalCode = 'NW1 3HG',
                BillingStreet = '4 Triton Square',
                BillingCity = 'London',
                BillingCountry = 'United Kingdom',
                Last_Name__c = 'Last Name'
        );
        insert acc;
        Region_Area__c regionArea = new Region_Area__c (
            Region_Area_Code__c = 'aa2a'
        );
        insert regionArea;
        
        Contact primContact = new Contact(
        LastName='LastName',
            Account  = acc
            );
        insert primContact;
        /*[Select Id
                               From Contact
                               Where AccountId = :acc.Id];
        //record type should be created by builder process alread*/
        Site__c site = new Site__c (
            Site_PostalCode__c = 'aa2a 2aa',//a-zA-Z]{2}\\d[a-zA-Z]\\s\\d[a-zA-Z]{2}"),
            Region_Area__c = regionArea.Id,
            RecordTypeId = Schema.SObjectType.Site__c.getRecordTypeInfosByDeveloperName().get('Commercial').getRecordTypeId(),
            Account__c = acc.Id,
            SiteGeo_Longitude__c = 1212335,
            SiteGeo_Latitude__c = 5675346,
            Primary_Site_Contact__c = primContact.id
        );
        insert site;/*
        Site__c site = [Select Id
                        From Site__c
                        Where Account__c = :acc.Id];*/
        
        WorkType workType = new WorkType (
            //Trade__c = 'Air Conditioning',
           // Group__c = 'Air Conditioning Ducted Systems',
            Name = 'Air Conditioning Ducted Systems ; Installation',
            // RecordTypeId = Schema.SObjectType.WorkType.getRecordTypeInfosByDeveloperName().get('Reactive').getRecordTypeId(),
            DurationType = 'Hours',
            EstimatedDuration = 2.00
        );
        insert workType;
        List<WorkOrder> workOrders = new List<WorkOrder>();

        for (Integer i = 0; i < numberWorkOrders; i++) {
            WorkOrder workOrder = new WorkOrder (
                AccountId = acc.Id,
//                Client_Status__c = 'New',
                Status = 'New',
                RecordTypeId = workOrderRecordTypes.get('Reactive').getRecordTypeId(),
                //Contact_Email__c = 'testAccountEmailWork@email.test',
                Site__c = site.Id,
                Time__c = '8AM',
                WorkTypeId = workType.Id
                //ContactId = primContact.Id
            );
            workOrders.add(workOrder);
        }
        return workOrders;
    }
    
    public static List<WorkOrder> createWorkordersFixedPrice(Integer numberWorkOrders, Site__c site, WorkType wt) {
      List<WorkOrder> workOrders = new List<WorkOrder>();
      for (Integer i = 0; i < numberWorkOrders; i++) {
            WorkOrder workOrder = new WorkOrder (
                    AccountId = Site.Account__c,
                 //   Client_Status__c = 'New',
                    Status = 'New',
                    RecordTypeId = workOrderRecordTypes.get('Fixed_Price').getRecordTypeId(),
                    //Contact_Email__c = 'testAccountEmailWork@email.test',
                    Site__c = site.Id,
                    Time__c = '8AM',
                    StartDate = system.now().addDays(1),
                    EndDate = system.now().addDays(3),
                  WorkTypeId = wt.Id
            );
            workOrders.add(workOrder);
        }
        return workOrders;
    }

    public static List<WorkOrder> createWorkordersFixedPrice(Integer numberWorkOrders) {
        Account acc = new Account (
                Name = 'TestAccountWorkOrderFixed',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Commercial').getRecordTypeId(),
                Account_Type__c = 'Credit',
                Account_Status__c = 'Open',
                Email__c = 'testAccountEmailWorkFixed@email.test',
                BillingPostalCode = 'NW1 3HG',
                BillingStreet = '4 Triton Square, , LONDON,',
                BillingCity = 'London',
                BillingCountry = 'United Kingdom',
                Last_Name__c = 'Last Name 123'
        );
        insert acc;
        Region_Area__c regionArea = new Region_Area__c (
                Region_Area_Code__c = 'aa2a'
        );
        insert regionArea;

        Contact primContact = new Contact(
        LastName='LastName',
            Account  = acc
            );
        insert primContact;



        Site__c site = new Site__c (
                Site_PostalCode__c = 'aa2a 2aa',//a-zA-Z]{2}\\d[a-zA-Z]\\s\\d[a-zA-Z]{2}"),
                Region_Area__c = regionArea.Id,
                RecordTypeId = Schema.SObjectType.Site__c.getRecordTypeInfosByDeveloperName().get('Commercial').getRecordTypeId(),
                Account__c = acc.Id,
                Primary_Site_Contact__c = primContact.id,
                SiteGeo_Longitude__c = 1212335,
                SiteGeo_Latitude__c = 5675346
        );
        insert site;
         WorkType workType = new WorkType (
           // Trade__c = 'Plumbing',
            Name = 'Test Plumbing',
            // RecordTypeId = Schema.SObjectType.WorkType.getRecordTypeInfosByDeveloperName().get('Reactive').getRecordTypeId(),
            DurationType = 'Hours',
            EstimatedDuration = 2.00
        );
        insert workType;
        List<WorkOrder> workOrders = new List<WorkOrder>();

        for (Integer i = 0; i < numberWorkOrders; i++) {
            WorkOrder workOrder = new WorkOrder (
                    AccountId = acc.Id,
                  //  Client_Status__c = 'New',
                    Status = 'New',
                    RecordTypeId = workOrderRecordTypes.get('Fixed_Price').getRecordTypeId(),
                    //Contact_Email__c = 'testAccountEmailWork@email.test',
                    Site__c = site.Id,
                    Time__c = '8AM',
                    StartDate = system.now().addDays(1),
                    EndDate = system.now().addDays(3),
                  WorkTypeId = workType.Id
            );
            workOrders.add(workOrder);
        }
        return workOrders;
    }

    public static List<ServiceAppointment> createServiceAppointments(Integer numberServiceAppointments) {
        List<ServiceAppointment> serviceAppointments = new List<ServiceAppointment>();
        
        //Site__c site = createSite(createAccounts(1).get(0));
//        WorkOrder wo = createWorkordersFixedPrice(1).get(0);

        for (Integer i = 0; i < numberServiceAppointments; i++) {
            ServiceAppointment serviceAppointment = new ServiceAppointment (
                    Visitour_ID__c = '10000' + i,
                    EarliestStartTime = System.now().addMonths(-1),
                    DueDate = System.now().addMonths(1),
                    Status = 'Scheduled',
                    SchedStartTime = System.now().addDays(-1),
                    SchedEndTime = System.now().addDays(1)
//                  ParentRecordId = wo.Id
            );
            serviceAppointments.add(serviceAppointment);
        }
        return serviceAppointments;
    }

    public static AssignedResource createAssignedResource(Id serviceAppointmentId, Id serviceResourceId) {
        return new AssignedResource (
            ServiceAppointmentId = serviceAppointmentId,
            ServiceResourceId = serviceResourceId
        );
    }

    public static List<ServiceTerritory> createServiceTerritories(Integer numberServiceTerritories) {
        List<ServiceTerritory> serviceTerritories = new List<ServiceTerritory>();

        for (Integer i = 0; i < numberServiceTerritories; i++) {
            ServiceTerritory serviceTerritory = new ServiceTerritory (
                Name = 'TestServiceTerritory' + i,
                IsActive = true

            );
            serviceTerritories.add(serviceTerritory);
        }
        return serviceTerritories;
    }

    public static List<OperatingHours> createOperatingHours(Integer numberOperatingHour) {
        List<OperatingHours> serviceOperatingHours = new List<OperatingHours>();

        for (Integer i = 0; i < numberOperatingHour; i++) {
            OperatingHours serviceOperatingHour = new OperatingHours (
                    Name = 'TestOperatingHours' + i
            );
            serviceOperatingHours.add(serviceOperatingHour);
        }
        return serviceOperatingHours;
    }

    public static ServiceTerritoryMember createTerritoryMember(Id serviceResourceId, Id serviceTerritoryId) {
        return new ServiceTerritoryMember (
            //TerritoryType = 'Primary',
            ServiceResourceId = serviceResourceId,
            ServiceTerritoryId = serviceTerritoryId,
            EffectiveStartDate = System.now().addMonths(-1)
        );
    }
    
    public static asp04__Authorisation__c createAuthorisation(Id AccountId, Date expiryDate, String status, string description){
      asp04__Authorisation__c auth = new asp04__Authorisation__c(
                        Customer__c = accountId, 
                        asp04__Expiry_Date__c = expiryDate, 
                        asp04__Status__c = status, 
                        asp04__Status_Description__c = description);
      insert auth;
      return auth;
    }
}