unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Client_Alert_1__c.field-meta.xml
<CustomField>
    <fullName>Client_Alert_1__c</fullName>
    <description>Alert on account level 1</description>
    <label>Client Alert 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Client_Alert_2__c.field-meta.xml
<CustomField>
    <fullName>Client_Alert_2__c</fullName>
    <description>Alert on account level 2</description>
    <label>Client Alert 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Client_Alert__c.field-meta.xml
<CustomField>
    <fullName>Client_Alert__c</fullName>
    <label>Client Alert</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/BatchMassUpdateofAccountTest.cls
@isTest
public class BatchMassUpdateofAccountTest {
    static testMethod void createAccount() {
        Account acc = new Account();
        acc.Name ='Test';
        acc.Account_Type__c = 'Key Account';
        acc.Client_Alert__c ='Test';
        acc.Client_Alert_1__c ='Test';
        acc.Client_Alert_2__c ='Test';
        insert acc;
        Test.startTest();
        String accQuery = 'SELECT id,Name,Account_Type__c,CreatedDate,OwnerId,Owner.Name,Client_Alert__c,Client_Alert_1__c,Client_Alert_2__c from Account' ;
        BatchMassUpdateofAccount bdt = new BatchMassUpdateofAccount(accQuery);
        dataBase.executeBatch(bdt);
        Test.stopTest();
    }
}