unpackaged/main/default/objects/Account/fields/Account_Reference__c.field-meta.xml
<CustomField>
    <fullName>Account_Reference__c</fullName>
    <description>Account Reference - Used for Exchequer reference</description>
    <displayFormat>A{00000}</displayFormat>
    <externalId>true</externalId>
    <label>Account Reference</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Outstanding_Balance_Incl_VAT__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_Incl_VAT__c</fullName>
    <description>The Total Outstanding Balance (Incl. VAT) from All Customer Invoices</description>
    <inlineHelpText>The Total Outstanding Balance (Incl. VAT) from All Customer Invoices</inlineHelpText>
    <label>Outstanding Balance (Incl. VAT)</label>
    <summarizedField>Customer_Invoice__c.Balance_Outstanding_with_Interest__c</summarizedField>
    <summaryForeignKey>Customer_Invoice__c.Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/Customer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Invoices</relationshipLabel>
    <relationshipName>Customer_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Balance_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Balance_Outstanding__c</fullName>
    <formula>Charge_Gross__c -   Customer_Credit_Total__c - Sum_of_Payments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Charge_Gross__c.field-meta.xml
<CustomField>
    <fullName>Charge_Gross__c</fullName>
    <description>Sum of all the Line Item records using their &#39;Charge Gross&#39; value</description>
    <inlineHelpText>Sum of all the Line Item records using their &#39;Charge Gross&#39; value</inlineHelpText>
    <label>Charge Gross</label>
    <summarizedField>Customer_Invoice_Line_Item__c.Charge_Gross__c</summarizedField>
    <summaryForeignKey>Customer_Invoice_Line_Item__c.Customer_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Charge_Net__c.field-meta.xml
<CustomField>
    <fullName>Charge_Net__c</fullName>
    <formula>Charge_Rollup_Net__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Charge Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Charge_VAT__c.field-meta.xml
<CustomField>
    <fullName>Charge_VAT__c</fullName>
    <description>Roll-up of line item VAT</description>
    <label>Charge VAT</label>
    <summarizedField>Customer_Invoice_Line_Item__c.Charge_VAT__c</summarizedField>
    <summaryForeignKey>Customer_Invoice_Line_Item__c.Customer_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>This will show the Date the invoice was raised</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Job_Number__c.field-meta.xml
<CustomField>
    <fullName>Job_Number__c</fullName>
    <formula>Job__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <formula>IF( ISBLANK(Job__r.Site__r.Site_Street__c) , &quot;&quot;,Job__r.Site__r.Site_Street__c &amp;BR() )&amp;
IF( ISBLANK(Job__r.Site__r.Site_City__c) , &quot;&quot;,Job__r.Site__r.Site_City__c &amp;BR() )&amp;
IF( ISBLANK(Job__r.Site__r.Site_State__c) , &quot;&quot;,Job__r.Site__r.Site_State__c &amp;BR() )&amp;
IF( ISBLANK(Job__r.Site__r.Site_PostalCode__c) , &quot;&quot;,Job__r.Site__r.Site_PostalCode__c &amp;BR() )&amp;
IF( ISBLANK(Job__r.Site__r.Site_Country__c) , &quot;&quot;,Job__r.Site__r.Site_Country__c &amp;BR() )</formula>
    <label>Property Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Site_Address__c.field-meta.xml
<CustomField>
    <fullName>Site_Address__c</fullName>
    <formula>Job__r.Site__r.Site_Street__c &amp;&quot;, &quot;&amp; Job__r.Site__r.Site_PostalCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Address</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AccountStatementController.cls
public class AccountStatementController {

    public list<Customer_Invoice__c> invoices {get; set;}
    public Account account {get;set;}
    public Decimal TotalDue{get; set;}
    public Decimal NotDue {get; set;}
    public Decimal OneMonthDue {get; set;}
    public Decimal TwoMonthsDue {get; set;}
    public Decimal ThreeMonthsDue {get; set;}
    public Decimal OverDue {get; set;}
    public Decimal BalanceOutstanding {get;set;}
//test
    public AccountStatementController( ) 
    {
        account = [
            SELECT id, Name, BillingStreet,BillingCity,BillingPostalCode,BillingCountry, Outstanding_Balance_Incl_VAT__c,Account_Reference__c
            FROM Account
            WHERE id = :ApexPages.currentPage().getParameters().get('id')
        ];
        invoices = [
            SELECT id, Name, Date__c, Job_Number__c, Site_Address__c, Charge_Net__c,Property_Address__c ,
            Charge_VAT__c,Charge_Gross__c, Balance_Outstanding__c
            FROM Customer_Invoice__c 
            WHERE Account__c = :ApexPages.currentPage().getParameters().get('id')
            AND Balance_Outstanding__c > 0
            ORDER BY Date__c ASC
        ];
        
        Apexpages.currentPage().getHeaders().put(
            'content-disposition', 
            'inline; filename=Aspect-Statement-'
            +account.Name.replaceAll(' ','-')+'-'
            +DateTime.newInstance(Date.Today(), Time.newInstance(0,0,0,0)).format('yyyy-MM-dd')
            +'.pdf'
        );
        TotalDue = 0;
        OverDue = 0;
     	NotDue = 0;
        OneMonthDue = 0;
        TwoMonthsDue = 0;
        ThreeMonthsDue = 0;
        BalanceOutstanding = 0;

        for(customer_Invoice__c ci:invoices)
        {
            BalanceOutstanding += ci.Balance_Outstanding__c;
            if(ci.date__c >= Date.today()-30 ){
                NotDue += ci.Balance_Outstanding__c;
            }
            if(ci.date__c < Date.today()-30 ){
                TotalDue += ci.Balance_Outstanding__c;
            }
            if(ci.date__c < Date.today()-30 && ci.date__c >= Date.today()-60 ){
                OneMonthDue += ci.Balance_Outstanding__c;
            }
            if(ci.date__c < Date.today()-60 && ci.date__c >= Date.today()-90 ){
                TwoMonthsDue += ci.Balance_Outstanding__c;
            }
            if(ci.date__c < Date.today()-90 && ci.date__c >= Date.today()-120 ){
                ThreeMonthsDue += ci.Balance_Outstanding__c;
            }
            if(ci.date__c < Date.today() - 120 ){
                ThreeMonthsDue += ci.Balance_Outstanding__c;
                OverDue += ci.Balance_Outstanding__c;
            }
        }
        
    }   
}