unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Costs_and_Charges__c/Costs_and_Charges__c.object-meta.xml
<CustomObject>
    <label>Costs and Charges</label>
    <nameField>
        <displayFormat>CandC-{000000}</displayFormat>
        <label>Costs and Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Costs_and_Charges__c/fields/Admin_Fee_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee_Percentage__c</fullName>
    <description>The percentage admin fee for the job.</description>
    <label>Admin Fee Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Costs_and_Charges__c/fields/Charge_Total_Pre_Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Charge_Total_Pre_Admin_Fee__c</fullName>
    <formula>Charge_Total_pre_discount__c 
-
 Discount_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Charge Total Pre Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Costs_and_Charges__c/fields/Fixed_Price_Admin_Fee_2__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price_Admin_Fee_2__c</fullName>
    <label>Fixed Price Admin Fee 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Costs_and_Charges__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Costs and Charges</relationshipLabel>
    <relationshipName>Costs_and_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Is the Account: Cash, Credit or Key Account?</description>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <inlineHelpText>Is the Account: Cash, Credit or Key Account?</inlineHelpText>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Charge_Total_Pre_Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Charge_Total_Pre_Admin_Fee__c</fullName>
    <label>Charge Total Pre Admin Fee</label>
    <summarizedField>Costs_and_Charges__c.Charge_Total_Pre_Admin_Fee__c</summarizedField>
    <summaryFilterItems>
        <field>Costs_and_Charges__c.Include_in_estimate__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Costs_and_Charges__c.Job__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Service_Fee_Banding__mdt/Service_Fee_Banding__mdt.object-meta.xml
<CustomObject>
    <label>Service Fee Banding</label>
    <pluralLabel>Service Fee Bandings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Service_Fee_Banding__mdt/fields/End_of_Band__c.field-meta.xml
<CustomField>
    <fullName>End_of_Band__c</fullName>
    <label>End of Band</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Service_Fee_Banding__mdt/fields/Service_Fee_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Service_Fee_Percentage__c</fullName>
    <label>Service Fee Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/classes/cct_Admin_Fee_Calc.cls
public class cct_Admin_Fee_Calc {

    public cct_Admin_Fee_Calc(id cct_id) {
        List<Service_Fee_Banding__mdt> bands = [ 
            SELECT End_of_Band__c, Service_Fee_Percentage__c 
            FROM Service_Fee_Banding__mdt 
        	ORDER BY End_of_Band__c ASC 
        ];
        Costs_and_Charges__c cct = [
            SELECT id, Charge_Total_Pre_Admin_Fee__c, Fixed_Price_Admin_Fee_2__c, Admin_Fee_Percentage__c, Job__r.Account_Type__c
            FROM Costs_and_Charges__c 
            WHERE id = :cct_id
            LIMIT 1
        ];
        Decimal percentage = 0;
        Decimal start_of_band = 0;
        Boolean use_next = FALSE;
        for ( Service_Fee_Banding__mdt band:bands ) 
        {
            if ( cct.Charge_Total_Pre_Admin_Fee__c < band.End_of_Band__c && cct.Charge_Total_Pre_Admin_Fee__c > start_of_band ) 
            {
                percentage = band.Service_Fee_Percentage__c;
            }
            start_of_band = band.End_of_Band__c;
        }
        cct.Fixed_Price_Admin_Fee_2__c = 0;
        cct.Admin_Fee_Percentage__c = percentage;
        if (cct.Job__r.Account_Type__c <> 'Key Account')
        {
        	cct.Fixed_Price_Admin_Fee_2__c = (cct.Charge_Total_Pre_Admin_Fee__c * percentage/100).setscale(2);
        }
        update cct;
    } 
    
}