unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Client_Alert_1__c.field-meta.xml
<CustomField>
    <fullName>Client_Alert_1__c</fullName>
    <description>Alert on account level 1</description>
    <label>Client Alert 1</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Client_Alert_2__c.field-meta.xml
<CustomField>
    <fullName>Client_Alert_2__c</fullName>
    <description>Alert on account level 2</description>
    <label>Client Alert 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Client_Alert__c.field-meta.xml
<CustomField>
    <fullName>Client_Alert__c</fullName>
    <label>Client Alert</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/Customer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Invoices</relationshipLabel>
    <relationshipName>Customer_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Cash, Credit or Key Account</description>
    <formula>TEXT(Account__r.Account_Type__c)</formula>
    <inlineHelpText>Cash, Credit or Key Account</inlineHelpText>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Charge_Net__c.field-meta.xml
<CustomField>
    <fullName>Charge_Net__c</fullName>
    <formula>Charge_Rollup_Net__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Charge Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice_Line_Item__c/Customer_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice Line Item</label>
    <nameField>
        <displayFormat>CILI-{000000}</displayFormat>
        <label>Customer Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice_Line_Item__c/fields/Charge_Net__c.field-meta.xml
<CustomField>
    <fullName>Charge_Net__c</fullName>
    <label>Charge Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice_Line_Item__c/fields/Customer_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Customer_Invoice__c</fullName>
    <label>Customer Invoice</label>
    <referenceTo>Customer_Invoice__c</referenceTo>
    <relationshipLabel>Customer Invoice Line Items</relationshipLabel>
    <relationshipName>Customer_Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice_Line_Item__c/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <label>VAT Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>17.5</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/VAT_Rate__c/VAT_Rate__c.object-meta.xml
<CustomObject>
    <description>Stores the vat codes and rates to be used in the system</description>
    <label>VAT Rate</label>
    <nameField>
        <label>VAT Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VAT Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/VAT_Rate__c/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <description>Vat Rate Applicable e.g 2 for 20% and Z for 0%</description>
    <label>VAT Rate</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/classes/ScheduleAccountUpdateTest.cls
@isTest
public class ScheduleAccountUpdateTest {
    static testMethod void createAccount() {
        Account acc = new Account();
        acc.Name ='Test';
        acc.Account_Type__c = 'Key Account';
        acc.Client_Alert__c ='Test';
        acc.Client_Alert_1__c ='Test';
        acc.Client_Alert_2__c ='Test';
        acc.Account_Type__c = 'Cash';
        insert acc;
        
        Customer_Invoice__c customer = new Customer_Invoice__c();
        customer.Account__c = acc.id;
        insert  customer;
        Account acc1 = new Account();
        acc1.Name ='Test';
        acc1.Account_Type__c = 'Key Account';
        acc1.Client_Alert__c ='Test';
        acc1.Client_Alert_1__c ='Test';
        acc1.Client_Alert_2__c ='Test';
        acc1.Account_Type__c = 'Cash';
        insert acc1;
        
        Customer_Invoice__c customer1 = new Customer_Invoice__c();
        customer1.Account__c = acc1.id;
        insert  customer1;
        
        Customer_Invoice_Line_Item__c cusInvoice = new Customer_Invoice_Line_Item__c();
        cusInvoice.Customer_Invoice__c = customer1.id;
        cusInvoice.Charge_Net__c =100.00;
        cusInvoice.VAT_Rate__c ='5';
        insert  cusInvoice;
        
        Test.startTest();
        ScheduleAccountUpdate sh1 = new ScheduleAccountUpdate();
        
        String sch = '0 0 23 * * ?'; system.schedule('Test Territory Check', sch, sh1); 
        ScheduleBatchAccountUpdate.sendEMail('Test','Account');
        Test.stopTest();
    }
}