unpackaged/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>This defines the terms of the account including charge and payment terms.</description>
    <inlineHelpText>This defines the terms of the account including charge and payment terms.</inlineHelpText>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Key Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <formula>TRIM(RecordType.DeveloperName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Exchequer_General_Ledger_Code__c/Exchequer_General_Ledger_Code__c.object-meta.xml
<CustomObject>
    <label>Exchequer General Ledger Code</label>
    <nameField>
        <label>Exchequer GL Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchequer General Ledger Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/General_Ledger_Code__c/General_Ledger_Code__c.object-meta.xml
<CustomObject>
    <description>This will hold all of the GLC for Syncing with Aspect. Is mainly to be used for finance design</description>
    <label>General Ledger Code</label>
    <nameField>
        <label>General Ledger Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Ledger Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/General_Ledger_Code__c/fields/Client_Type__c.field-meta.xml
<CustomField>
    <fullName>Client_Type__c</fullName>
    <description>This is the Type of the Client the Code falls under</description>
    <label>Client Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Utility/Claims</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Ledger_Code__c/fields/Exchequer_GL_Code__c.field-meta.xml
<CustomField>
    <fullName>Exchequer_GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exchequer GL Code</label>
    <referenceTo>Exchequer_General_Ledger_Code__c</referenceTo>
    <relationshipLabel>General Ledger Codes</relationshipLabel>
    <relationshipName>General_Ledger_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/General_Ledger_Code__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>Reactive</fullName>
            </value>
            <value>
                <fullName>Service Contracts</fullName>
            </value>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Remedial</fullName>
                <isActive>false</isActive>
                <label>Remedial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Ledger_Code__c/fields/Ledger_Type__c.field-meta.xml
<CustomField>
    <fullName>Ledger_Type__c</fullName>
    <description>This will be the type of Ledger that the Code falls Under</description>
    <label>Ledger Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ledger_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Ledger_Code__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <description>This is the Payment type that will be used to classify which Payment Type the Code falls under</description>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/General_Ledger_Code__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <description>This is the Trade that the GLC falls under</description>
    <label>Trade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trade</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>Purchase Order for Material and Sub Contractor.</description>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Purchase_Order__c/fields/General_Ledger_Code__c.field-meta.xml
<CustomField>
    <fullName>General_Ledger_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GL code for the purchase order. Derived from the GL Code for Type of Purchase, Customer(Domestic/Commercial), Payment Type(Cash/Credit), Trade</description>
    <label>General Ledger Code</label>
    <referenceTo>General_Ledger_Code__c</referenceTo>
    <relationshipName>Purchase_Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/Supplier_Invoice__c.object-meta.xml
<CustomObject>
    <description>Supplier Invoice</description>
    <label>Supplier Invoice</label>
    <nameField>
        <displayFormat>SI-{000000}</displayFormat>
        <label>Salesforce Internal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT(Purchase_Order__r.Supplier_Account__r.Account_Type__c)</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/Exchequer_General_Ledger_Code__c.field-meta.xml
<CustomField>
    <fullName>Exchequer_General_Ledger_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exchequer General Ledger Code</label>
    <referenceTo>Exchequer_General_Ledger_Code__c</referenceTo>
    <relationshipLabel>Supplier Invoices</relationshipLabel>
    <relationshipName>Supplier_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GL code for the purchase order. Derived from the GL Code for Type of Purchase(to be confirmed with Richard/Jeya), Customer(Domestic/Commercial), Payment Type(Cash/Credit), Trade</description>
    <label>GL Code</label>
    <referenceTo>General_Ledger_Code__c</referenceTo>
    <relationshipName>Supplier_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Supplier Invoices</relationshipLabel>
    <relationshipName>Supplier_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WorkOrder/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TRIM(TEXT(Account.Account_Type__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <description>Trade for the Work Type - added this for the H&amp;S Flow + thought it better to use a formula than look it up each time.</description>
    <formula>TEXT( WorkType.Trade__c )</formula>
    <inlineHelpText>Trade for the Work Type</inlineHelpText>
    <label>Trade</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkType/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The GL Code associated with the product</description>
    <label>GL Code</label>
    <referenceTo>General_Ledger_Code__c</referenceTo>
    <relationshipLabel>Work Types</relationshipLabel>
    <relationshipName>Work_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkType/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkType/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trade</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Ledger_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Labour</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer Cost</fullName>
    </customValue>
    <customValue>
        <fullName>Estimator Cost</fullName>
    </customValue>
    <customValue>
        <fullName>Manager Cost</fullName>
    </customValue>
    <customValue>
        <fullName>Purchases</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer Pay</fullName>
    </customValue>
    <customValue>
        <fullName>Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Purchase</fullName>
        <isActive>false</isActive>
        <label>Purchase</label>
    </customValue>
    <masterLabel>Ledger Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Payment_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <customValue>
        <fullName>Card</fullName>
    </customValue>
    <customValue>
        <fullName>Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>BACS</fullName>
    </customValue>
    <customValue>
        <fullName>Credit</fullName>
    </customValue>
    <masterLabel>Payment Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Trade.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Access</fullName>
    </customValue>
    <customValue>
        <fullName>Air Con, Ventilation &amp; Refrigeration</fullName>
    </customValue>
    <customValue>
        <fullName>Brickwork &amp; Paving</fullName>
    </customValue>
    <customValue>
        <fullName>Carpentry</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Decorating</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Soil Water)</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Tanker)</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Wastewater)</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Fencing</fullName>
    </customValue>
    <customValue>
        <fullName>Flooring</fullName>
    </customValue>
    <customValue>
        <fullName>Gardening</fullName>
    </customValue>
    <customValue>
        <fullName>Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>Handyman</fullName>
    </customValue>
    <customValue>
        <fullName>Heating &amp; Hot Water (Commercial)</fullName>
    </customValue>
    <customValue>
        <fullName>Heating &amp; Hot Water (Domestic)</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Central Heating</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Drainage</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Plumbing</fullName>
    </customValue>
    <customValue>
        <fullName>Locksmithing</fullName>
    </customValue>
    <customValue>
        <fullName>OSA</fullName>
    </customValue>
    <customValue>
        <fullName>Partition Walls &amp; Ceilings</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Control</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Proofing</fullName>
    </customValue>
    <customValue>
        <fullName>Plastering</fullName>
    </customValue>
    <customValue>
        <fullName>Plumbing &amp; Cold Water</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management Decoration</fullName>
    </customValue>
    <description>This holds all of the types of trade in the company</description>
    <masterLabel>Trade</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SupplierInvoice_GL_Controller.cls
public class SupplierInvoice_GL_Controller {

    
    public static void stampGL(id si_id)
    {

        try {

            Supplier_Invoice__c si = [
                SELECT id,  Purchase_Order__r.Work_Order__c 
                FROM Supplier_Invoice__c
                WHERE id = :si_id
                LIMIT 1
            ];
            
            WorkOrder wo = [
                SELECT id, WorkType.Trade__c, Account.Account_Type__c, Account.Record_Type_Name__c, Record_Type_Name__c
                FROM WorkOrder
                WHERE id = :si.Purchase_Order__r.Work_Order__c
            ];

            General_Ledger_Code__c glc = [
                SELECT id, Exchequer_GL_Code__c
                FROM General_Ledger_Code__c
                WHERE Ledger_Type__c = 'Purchases'
                AND Job_Type__c = :wo.Record_Type_Name__c
                AND Payment_Type__c = :wo.Account.Account_Type__c
                AND Trade__c = :wo.WorkType.Trade__c
                AND Client_Type__c = :wo.Account.Record_Type_Name__c
            ];
            
            si.GL_Code__c = glc.id;
            si.Exchequer_General_Ledger_Code__c = glc.Exchequer_GL_Code__c;
            update si;
        } catch (Exception e) {
            
        }

    }
    
}