unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Resource Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Engineer_Role__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Role__c</fullName>
    <description>The main role the resource takes</description>
    <label>Engineer Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Rate_of_Pay_Tier__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay_Tier__c</fullName>
    <description>Rate at which the Engineer receives Pay</description>
    <inlineHelpText>Rate at which the Engineer receives Pay</inlineHelpText>
    <label>Rate of Pay Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Tier_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Engineer_Tier_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 4</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 6</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 8</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 10</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1</fullName>
        <isActive>false</isActive>
        <label>Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Tier 3</fullName>
        <isActive>false</isActive>
        <label>Tier 3</label>
    </customValue>
    <masterLabel>Engineer Tier Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Engineer_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service_Resource</fullName>
        <label>Service Resource</label>
    </customValue>
    <customValue>
        <fullName>Franchisee</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer</fullName>
        <isActive>false</isActive>
        <label>Engineer</label>
    </customValue>
    <customValue>
        <fullName>Manager</fullName>
        <isActive>false</isActive>
        <label>Manager</label>
    </customValue>
    <customValue>
        <fullName>Estimator</fullName>
        <isActive>false</isActive>
        <label>Estimator</label>
    </customValue>
    <description>The main role the resource takes</description>
    <masterLabel>Engineer Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SendEmailHandlerTest.cls
@isTest
public class SendEmailHandlerTest {
    static testMethod void SendEmailMethod() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduse21344555r@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standfefdsfdarduser@testorg.com');
        insert u;
        System.runAs(u) {
            
            Account acc = new Account(name='test acc');
            insert acc;
            
            String RecordTypeIdContact = Schema.SObjectType.ResourceAbsence.getRecordTypeInfosByName().get('Non Availability').getRecordTypeId();
            ServiceResource SR = new ServiceResource();
            SR.Email__c = ' Test@gmail.com';
            SR.Engineer_Role__c ='Service_Resource';
            SR.ResourceType = 'T';
            SR.Rate_of_Pay_Tier__c = 'Tier 2';
            SR.RelatedRecordId =u.id;
            SR.Name ='Test';
            insert SR;    
            
            ContentVersion cv = new ContentVersion();
            cv.ContentLocation = 'S';
            Blob b=Blob.valueOf('Unit Test Attachment Body');
            cv.versiondata=EncodingUtil.base64Decode('Unit Test Attachment Body');
            cv.Title = 'fileName';
            cv.PathOnClient = 'filename';
            insert cv;
            
            ContentNote cn = new ContentNote();
            cn.Title = 'This is Title of the Note!';
            cn.Content = Blob.valueOf('test');
            insert cn;
            
            ContentDocumentLink cl = new ContentDocumentLink();
            cl.ContentDocumentId = cn.Id;
            cl.LinkedEntityId = acc.Id; 
       	    cl.ShareType = 'V';
       	    cl.Visibility = 'AllUsers';
            insert cl;
            
            test.StartTest();
            
            String s1 = SendEmailHandler.processEmail('','','','','');
            SendEmailHandler.wrapEmail s2 = SendEmailHandler.getemailidDetails();
            List<String> s3 = SendEmailHandler.getSucotmSetting();
          //  String s4 = SendEmailHandler.saveFileforRecord(cv.Id,'','','','');
            //String s5 = SendEmailHandler.saveFile(cv.Id,'','','','');
              String s = SendEmailHandler.saveFileforRecord(null,'Test','fsdsgfdgdfbgfngfn','','');
            String s6 = SendEmailHandler.saveFile(null,'Test','fsdsgfdgdfbgfngfn','','');
            test.StopTest();
        }
    }
}