unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Referral_notes__c.field-meta.xml
<CustomField>
    <fullName>Referral_notes__c</fullName>
    <label>Referral notes</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Site related to the Contact</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Promo_Code__c.field-meta.xml
<CustomField>
    <fullName>Promo_Code__c</fullName>
    <label>Promo Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email to contact the related Site</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/classes/BuyapowaReferralTrackingAPI_Test.cls
/*
* Class  : BuyapowaReferralReconciliationAPI_Test
* Use    : This test class is written to get coverage for class BuyapowaReferralReconciliationAPI.
* Auther : Bharat Vyas, 5/10/2022
*/

@isTest
private class BuyapowaReferralTrackingAPI_Test {

     @isTest static void testCallout() {
        
        Account acc = AspectTestDataFactory.createAccount();
        Contact cont = AspectTestDataFactory.createContact(acc);
        Site__c site = AspectTestDataFactory.createSite(acc, Cont);
        WorkType wType = AspectTestDataFactory.createWorkType();
        Job__c job = AspectTestDataFactory.createJob(acc, wType, site);		
        
        acc.Referral_notes__c = 'testinghere,test@gmail.com';
        update acc;
         
        List<BuyapowaReferralTrackingAPI.orderDetails> orderDetailList = new List<BuyapowaReferralTrackingAPI.orderDetails>();
        BuyapowaReferralTrackingAPI.orderDetails ordrDetail = new BuyapowaReferralTrackingAPI.orderDetails();
        ordrDetail.referrerEmail = acc.Referral_notes__c;
        ordrDetail.voucherCode = job.Promo_Code__c;
        ordrDetail.firstName = acc.First_Name__c;
        ordrDetail.lastName = acc.Last_Name__c;
        ordrDetail.email = acc.Email__c;
        ordrDetail.jobId = job.Id;
        ordrDetail.jobName = job.Name;
        ordrDetail.jobCreatedTime = System.today();
        orderDetailList.add(ordrDetail);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BuyapowaReferralTrackingAPIMockHttp()); 
        BuyapowaReferralTrackingAPI.getOrderDetails(orderDetailList);
        Test.stopTest();
    }
}