unpackaged/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Invoicing_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Email_Address__c</fullName>
    <description>Purpose is to send bulk invoices to a Customer. If this field is populated then the system should send the email to the email address on the field else it should use the Customer&#39;s email address</description>
    <label>Invoicing Email Address</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Site related to the Contact</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/Customer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Invoices</relationshipLabel>
    <relationshipName>Customer_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Email_Address__c</fullName>
    <description>Email address pulled from account - this field is stamped on the creation of the invoice, so will not be updated if there is a later change to the email address on the account</description>
    <inlineHelpText>Email address pulled from account - this field is stamped on the creation of the invoice, so will not be updated if there is a later change to the email address on the account</inlineHelpText>
    <label>Account Email Address</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Authorisation__c.field-meta.xml
<CustomField>
    <fullName>Authorisation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Authorisation</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>asp04__Authorisation__c.Customer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>asp04__Authorisation__c</referenceTo>
    <relationshipLabel>Customer Invoices</relationshipLabel>
    <relationshipName>Customer_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Customer_Invoices_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Number of days credit given on Customer Invoices</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Authorisation__c.field-meta.xml
<CustomField>
    <fullName>Authorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Valid Authorisation record (at time of booking)</description>
    <inlineHelpText>Valid Authorisation record (at time of booking)</inlineHelpText>
    <label>Authorisation</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only add a card if it is linked to this jobs account.</errorMessage>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>asp04__Authorisation__c.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>asp04__Authorisation__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Contact_Email_who_Raised_Job__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_who_Raised_Job__c</fullName>
    <description>Email Address of the Contact who raised the Job</description>
    <inlineHelpText>Email Address of the Contact who raised the Job</inlineHelpText>
    <label>Contact Email who Raised Job</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Customer_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Customer_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Invoice</label>
    <referenceTo>Customer_Invoice__c</referenceTo>
    <relationshipLabel>Jobs (Customer Invoice)</relationshipLabel>
    <relationshipName>Consolidated_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>For Client Approval</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved by Client</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email to contact the related Site</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Primary_Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Site_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Primary contact at this Site</inlineHelpText>
    <label>Primary Site Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Primary_Sites_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Contact_Email_who_Raised_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_who_Raised_Work_Order__c</fullName>
    <description>Email Address of the Contact who raised the Work Order</description>
    <inlineHelpText>Email Address of the Contact who raised the Work Order</inlineHelpText>
    <label>Contact Email who Raised Work Order</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated only through the flow</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ready to Send</fullName>
    </customValue>
    <customValue>
        <fullName>Part Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Outstanding</fullName>
        <default>true</default>
        <label>Outstanding</label>
    </customValue>
    <customValue>
        <fullName>In Post</fullName>
        <isActive>false</isActive>
        <label>In Post</label>
    </customValue>
    <customValue>
        <fullName>Reconciled</fullName>
        <isActive>false</isActive>
        <label>Reconciled</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
        <isActive>false</isActive>
        <label>Received</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <isActive>false</isActive>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>With Engineer</fullName>
        <isActive>false</isActive>
        <label>With Engineer</label>
    </customValue>
    <description>Number of days credit given on Customer Invoices</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Emailaddress.cls
public class Emailaddress{

    @InvocableMethod
    public static void EmailAddresses(list<String> jobslist){
        
        //Data crunch to seperate emailId from the rest of JOBIDs
        string data = jobslist[0];
        String emailString = '';
        Set<Id> accIdSet = new Set<Id>();
        Set<Id> authIdSet = new Set<Id>();
        Set<Id> siteIdSet = new Set<Id>();
        Set<Id> contactIdSet = new Set<Id>();
        
        List<String> splitData = data.split(';');
        
        
        List<Id> trimmedJobIdList = new List<Id>(); 
         //Identify the email in the list
         for(String recvdListrec : splitData){
            if(recvdListrec.contains('@')){
                emailString = recvdListrec;
            }else{
                trimmedJobIdList.add(id.valueOf(recvdListrec.trim()));
            } 
         }
         
         ////Update Jobs
            list<Job__c> joblist = [select id,Site__c,Site__r.Primary_Site_Contact__c,Contact_Email_who_Raised_Job__c,Account__c,Authorisation__c from Job__c where Id in :  trimmedJobIdList];

            system.debug('Job list ' + joblist.size());

            for(Job__c jj : joblist){
                jj.Contact_Email_who_Raised_Job__c = emailString;
                accIdSet.add(jj.Account__c);
                authIdSet.add(jj.Authorisation__c); 
                siteIdSet.add(jj.Site__c);
                if(jj.Site__r.Primary_Site_Contact__c != NULL){
                    contactIdSet.add(jj.Site__r.Primary_Site_Contact__c);
                }
                
            }
            update joblist; 
          
         //Account 
         List<Account> accList = [select id,email__c,Invoicing_Email_Address__c  from account where id in: accIdSet];
         for(Account acc : accList){
                acc.Invoicing_Email_Address__c = emailString;
                acc.Email__c = emailString;
          }
            update accList;
         
         //Contact
         if(contactIdSet.size() > 0){
             List<Contact> contList = [select id,Email from Contact where Id  in: contactIdSet];
             for(Contact Con: contList ){
                    con.Email = emailString;
              }
              update contList ;
         }
         
          
         //Site 
         List<Site__c> siteList = [select id,Email__c from Site__c where id in: siteIdSet];
         for(Site__c siterec: siteList ){
                siterec.Email__c = emailString;
          }
          update siteList;
         
         //WO , Pending,
         list<WorkOrder> wolist = [select id,Contact_Email_who_Raised_Work_Order__c from WorkOrder where Job__c in :  trimmedJobIdList and Status = 'Pending'];
         for(WorkOrder ww : wolist){
            ww.Contact_Email_who_Raised_Work_Order__c = emailString;
         }
         update wolist;
        
         //Authorization ,Awaiting submission, Pending or INforce
         list<asp04__Authorisation__c> authlist = [select id,Customer_Email__c from asp04__Authorisation__c where id in :  authIdSet and 
         (asp04__Status__c = 'Awaiting submission' OR asp04__Status__c = 'Pending' OR asp04__Status__c = 'In Force')];
         for(asp04__Authorisation__c auth : authlist){
               auth.Customer_Email__c = emailString;
               auth.asp04__Email__c = emailString;
         }
         update authlist;
            
         //SA ,!= Visit complete
         List<ServiceAppointment> SAList = [select id,Contact_Email__c from ServiceAppointment where Work_Order__c in :  wolist and Status != 'Visit Complete'];
         for(ServiceAppointment sa : SAList){
             sa.Contact_Email__c = emailString;
         }
         update SAList;
        
          //CI , Outstanding, Account__c
          list<Customer_Invoice__c> CIlist = [select id,Account_Email_Address__c from Customer_Invoice__c where Job__c in :  trimmedJobIdList and Status__c != 'Paid'];
          for(Customer_Invoice__c ci : CIlist){
               ci.Account_Email_Address__c = emailString;
          }
          update CIlist;
            
         //Not including payments for email updates   
         /*Payment , != Collected from customer
         list<asp04__Payment__c> paymentlist = [select id,Account_Email__c from asp04__Payment__c where Customer__c in :  accIdSet];
         for(asp04__Payment__c pay : paymentlist){
              pay.Account_Email__c = 'upparapalli3.saikrishna@gmail.com';
         }
         update paymentlist;*/
                        
    }
}