unpackaged/main/default/objects/Account/fields/Rate_Card__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>Rate_Card_Account__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Account__c/Rate_Card_Account__c.object-meta.xml
<CustomObject>
    <label>Account Rate Card</label>
    <nameField>
        <displayFormat>ARC-{0000}</displayFormat>
        <label>Account Rate Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Rate_Card_Trade__c/Rate_Card_Trade__c.object-meta.xml
<CustomObject>
    <label>Trade Rate Card</label>
    <nameField>
        <displayFormat>TRC-{0000}</displayFormat>
        <label>Trade Rate Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Rate_Card__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card__c</fullName>
    <label>Rate Card</label>
    <referenceTo>Rate_Card_Account__c</referenceTo>
    <relationshipLabel>Trade Rate Cards</relationshipLabel>
    <relationshipName>Trade_Rate_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trade</label>
    <referenceTo>Trade__c</referenceTo>
    <relationshipLabel>Trade Rate Cards</relationshipLabel>
    <relationshipName>Trade_Rate_Cards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Trade_Name__c.field-meta.xml
<CustomField>
    <fullName>Trade_Name__c</fullName>
    <formula>Trade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trade Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WorkOrder/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <description>Trade for the Work Type - added this for the H&amp;S Flow + thought it better to use a formula than look it up each time.</description>
    <formula>TEXT( WorkType.Trade__c )</formula>
    <inlineHelpText>Trade for the Work Type</inlineHelpText>
    <label>Trade</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Trade_Rate__c.field-meta.xml
<CustomField>
    <fullName>Trade_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trade Rate</label>
    <referenceTo>Rate_Card_Trade__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/WorkOrderTriggerHandler.cls
/*
Author: Pradeep Kumar on 25/07/2022
Purpose: This is trigger handler class created to handle all the logic related to WorkOrder Object.

Modification Log: 

*/
public class WorkOrderTriggerHandler {
    
    public void assignTradeRateCard(List<WorkOrder> woRecList){
        
        Set<string> tradeNameSet = new Set<string>();
        Set<Id> accIdSet = new Set<Id>();
        Set<Id> accRateIdSet = new Set<Id>();
        List<Rate_Card_Trade__c> trcRecList = new List<Rate_Card_Trade__c>();
        List<Account> accRecList = new List<Account>();
        Map<String, List<WorkOrder>> tradeWOMap = new Map<String, List<WorkOrder>>();
        
        for(WorkOrder woRec: woRecList){
            if(woRec.Trade__c != NULL){
                tradeNameSet.add(woRec.Trade__c);
                accIdSet.add(woRec.AccountId);
            }
            if(tradeWOMap.containsKey(woRec.Trade__c)){
                List<WorkOrder> woList = new List<WorkOrder>();
                woList = tradeWOMap.get(woRec.Trade__c); woList.add(woRec);
                tradeWOMap.put(woRec.Trade__c, woList);
            }else{
                tradeWOMap.put(woRec.Trade__c, new List<WorkOrder>{woRec});
            }
        }
        
        List<Rate_Card_Account__c> acrRec = [SELECT Id,Standard__c FROM Rate_Card_Account__c 
                                             WHERE Standard__c = TRUE LIMIT 1];
        
        if(accIdSet != NULL){
            accRecList = [SELECT Id, Rate_Card__c FROM Account WHERE Id IN: accIdSet];
        }
        
        if(accRecList.size() > 0){
            for(Account accRec: accRecList){
                accRateIdSet.add(accRec.Rate_Card__c);
            }
        }
        
        if(tradeNameSet.size() > 0 && accRateIdSet.size() > 0){
            trcRecList = [SELECT Id,Trade_Name__c,Rate_Card__c FROM Rate_Card_Trade__c 
                          WHERE Trade_Name__c IN:tradeNameSet AND Rate_Card__c IN: accRateIdSet];
        }
        else if(tradeNameSet.size() > 0 && accRateIdSet == NULL && acrRec != NULL){
             trcRecList = [SELECT Id,Trade_Name__c,Rate_Card__c FROM Rate_Card_Trade__c WHERE Trade_Name__c IN:tradeNameSet 
                           AND Rate_Card__c =: acrRec[0].Id];
        }
        
        if(trcRecList.size() > 0){
            for(Rate_Card_Trade__c trcRec: trcRecList){
                if(tradeWOMap.containsKey(trcRec.Trade_Name__c)){
                    for(WorkOrder woRec: tradeWOMap.get(trcRec.Trade_Name__c)){
                        if(woRec.Trade_Rate__c == NULL){
                            woRec.Trade_Rate__c = trcRec.Id;
                        }
                    } 
                }
            } 
        }
        TriggerStopper.stopWOTrigger = TRUE;
    }
}