unpackaged/main/default/objects/Account/fields/Rate_Card__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>Rate_Card_Account__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Domestic.recordType-meta.xml
<RecordType>
    <fullName>Domestic</fullName>
    <active>true</active>
    <label>Domestic</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Site related to the Contact</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Costs_and_Charges__c/Costs_and_Charges__c.object-meta.xml
<CustomObject>
    <label>Costs and Charges</label>
    <nameField>
        <displayFormat>CandC-{000000}</displayFormat>
        <label>Costs and Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Costs_and_Charges__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Costs and Charges</relationshipLabel>
    <relationshipName>Costs_and_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/Customer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Invoices</relationshipLabel>
    <relationshipName>Customer_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Customer_Invoices_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/recordTypes/Deposit.recordType-meta.xml
<RecordType>
    <fullName>Deposit</fullName>
    <active>true</active>
    <label>Deposit</label>
</RecordType>

unpackaged/main/default/objects/Customer_Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Combined_Scope_of_Works_for_All_WOs__c.field-meta.xml
<CustomField>
    <fullName>Combined_Scope_of_Works_for_All_WOs__c</fullName>
    <label>Combined Scope of Works for All WOs</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ProductRequired/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Product Required - max 200 characters</description>
    <inlineHelpText>Description of the Product Required - max 200 characters</inlineHelpText>
    <label>Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/Rate_Card_Trade__c.object-meta.xml
<CustomObject>
    <label>Trade Rate Card</label>
    <nameField>
        <displayFormat>TRC-{0000}</displayFormat>
        <label>Trade Rate Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Rate Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Charge_R1__c.field-meta.xml
<CustomField>
    <fullName>Charge_R1__c</fullName>
    <label>Charge R1</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Charge_R2__c.field-meta.xml
<CustomField>
    <fullName>Charge_R2__c</fullName>
    <label>Charge R2</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Charge_R3__c.field-meta.xml
<CustomField>
    <fullName>Charge_R3__c</fullName>
    <label>Charge R3</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Default_For_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Default_For_Estimate__c</fullName>
    <label>Default For Estimate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engineer_Tier_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Pay_Tier_10__c.field-meta.xml
<CustomField>
    <fullName>Pay_Tier_10__c</fullName>
    <label>Pay Tier 10</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Pay_Tier_1__c.field-meta.xml
<CustomField>
    <fullName>Pay_Tier_1__c</fullName>
    <label>Pay Tier 1</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Pay_Tier_2__c.field-meta.xml
<CustomField>
    <fullName>Pay_Tier_2__c</fullName>
    <label>Pay Tier 2</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Pay_Tier_3__c.field-meta.xml
<CustomField>
    <fullName>Pay_Tier_3__c</fullName>
    <label>Pay Tier 3</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Pay_Tier_4__c.field-meta.xml
<CustomField>
    <fullName>Pay_Tier_4__c</fullName>
    <label>Pay Tier 4</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Pay_Tier_5__c.field-meta.xml
<CustomField>
    <fullName>Pay_Tier_5__c</fullName>
    <label>Pay Tier 5</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Pay_Tier_6__c.field-meta.xml
<CustomField>
    <fullName>Pay_Tier_6__c</fullName>
    <label>Pay Tier 6</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Pay_Tier_7__c.field-meta.xml
<CustomField>
    <fullName>Pay_Tier_7__c</fullName>
    <label>Pay Tier 7</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Pay_Tier_8__c.field-meta.xml
<CustomField>
    <fullName>Pay_Tier_8__c</fullName>
    <label>Pay Tier 8</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Pay_Tier_9__c.field-meta.xml
<CustomField>
    <fullName>Pay_Tier_9__c</fullName>
    <label>Pay Tier 9</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Rate_Card__c.field-meta.xml
<CustomField>
    <fullName>Rate_Card__c</fullName>
    <label>Rate Card</label>
    <referenceTo>Rate_Card_Account__c</referenceTo>
    <relationshipLabel>Trade Rate Cards</relationshipLabel>
    <relationshipName>Trade_Rate_Cards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Rate_Card_Trade__c/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Trade</label>
    <referenceTo>Trade__c</referenceTo>
    <relationshipLabel>Trade Rate Cards</relationshipLabel>
    <relationshipName>Trade_Rate_Cards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Primary_Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Site_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Primary contact at this Site</inlineHelpText>
    <label>Primary Site Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Primary_Sites_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_Country__c.field-meta.xml
<CustomField>
    <fullName>Site_Country__c</fullName>
    <defaultValue>&#39;United Kingdom&#39;</defaultValue>
    <description>Site country</description>
    <label>Site Country</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Site_PostalCode__c</fullName>
    <description>Site postal address</description>
    <label>Site PostalCode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_Street__c.field-meta.xml
<CustomField>
    <fullName>Site_Street__c</fullName>
    <description>Site street address</description>
    <label>Site Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/recordTypes/Domestic.recordType-meta.xml
<RecordType>
    <fullName>Domestic</fullName>
    <active>true</active>
    <label>Domestic</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/fields/Costs_and_Charges__c.field-meta.xml
<CustomField>
    <fullName>Costs_and_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Costs and Charges</label>
    <referenceTo>Costs_and_Charges__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated only through the flow</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <description>Trade for the Work Type - added this for the H&amp;S Flow + thought it better to use a formula than look it up each time.</description>
    <formula>TEXT( WorkType.Trade__c )</formula>
    <inlineHelpText>Trade for the Work Type</inlineHelpText>
    <label>Trade</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkType/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trade</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Engineer_Tier_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tier 2</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 4</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 6</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 8</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 10</fullName>
    </customValue>
    <customValue>
        <fullName>Tier 1</fullName>
        <isActive>false</isActive>
        <label>Tier 1</label>
    </customValue>
    <customValue>
        <fullName>Tier 3</fullName>
        <isActive>false</isActive>
        <label>Tier 3</label>
    </customValue>
    <masterLabel>Engineer Tier Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Trade.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Access</fullName>
    </customValue>
    <customValue>
        <fullName>Air Con, Ventilation &amp; Refrigeration</fullName>
    </customValue>
    <customValue>
        <fullName>Brickwork &amp; Paving</fullName>
    </customValue>
    <customValue>
        <fullName>Carpentry</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Decorating</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Soil Water)</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Tanker)</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Wastewater)</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Fencing</fullName>
    </customValue>
    <customValue>
        <fullName>Flooring</fullName>
    </customValue>
    <customValue>
        <fullName>Gardening</fullName>
    </customValue>
    <customValue>
        <fullName>Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>Handyman</fullName>
    </customValue>
    <customValue>
        <fullName>Heating &amp; Hot Water (Commercial)</fullName>
    </customValue>
    <customValue>
        <fullName>Heating &amp; Hot Water (Domestic)</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Central Heating</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Drainage</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Plumbing</fullName>
    </customValue>
    <customValue>
        <fullName>Locksmithing</fullName>
    </customValue>
    <customValue>
        <fullName>OSA</fullName>
    </customValue>
    <customValue>
        <fullName>Partition Walls &amp; Ceilings</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Control</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Proofing</fullName>
    </customValue>
    <customValue>
        <fullName>Plastering</fullName>
    </customValue>
    <customValue>
        <fullName>Plumbing &amp; Cold Water</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management Decoration</fullName>
    </customValue>
    <customValue>
        <fullName>Roofing</fullName>
    </customValue>
    <description>This holds all of the types of trade in the company</description>
    <masterLabel>Trade</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Aspect_JobDataControllerTest.cls
/*

Modification Log:
1) 7/7/2022 - Mofified by Pradeep for Rate Cards and Rate restructure

*/

@istest
public class Aspect_JobDataControllerTest {
    
    static testMethod void jobMethod1(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='PHASE 2 Ops - Starter']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standardusfghgfhgfhger@testorg.com');
        insert u;
        
        Rate_Card_Account__c rca = new Rate_Card_Account__c();
        rca.Description__c = 'test';
        rca.Standard__c = TRUE;
        insert rca;
        
        Account acc = new Account();
        acc.Name = 'Test';
        acc.BillingStreet ='Test';
        acc.BillingPostalCode  ='123445';
        acc.Rate_Card__c = rca.Id;
        insert acc; 
        
        contact con  = new Contact();
        con.LastName = 'Aspect';
        insert con;
        
        Id RecordTypeIdContact = Schema.SObjectType.Site__c.getRecordTypeInfosByName().get('Domestic').getRecordTypeId();
        Site__c site = new Site__c();
        site.Account__c  = acc.id;
        site.RecordTypeId = RecordTypeIdContact;
        site.Name = 'test';
        site.Primary_Site_Contact__c =con.id;
        site.Site_Street__c ='Test';
        site.Site_PostalCode__c ='12345';
        Site.Site_Country__c ='Uk';
        insert site;
        
        Job__c job = new Job__c();
        Job.Account__c = acc.id;
        Job.Site__c =site.id;
        JOb.Combined_Scope_of_Works_for_All_WOs__c = 'Test';
        insert Job;
        
        Aspect_JobDataController.workORderLabourWrapper wraps = new Aspect_JobDataController.workORderLabourWrapper();
        Costs_and_Charges__c cost = new Costs_and_Charges__c();
        cost.JOb__c = Job.id;
        insert cost;
        
        Trade__c trade = new Trade__c();
        trade.Name = 'Roofing';
        insert trade;
        
        Rate_Card_Trade__c rct = new Rate_Card_Trade__c();
        rct.Rate_Card__c = rca.Id;
        rct.Trade__c = trade.Id;
        rct.Default_For_Estimate__c = 'Tier 8';
        rct.Charge_R1__c = 10;rct.Charge_R2__c = 20;rct.Charge_R3__c= 30;
        rct.Pay_Tier_1__c = 4;rct.Pay_Tier_2__c = 4;
        rct.Pay_Tier_3__c= 5;rct.Pay_Tier_4__c = 6;
        rct.Pay_Tier_5__c = 3;rct.Pay_Tier_6__c = 7;
        rct.Pay_Tier_7__c = 21;rct.Pay_Tier_8__c = 9;
        rct.Pay_Tier_9__c = 25;rct.Pay_Tier_10__c = 12;
        insert rct;
        
        Costs_and_Charges__c costs = new Costs_and_Charges__c();
        costs.Job__c = job.id;
        insert costs;
        
        Aspect_JobDataController.productRequiredWrapper prod = new Aspect_JobDataController.productRequiredWrapper();
        prod.type='Hire';
        prod.overrides=true;
        prod.cost =10;
        prod.costorg =11;
        prod.quantity =10;
        prod.quantityorg =11;
        prod.markup =10;
        prod.markuporg =11;
        prod.ProductREquiredId ='|567|';
        List<Aspect_JobDataController.productRequiredWrapper> prodrec = new List<Aspect_JobDataController.productRequiredWrapper>();
        prodrec.add(prod);
        WorkType wt=new WorkType();
        wt.trade__c='Roofing';
        wt.name ='test';
        wt.EstimatedDuration=10.00;
        insert wt;
        
        WorkOrder WO  = New WOrkOrder();
        WO.JOb__c =job.id;
        WO.Costs_and_Charges__c =costs.id;
        WO.WorkTypeId =wt.id;
        WO.Trade_Rate__c = rct.Id;
        insert WO;

        Id pricebookId = Test.getStandardPricebookId();
        
        //Create your product
        Product2 prodyuct = new Product2(
            Name = 'Hire',
            ProductCode = 'Pro-X',
            isActive = true
        );
        insert prodyuct;
        
        //Create your pricebook entry
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prodyuct.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        ProductRequired prodreq = new ProductRequired();
        prodreq.ParentRecordId =WO.id;
        prodreq.Product2Id =prodyuct.id;
        prodreq.QuantityRequired = 1;
        insert prodreq;
        
        Aspect_JobDataController.CCOtherWrapper ccothers = new   Aspect_JobDataController.CCOtherWrapper();
        Test.startTest();
        Map<String,String> trades =  Aspect_JobDataController.getTrades();
        Aspect_JobDataController.workORderLabourWrapper wrap = Aspect_JobDataController.getWorkOrderOnChage(trade.id,wraps,Job.id,true,true);
        Aspect_JobDataController.workORderLabourWrapper wrap1 = Aspect_JobDataController.getWorkOrderOnChage(trade.id,wraps,Job.id,false,false);
        Aspect_JobDataController.workORderLabourWrapper wrap2 = Aspect_JobDataController.getWorkOrderOnChage(trade.id,wraps,Job.id,false,true);
        Aspect_JobDataController.workORderLabourWrapper wrap3 = Aspect_JobDataController.getWorkOrderOnChage(trade.id,wraps,Job.id,true,false);
        Aspect_JobDataController.workTrageGroupWrapper tradge =Aspect_JobDataController.tradeWOrktypeGroup(WO.id);
        Aspect_JobDataController.updateccforworkorder(WO.id);
        Aspect_JobDataController.CCOtherWrapper ccother =Aspect_JobDataController.getCCforWorkOrder(WO.id);
        List<Aspect_JobDataController.productRequiredWrapper>Prods =  Aspect_JobDataController.updatePrdowrap(prodrec);
        JOb__c jobs  =Aspect_JobDataController.getjobbrecord(Job.id);
        Aspect_JobDataController.workORderLabourWrapper wrapsLabour =   Aspect_JobDataController.getWorkorderforLabourctrl(WO.id);
        Aspect_JobDataController.workOrderWrapper  wkorder = Aspect_JobDataController.getWorkOrderDetailsCtrl(WO.id);
        List<Aspect_JobDataController.productRequiredWrapper>Prods1 =  Aspect_JobDataController.markupChangeMethod(prodrec);
        List<Aspect_JobDataController.productRequiredWrapper>Prods2 =  Aspect_JobDataController.qulaityChangeMethd(prodrec);
        List<Aspect_JobDataController.productRequiredWrapper>Prods3 =  Aspect_JobDataController.checkboxchange(prodrec,'3',true);
        List<Aspect_JobDataController.productRequiredWrapper>Prods4 =  Aspect_JobDataController.checkboxchange(prodrec,'3',false);
        Aspect_JobDataController.CCOtherWrapper ccotherss = Aspect_JobDataController.handloeotherfunction(ccothers);
        List<Aspect_JobDataController.productRequiredWrapper> prodwrapppers = Aspect_JobDataController.getProductRequiredRec(WO.id);
        Aspect_JobDataController.updateSuccess s = Aspect_JobDataController.updateJob(prodrec,wraps,'',ccothers,Job.id,false,trade.id);
        Aspect_JobDataController.updateSuccess s1 = Aspect_JobDataController.updateJob(prodrec,wraps,'',ccothers,Job.id,true,trade.id);
        Map<String,String> mpasRTrade =Aspect_JobDataController.getgroup('');
        Map<String,String> mpasRTrades =Aspect_JobDataController.getWorkType('');
        Aspect_JobDataController.workORderLabourWrapper wrap6 =    Aspect_JobDataController.getworktypechange(wt.id,wraps,WO.id,Job.id);
        String getDescription = Aspect_JobDataController.getCombinedValuefromJob(Job.id);
        Boolean wrap7 =    Aspect_JobDataController.checkOnSize(prodrec);
        Aspect_JobDataController.hr1 =10;
        Aspect_JobDataController.hr2 =10;
        Aspect_JobDataController.hr3 =10;
        Aspect_JobDataController.hr1amount =10;
        Aspect_JobDataController.hr2amount =10;
        Aspect_JobDataController.hr3amount =10;
        Boolean s5=  Aspect_JobDataController.checkUserProfile();
        List<String> s6 =Aspect_JobDataController.getProductRequiredProduct();
        //decimal s7 = Aspect_JobDataController.getfixedPriceAdmin(Job.id);
        List<Aspect_JobDataController.productRequiredWrapper> prodWraps = new  List<Aspect_JobDataController.productRequiredWrapper>();
        Aspect_JobDataController.productRequiredWrapper prodWrap = new Aspect_JobDataController.productRequiredWrapper();
        prodWrap.type='Hire';
        prodWraps.add(prodWrap);
        
        integer intValue = Aspect_JobDataController.getrandomnumber();
        //Aspect_JobDataController.deleteproductrequired(prodreq.id);
        //Boolean isCheckUser=Aspect_JobDataController.getUserInfo(u.id);
        //   String sJob1 = Aspect_JobDataController.getCombinedValuefromJob(job.id);
        Test.stopTest();
    }
    
    static testMethod void jobMethod(){
        
        Profile p = [SELECT Id FROM Profile WHERE Name='PHASE 2 Ops - Starter']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standardusfghgfhgfhger@testorg.com');
        insert u;
        
        Rate_Card_Account__c rca = new Rate_Card_Account__c();
        rca.Description__c = 'test';
        rca.Standard__c = TRUE;
        insert rca;
        
        ID networkId = Network.getNetworkId();
        
        Account acc = new Account();
        acc.Name = 'Invoice Test';
        acc.First_Name__c = 'Invoice';
        acc.Last_Name__c = 'Test';
        acc.Email__c = 'dasfrog.web@gmail.com';
        acc.Invoicing_Email_Address__c = 'dasfrog.web@gmail.com';
        acc.Account_Type__c = 'Cash';
        acc.Account_Status__c = 'Open';
        acc.BillingStreet = '8 Allington way';
        acc.BillingCity = 'Swanley';
        acc.BillingCountry = 'United Kingdom';
        acc.BillingPostalCode = 'BR8 8FG';
        acc.Access_Details__c = '2333';
        acc.DRC_Applies__c = TRUE;
        acc.Rate_Card__c = rca.Id;
        insert acc; 
        
        contact con  = new Contact();
        con.LastName = 'Aspect';
        insert con;
        
        Id RecordTypeIdContact = Schema.SObjectType.Site__c.getRecordTypeInfosByName().get('Domestic').getRecordTypeId();
        Site__c site = new Site__c();
        site.Account__c  = acc.id;
        site.RecordTypeId = RecordTypeIdContact;
        site.Name = 'test';
        site.Primary_Site_Contact__c =con.id;
        site.Site_Street__c ='Test';
        site.Site_PostalCode__c ='12345';
        Site.Site_Country__c ='Uk';
        insert site;
        
        WorkType wt=new WorkType();
        wt.trade__c='Electrical';
        wt.name ='test';
        wt.EstimatedDuration=10.00;
        insert wt;
        
        Job__c job = new Job__c();
        Job.Account__c = acc.id;
        Job.Job_Type__c = wt.Id;
        Job.Site__c =site.id;
        JOb.Combined_Scope_of_Works_for_All_WOs__c = 'Test';
        insert Job;
        
        Aspect_JobDataController.workORderLabourWrapper wraps = new Aspect_JobDataController.workORderLabourWrapper();
        Costs_and_Charges__c cost = new Costs_and_Charges__c();
        cost.JOb__c = Job.id;
        insert cost;
        
        Trade__c trade = new Trade__c();
        trade.Name = 'Electrical';
        insert trade;
        
        Rate_Card_Trade__c rct = new Rate_Card_Trade__c();
        rct.Rate_Card__c = rca.Id;
        rct.Trade__c = trade.Id;
        rct.Default_For_Estimate__c = 'Tier 8';
        rct.Charge_R1__c = 10;rct.Charge_R2__c = 20;rct.Charge_R3__c= 30;
        rct.Pay_Tier_1__c = 4;rct.Pay_Tier_2__c = 4;
        rct.Pay_Tier_3__c= 5;rct.Pay_Tier_4__c = 6;
        rct.Pay_Tier_5__c = 3;rct.Pay_Tier_6__c = 7;
        rct.Pay_Tier_7__c = 21;rct.Pay_Tier_8__c = 9;
        rct.Pay_Tier_9__c = 25;rct.Pay_Tier_10__c = 12;
        insert rct;
        
        Costs_and_Charges__c costs = new Costs_and_Charges__c();
        costs.Job__c = job.id;
        insert costs;
        
        Aspect_JobDataController.productRequiredWrapper prod = new Aspect_JobDataController.productRequiredWrapper();
        prod.type='Hire';
        prod.ProductREquiredId ='|567|';
        List<Aspect_JobDataController.productRequiredWrapper> prodrec = new List<Aspect_JobDataController.productRequiredWrapper>();
        prodrec.add(prod);
        
        WorkOrder WO  = New WOrkOrder();
        WO.JOb__c =job.id;
        WO.Costs_and_Charges__c =costs.id;
        WO.WorkTypeId =wt.id;
        WO.Trade_Rate__c = rct.Id;
        insert WO;

        Id pricebookId = Test.getStandardPricebookId();
        
        //Create your product
        Product2 prodyuct = new Product2(
            Name = 'Hire',
            ProductCode = 'Pro-X',
            isActive = true
        );
        insert prodyuct;
        
        //Create your pricebook entry
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prodyuct.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        ProductRequired prodreq = new ProductRequired();
        prodreq.ParentRecordId =WO.id;
        prodreq.Product2Id =prodyuct.id;
        prodreq.QuantityRequired = 1;
        insert prodreq;
        
        Aspect_JobDataController.CCOtherWrapper ccothers = new   Aspect_JobDataController.CCOtherWrapper();
        Test.startTest();
        Map<String,String> trades =  Aspect_JobDataController.getTrades();
        List<Id> ids = InvoiceController.getGLC('Fixed Price',Job.Account__r.Account_Type__c,Job.Job_Type__r.Trade__c,Job.Account__r.RecordType.name);
        Customer_Invoice__c inv = InvoiceController.createInvoice(Job,ids,'Deposit');
        insert inv;
        Aspect_JobDataController.workORderLabourWrapper wrap = Aspect_JobDataController.getWorkOrderOnChage(trade.id,wraps,Job.id,true,true);
        Aspect_JobDataController.workORderLabourWrapper wrap1 = Aspect_JobDataController.getWorkOrderOnChage(trade.id,wraps,Job.id,false,false);
        Aspect_JobDataController.workORderLabourWrapper wrap2 = Aspect_JobDataController.getWorkOrderOnChage(trade.id,wraps,Job.id,false,true);
        Aspect_JobDataController.workORderLabourWrapper wrap3 = Aspect_JobDataController.getWorkOrderOnChage(trade.id,wraps,Job.id,true,false);
        Aspect_JobDataController.workTrageGroupWrapper tradge =Aspect_JobDataController.tradeWOrktypeGroup(WO.id);
        Aspect_JobDataController.updateccforworkorder(WO.id);
        Aspect_JobDataController.CCOtherWrapper ccother =Aspect_JobDataController.getCCforWorkOrder(WO.id);
        List<Aspect_JobDataController.productRequiredWrapper>Prods =  Aspect_JobDataController.updatePrdowrap(prodrec);
        JOb__c jobs  =Aspect_JobDataController.getjobbrecord(Job.id);
        Aspect_JobDataController.workORderLabourWrapper wrapsLabour =   Aspect_JobDataController.getWorkorderforLabourctrl(WO.id);
        Aspect_JobDataController.workOrderWrapper  wkorder = Aspect_JobDataController.getWorkOrderDetailsCtrl(WO.id);
        List<Aspect_JobDataController.productRequiredWrapper>Prods1 =  Aspect_JobDataController.markupChangeMethod(prodrec);
        List<Aspect_JobDataController.productRequiredWrapper>Prods2 =  Aspect_JobDataController.qulaityChangeMethd(prodrec);
        List<Aspect_JobDataController.productRequiredWrapper>Prods3 =  Aspect_JobDataController.checkboxchange(prodrec,'3',true);
        List<Aspect_JobDataController.productRequiredWrapper>Prods4 =  Aspect_JobDataController.checkboxchange(prodrec,'3',false);
        Aspect_JobDataController.CCOtherWrapper ccotherss = Aspect_JobDataController.handloeotherfunction(ccothers);
        List<Aspect_JobDataController.productRequiredWrapper> prodwrapppers = Aspect_JobDataController.getProductRequiredRec(WO.id);
        Aspect_JobDataController.updateSuccess s = Aspect_JobDataController.updateJob(prodrec,wraps,'',ccothers,Job.id,false,trade.id);
        Aspect_JobDataController.updateSuccess s1 = Aspect_JobDataController.updateJob(prodrec,wraps,'',ccothers,Job.id,true,trade.id);
        Map<String,String> mpasRTrade =Aspect_JobDataController.getgroup('');
        Map<String,String> mpasRTrades =Aspect_JobDataController.getWorkType('');
        Aspect_JobDataController.workORderLabourWrapper wrap6 =    Aspect_JobDataController.getworktypechange(wt.id,wraps,WO.id,Job.id);
        String getDescription = Aspect_JobDataController.getCombinedValuefromJob(Job.id);
        Boolean wrap7 =    Aspect_JobDataController.checkOnSize(prodrec);
        Aspect_JobDataController.hr1 =10;
        Aspect_JobDataController.hr2 =10;
        Aspect_JobDataController.hr3 =10;
        Aspect_JobDataController.hr1amount =10;
        Aspect_JobDataController.hr2amount =10;
        Aspect_JobDataController.hr3amount =10;
        Boolean s5=  Aspect_JobDataController.checkUserProfile();
        List<String> s6 =Aspect_JobDataController.getProductRequiredProduct();
        decimal s7 = Aspect_JobDataController.getfixedPriceAdmin(Job.id);
        List<Aspect_JobDataController.productRequiredWrapper> prodWraps = new  List<Aspect_JobDataController.productRequiredWrapper>();
        Aspect_JobDataController.productRequiredWrapper prodWrap = new Aspect_JobDataController.productRequiredWrapper();
        prodWrap.type='Hire';
        prodWraps.add(prodWrap);
        Aspect_JobDataController.workORderLabourWrapper d2= Aspect_JobDataHandler.updateWorkOrder(trade.id,wraps,Job.id,true,true);
        integer intValue = Aspect_JobDataController.getrandomnumber();
        Aspect_JobDataController.deleteproductrequired(prodreq.id);
        Boolean isCheckUser=Aspect_JobDataController.getUserInfo(u.id);
        Aspect_JobDataHandler.createupdateprod('Hire');
        //   String sJob1 = Aspect_JobDataController.getCombinedValuefromJob(job.id);
        Test.stopTest();
    }
}