unpackaged/main/default/objects/Account/recordTypes/Domestic.recordType-meta.xml
<RecordType>
    <fullName>Domestic</fullName>
    <active>true</active>
    <label>Domestic</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Site related to the Contact</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Costs_and_Charges__c/Costs_and_Charges__c.object-meta.xml
<CustomObject>
    <label>Costs and Charges</label>
    <nameField>
        <displayFormat>CandC-{000000}</displayFormat>
        <label>Costs and Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Costs_and_Charges__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Costs and Charges</relationshipLabel>
    <relationshipName>Costs_and_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Costs_and_Charges__c/fields/Rate_of_Pay__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay__c</fullName>
    <description>Rate of Pay as a percentage of the Rate of Charge</description>
    <inlineHelpText>Rate of Pay as a percentage of the Rate of Charge</inlineHelpText>
    <label>Rate of Pay</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Combined_Scope_of_Works_for_All_WOs__c.field-meta.xml
<CustomField>
    <fullName>Combined_Scope_of_Works_for_All_WOs__c</fullName>
    <label>Combined Scope of Works for All WOs</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail to account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Primary_Site_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Site_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Primary contact at this Site</inlineHelpText>
    <label>Primary Site Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Primary_Sites_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_Country__c.field-meta.xml
<CustomField>
    <fullName>Site_Country__c</fullName>
    <defaultValue>&#39;United Kingdom&#39;</defaultValue>
    <description>Site country</description>
    <label>Site Country</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>Site_PostalCode__c</fullName>
    <description>Site postal address</description>
    <label>Site PostalCode</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/fields/Site_Street__c.field-meta.xml
<CustomField>
    <fullName>Site_Street__c</fullName>
    <description>Site street address</description>
    <label>Site Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site__c/recordTypes/Domestic.recordType-meta.xml
<RecordType>
    <fullName>Domestic</fullName>
    <active>true</active>
    <label>Domestic</label>
</RecordType>

unpackaged/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WorkOrder/fields/Costs_and_Charges__c.field-meta.xml
<CustomField>
    <fullName>Costs_and_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Costs and Charges</label>
    <referenceTo>Costs_and_Charges__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Rate_of_Pay__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay__c</fullName>
    <description>Deletion Candidate</description>
    <label>Rate of Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Rate_Of_Pay_Percent__c.field-meta.xml
<CustomField>
    <fullName>Rate_Of_Pay_Percent__c</fullName>
    <label>Rate Of Pay %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is populated only through the flow</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <description>Trade for the Work Type - added this for the H&amp;S Flow + thought it better to use a formula than look it up each time.</description>
    <formula>TEXT( WorkType.Trade__c )</formula>
    <inlineHelpText>Trade for the Work Type</inlineHelpText>
    <label>Trade</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkType/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trade</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Trade.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Access</fullName>
    </customValue>
    <customValue>
        <fullName>Air Con, Ventilation &amp; Refrigeration</fullName>
    </customValue>
    <customValue>
        <fullName>Brickwork &amp; Paving</fullName>
    </customValue>
    <customValue>
        <fullName>Carpentry</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Decorating</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Soil Water)</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Tanker)</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Wastewater)</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Fencing</fullName>
    </customValue>
    <customValue>
        <fullName>Flooring</fullName>
    </customValue>
    <customValue>
        <fullName>Gardening</fullName>
    </customValue>
    <customValue>
        <fullName>Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>Handyman</fullName>
    </customValue>
    <customValue>
        <fullName>Heating &amp; Hot Water (Commercial)</fullName>
    </customValue>
    <customValue>
        <fullName>Heating &amp; Hot Water (Domestic)</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Central Heating</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Drainage</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Plumbing</fullName>
    </customValue>
    <customValue>
        <fullName>Locksmithing</fullName>
    </customValue>
    <customValue>
        <fullName>OSA</fullName>
    </customValue>
    <customValue>
        <fullName>Partition Walls &amp; Ceilings</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Control</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Proofing</fullName>
    </customValue>
    <customValue>
        <fullName>Plastering</fullName>
    </customValue>
    <customValue>
        <fullName>Plumbing &amp; Cold Water</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management Decoration</fullName>
    </customValue>
    <customValue>
        <fullName>Roofing</fullName>
    </customValue>
    <description>This holds all of the types of trade in the company</description>
    <masterLabel>Trade</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/BatchMassUpdateRateOfPayWOTest.cls
@isTest
public class BatchMassUpdateRateOfPayWOTest {
    static testmethod void testWOrkOrder(){
        Profile p = [SELECT Id FROM Profile WHERE Name='PHASE 2 Ops - Starter']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standardusfghgfhgfhger@testorg.com');

        insert u;
        
        Account acc = new Account();
        acc.Name = 'Test';
        acc.BillingStreet ='Test';
        acc.BillingPostalCode  ='123445';
        insert acc; 
        
        contact con  = new Contact();
        con.LastName = 'Aspect';
        insert con;
        Id RecordTypeIdContact = Schema.SObjectType.Site__c.getRecordTypeInfosByName().get('Domestic').getRecordTypeId();
        Site__c site = new Site__c();
        site.Account__c  = acc.id;
        site.RecordTypeId = RecordTypeIdContact;
        site.Name = 'test';
        site.Primary_Site_Contact__c =con.id;
        site.Site_Street__c ='Test';
        site.Site_PostalCode__c ='12345';
        Site.Site_Country__c ='Uk';
        insert site;
        Job__c job = new Job__c();
        Job.Account__c = acc.id;
        Job.Site__c =site.id;
        JOb.Combined_Scope_of_Works_for_All_WOs__c = 'Test';
        insert Job;
        Aspect_JobDataController.workORderLabourWrapper wraps = new Aspect_JobDataController.workORderLabourWrapper();
        Costs_and_Charges__c cost = new Costs_and_Charges__c();
        cost.JOb__c = Job.id;
        insert cost;
        Trade__c trade = new Trade__c();
        trade.Name = 'Roofing';
        insert trade;
        Costs_and_Charges__c costs = new Costs_and_Charges__c();
        costs.Job__c = job.id;
        insert costs;
        Aspect_JobDataController.productRequiredWrapper prod = new Aspect_JobDataController.productRequiredWrapper();
        prod.type='Hire';
        prod.ProductREquiredId ='|567|';
        List<Aspect_JobDataController.productRequiredWrapper> prodrec = new List<Aspect_JobDataController.productRequiredWrapper>();
        prodrec.add(prod);
        WorkType wt=new WorkType();
        wt.trade__c='Roofing';
        wt.name ='test';
        wt.EstimatedDuration=10.00;
        insert wt;
        WorkOrder WO  = New WOrkOrder();
        WO.JOb__c =job.id;
        WO.Costs_and_Charges__c =costs.id;
        WO.WorkTypeId =wt.id;
        WO.Rate_of_Pay__c = 45;
        insert WO;
        
         Test.startTest();
        String accQuery = 'SELECT id,Rate_of_Pay__c,Rate_Of_Pay_Percent__c from WorkOrder where  Rate_of_Pay__c !=null';
BatchMassUpdateRateOfPayWO bdt = new BatchMassUpdateRateOfPayWO(accQuery);
dataBase.executeBatch(bdt);
        Test.stopTest();
    }

}