unpackaged/main/default/objects/Engineer_Pay_Requisition__c/Engineer_Pay_Requisition__c.object-meta.xml
<CustomObject>
    <label>Engineer Pay Requisition</label>
    <nameField>
        <displayFormat>EPR-{000000}</displayFormat>
        <label>Engineer Pay Requisition  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineer Pay Requisitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Engineer Pay Requisitions</relationshipLabel>
    <relationshipName>Engineer_Pay_Requisitions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Pay_Fixed_Price__c.field-meta.xml
<CustomField>
    <fullName>Pay_Fixed_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pay Other</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Pay_Labour_Total__c.field-meta.xml
<CustomField>
    <fullName>Pay_Labour_Total__c</fullName>
    <formula>Pay_Labour_R1__c + Pay_Labour_R2__c + Pay_Labour_R3__c - Discount_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pay Labour Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Pay_Materials__c.field-meta.xml
<CustomField>
    <fullName>Pay_Materials__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pay Materials</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Pay_Total__c.field-meta.xml
<CustomField>
    <fullName>Pay_Total__c</fullName>
    <formula>Pay_Labour_Total__c +  Pay_Materials__c +  Pay_Fixed_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pay Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Engineer Pay Requisitions</relationshipLabel>
    <relationshipName>Engineer_Pay_Requisitions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Requisition_Total_Pay__c.field-meta.xml
<CustomField>
    <fullName>Requisition_Total_Pay__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Requisition Total Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>For Client Approval</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Approved by Client</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Requisition_Labour__c.field-meta.xml
<CustomField>
    <fullName>Requisition_Labour__c</fullName>
    <label>Requisition Labour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Requisition_Materials__c.field-meta.xml
<CustomField>
    <fullName>Requisition_Materials__c</fullName>
    <label>Requisition Materials</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Requisition_Other__c.field-meta.xml
<CustomField>
    <fullName>Requisition_Other__c</fullName>
    <label>Requisition Other</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Requisition_Total__c.field-meta.xml
<CustomField>
    <fullName>Requisition_Total__c</fullName>
    <label>Requisition Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/epr_create_edit_delete_controller.cls
public class epr_create_edit_delete_controller {

    public static void updateJob( id job_id, id wo_id )
    {
        Decimal job_total_pay = 0;
        Decimal wo_labour_pay = 0;
        Decimal wo_material_pay = 0;
        Decimal wo_other_pay = 0;
        Decimal wo_total_pay = 0;
        
        //
        // get all eprs on this job and total them
        //
        List<Engineer_Pay_Requisition__c> eprs = [
            SELECT Pay_Labour_Total__c, Pay_Materials__c, Pay_Fixed_Price__c, Pay_Total__c, Work_Order__c 
            FROM Engineer_Pay_Requisition__c 
            WHERE Job__c = :job_Id 
        ];
        for (Engineer_Pay_Requisition__c epr : eprs )
        {
            job_total_pay+=epr.Pay_Total__c;
            if (epr.Work_Order__c == wo_id )
            {
                if (epr.Pay_Labour_Total__c != NULL)
                {
                    wo_labour_pay += epr.Pay_Labour_Total__c;
                } 
                if (epr.Pay_Materials__c != NULL) 
                {
                    wo_material_pay += epr.Pay_Materials__c;
                } 
                if (epr.Pay_Fixed_Price__c != NULL)
                {
                    wo_other_pay += epr.Pay_Fixed_Price__c;
                } 
                if (epr.Pay_Total__c != NULL)
                {
                    wo_total_pay += epr.Pay_Total__c;
                }
            }
        }

        if (wo_id != NULL )
        {
            
            WorkOrder wo = [SELECT id FROM WorkOrder WHERE id=:wo_id LIMIT 1];
            wo.Requisition_Labour__c = wo_labour_pay;
            wo.Requisition_Materials__c = wo_material_pay;
            wo.Requisition_Other__c = wo_other_pay;
            wo.Requisition_Total__c = wo_total_pay;
            update wo;
        }
        Job__c job = [SELECT id FROM Job__c WHERE id = :job_id];
        job.Requisition_total_pay__c = job_total_pay;
        update job;
    }

    public static void markEPRsApproved(id job_id)
    {
        List<Engineer_Pay_Requisition__c> eprs = [
            SELECT id 
            FROM Engineer_Pay_Requisition__c
            WHERE Job__c = :job_id 
            AND Status__c = 'New'
        ];
        for(Engineer_Pay_Requisition__c epr:eprs)
        {
            epr.Status__c = 'Approved';
        }
        update eprs;
    }
    
}