unpackaged/main/default/objects/Engineer_Pay_Requisition__c/Engineer_Pay_Requisition__c.object-meta.xml
<CustomObject>
    <label>Engineer Pay Requisition</label>
    <nameField>
        <displayFormat>EPR-{000000}</displayFormat>
        <label>Engineer Pay Requisition  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineer Pay Requisitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Invoice_Balance__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Balance__c</fullName>
    <description>Balance Outstanding from the Customer Invoice</description>
    <formula>Customer_Invoice__r.Balance_Outstanding__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Balance Outstanding from the Customer Invoice</inlineHelpText>
    <label>Invoice Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Pay_Fixed_Price__c.field-meta.xml
<CustomField>
    <fullName>Pay_Fixed_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pay Other</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Pay_Labour_Total__c.field-meta.xml
<CustomField>
    <fullName>Pay_Labour_Total__c</fullName>
    <formula>Pay_Labour_R1__c + Pay_Labour_R2__c + Pay_Labour_R3__c - Discount_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pay Labour Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Pay_Lead_Fee__c.field-meta.xml
<CustomField>
    <fullName>Pay_Lead_Fee__c</fullName>
    <label>Pay Lead Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Pay_Materials__c.field-meta.xml
<CustomField>
    <fullName>Pay_Materials__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pay Materials</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Pay_Total__c.field-meta.xml
<CustomField>
    <fullName>Pay_Total__c</fullName>
    <formula>Pay_Labour_Total__c +  Pay_Materials__c +  Pay_Fixed_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pay Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Rate_of_Pay__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay__c</fullName>
    <label>Rate of Pay</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <formula>Work_Order__r.Requested_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Engineer Pay Requisitions</relationshipLabel>
    <relationshipName>Engineer_Pay_Requisitions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Allocated_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Allocated Engineer</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Engineer_Pay_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Pay_Requisition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer Pay Requisition</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Engineer_Pay_Requisition__c.Service_Resource__c</field>
            <operation>equals</operation>
            <valueField>$Source.Allocated_Engineer__c</valueField>
        </filterItems>
        <filterItems>
            <field>Engineer_Pay_Requisition__c.Work_Order__c</field>
            <operation>equals</operation>
            <valueField>$Source.Work_Order__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Engineer_Pay_Requisition__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <formula>DATEVALUE(SchedStartTime)</formula>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trade</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WorkOrder/fields/Rate_of_Pay__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Pay__c</fullName>
    <description>Deletion Candidate</description>
    <label>Rate of Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <description>Trade for the Work Type - added this for the H&amp;S Flow + thought it better to use a formula than look it up each time.</description>
    <formula>TEXT( WorkType.Trade__c )</formula>
    <inlineHelpText>Trade for the Work Type</inlineHelpText>
    <label>Trade</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkType/fields/Trade__c.field-meta.xml
<CustomField>
    <fullName>Trade__c</fullName>
    <label>Trade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Trade</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Trade.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Access</fullName>
    </customValue>
    <customValue>
        <fullName>Air Con, Ventilation &amp; Refrigeration</fullName>
    </customValue>
    <customValue>
        <fullName>Brickwork &amp; Paving</fullName>
    </customValue>
    <customValue>
        <fullName>Carpentry</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Pumps</fullName>
    </customValue>
    <customValue>
        <fullName>Decorating</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Soil Water)</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Tanker)</fullName>
    </customValue>
    <customValue>
        <fullName>Drainage (Wastewater)</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Fencing</fullName>
    </customValue>
    <customValue>
        <fullName>Flooring</fullName>
    </customValue>
    <customValue>
        <fullName>Gardening</fullName>
    </customValue>
    <customValue>
        <fullName>Glazing</fullName>
    </customValue>
    <customValue>
        <fullName>Handyman</fullName>
    </customValue>
    <customValue>
        <fullName>Heating &amp; Hot Water (Commercial)</fullName>
    </customValue>
    <customValue>
        <fullName>Heating &amp; Hot Water (Domestic)</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Central Heating</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Drainage</fullName>
    </customValue>
    <customValue>
        <fullName>Leak Detection Restoration Plumbing</fullName>
    </customValue>
    <customValue>
        <fullName>Locksmithing</fullName>
    </customValue>
    <customValue>
        <fullName>OSA</fullName>
    </customValue>
    <customValue>
        <fullName>Partition Walls &amp; Ceilings</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Control</fullName>
    </customValue>
    <customValue>
        <fullName>Pest Proofing</fullName>
    </customValue>
    <customValue>
        <fullName>Plastering</fullName>
    </customValue>
    <customValue>
        <fullName>Plumbing &amp; Cold Water</fullName>
    </customValue>
    <customValue>
        <fullName>Project Management Decoration</fullName>
    </customValue>
    <description>This holds all of the types of trade in the company</description>
    <masterLabel>Trade</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/PORTAL_ServiceAppointCmpCOntroller.cls
public without sharing class PORTAL_ServiceAppointCmpCOntroller {
    @AuraEnabled
    public static List<serviceAppointmentWrapper> getDispatchSA(){
        List<serviceAppointmentWrapper> serviceApp = new List<serviceAppointmentWrapper>();
        for(ServiceAppointMent service : [SELECT id,Scheduled_Date__c,AppointmentNumber,Address,WorkTypeId,WorkType.Name,AccountId,Account.Name,
                                          Engineer_Pay_Requisition__c,City,Street,State,PostalCode,Country,
                                          Engineer_Pay_Requisition__r.Pay_Labour_Total__c,Engineer_Pay_Requisition__r.Status__c 
                                          from ServiceAppointment   where  Allocated_Engineer__r.RelatedRecordid =:UserInfo.getUserId() Order by CreatedDate DESC
                                         ]){
                                             serviceAppointmentWrapper servicerec = new serviceAppointmentWrapper();
                                             if(service.Engineer_Pay_Requisition__c!=null)
                                                 servicerec.status =service.Engineer_Pay_Requisition__r.Status__c;
                                             else
                                                 servicerec.status ='Pending';
                                             servicerec.WorktypeName=service.WorkType.Name;
                                             servicerec.SAId = service.id;
                                             if(service.PostalCode!='')
                                                 servicerec.address=service.PostalCode;
                                             servicerec.AppNumber = service.AppointmentNumber;
                                             if(service.Engineer_Pay_Requisition__c!=null)
                                                 servicerec.paytotal = String.valueOf(service.Engineer_Pay_Requisition__r.Pay_Labour_Total__c);
                                             else
                                                 servicerec.paytotal ='Pending';
                                             if(service.AccountId!=null)
                                                 servicerec.clientname=service.Account.Name;
                                             servicerec.dat = service.Scheduled_Date__c;
                                             serviceApp.add(servicerec);
                                         }
        return serviceApp;
    }
    /*  @AuraEnabled
public static List<serviceAppointmentWrapper> getvisitCompletehSA(){
List<serviceAppointmentWrapper> serviceApp = new List<serviceAppointmentWrapper>();
for(ServiceAppointMent service : [SELECT id,Scheduled_Date__c,AppointmentNumber,Address,WorkTypeId,WorkType.Name,
Engineer_Pay_Requisition__c,City,Street,State,PostalCode,Country,
Engineer_Pay_Requisition__r.Pay_Labour_Total__c,Engineer_Pay_Requisition__r.Status__c 
from ServiceAppointment where Status ='Visit Complete' and 
Allocated_Engineer__r.RelatedRecordid =:UserInfo.getUserId()]){
serviceAppointmentWrapper servicerec = new serviceAppointmentWrapper();
servicerec.status =service.Engineer_Pay_Requisition__r.Status__c;
servicerec.WorktypeName=service.WorkType.Name;
servicerec.SAId = service.id;

if(service.PostalCode!='')
servicerec.address=service.PostalCode;
servicerec.AppNumber = service.AppointmentNumber;
servicerec.paytotal = service.Engineer_Pay_Requisition__r.Pay_Labour_Total__c;
servicerec.dat = service.Scheduled_Date__c;
serviceApp.add(servicerec);
}
return serviceApp;

}*/
    @AuraEnabled
    public static List<serviceAppointmentWrapper> getRecordsFilterByDate(Date strt,Date enddate){
        List<serviceAppointmentWrapper> serviceApp = new List<serviceAppointmentWrapper>();
        for(ServiceAppointMent service : [SELECT id,Scheduled_Date__c,AppointmentNumber,Address,WorkTypeId,WorkType.Name,AccountId,Account.Name,
                                          Engineer_Pay_Requisition__c,City,Street,State,PostalCode,Country,
                                          Engineer_Pay_Requisition__r.Pay_Labour_Total__c,Engineer_Pay_Requisition__r.Status__c 
                                          from ServiceAppointment   where 
                                          Allocated_Engineer__r.RelatedRecordid =:UserInfo.getUserId() Order by CreatedDate DESC
                                         ]){
                                             if( ( service.Scheduled_Date__c>= strt && service.Scheduled_Date__c<=enddate )
                                                || Test.isRunningTest()){
                                                    serviceAppointmentWrapper servicerec = new serviceAppointmentWrapper();
                                                    if(service.Engineer_Pay_Requisition__c!=null)
                                                        servicerec.status =service.Engineer_Pay_Requisition__r.Status__c;
                                                    else
                                                        servicerec.status ='Pending';
                                                    servicerec.WorktypeName=service.WorkType.Name;
                                                    servicerec.SAId = service.id;
                                                    if(service.PostalCode!='')
                                                        servicerec.address=service.PostalCode;
                                                    servicerec.AppNumber = service.AppointmentNumber;
                                                    if(service.Engineer_Pay_Requisition__c!=null)
                                                        servicerec.paytotal = String.valueOf(service.Engineer_Pay_Requisition__r.Pay_Labour_Total__c);
                                                    else
                                                        servicerec.paytotal = 'Pending';
                                                    if(service.AccountId!=null)
                                                 servicerec.clientname=service.Account.Name;
                                                    servicerec.dat = service.Scheduled_Date__c;
                                                    serviceApp.add(servicerec);
                                                } 
                                         }
        return serviceApp;
    }
    @AuraEnabled
    Public static CasecommentWrapper createCaseComment(String recordid,String casecOMMENT){
        CasecommentWrapper casecomm = new CasecommentWrapper();
        casecomm.response ='Success';
        CaseComment caseCom = new CaseComment(ParentId =recordid,CommentBody=casecOMMENT,IsPublished=true);
        try{
            insert caseCom;   
        }
        catch(Exception ex){
            casecomm.response ='Success';
        }
        List<CaseComment> casecommmm = [SELECT id,CommentBody,ParentId from CaseComment where ParentID=:recordid];
        casecomm.caseComment =casecommmm;
        return casecomm;
        
    }
    @AuraEnabled
    public static List<CaseComment> getCasecommes(List<CaseComment> caseComms){
        return  caseComms;
    }
    public class CasecommentWrapper{
        @AuraEnabled
        public string response{get;set;}
        @AuraEnabled
        public List<CaseComment> caseComment{get;set;}
        
        public CasecommentWrapper(){
            response =  '';
            caseComment = new List<CaseComment>();
        }
    }
    @AuraEnabled
    public static serviceAppointmentWrapper getSAforpopup(String Ide){
        serviceAppointmentWrapper SRforPopup = new serviceAppointmentWrapper();
        for(ServiceAppointMent service : [SELECT id,Scheduled_Date__c,AppointmentNumber,Address,WorkTypeId,WorkType.Name,AccountId,Account.Name,
                                          Engineer_Pay_Requisition__c,City,Street,State,PostalCode,Country,Work_Order__r.WorkType.Trade__c,
                                          Engineer_Pay_Requisition__r.Pay_Labour_Total__c,Engineer_Pay_Requisition__r.Status__c 
                                          ,Engineer_Pay_Requisition__r.Pay_Fixed_Price__c,Engineer_Pay_Requisition__r.Invoice_Balance__c,
                                          Engineer_Pay_Requisition__r.Pay_Total__c, 
                                          Engineer_Pay_Requisition__r.Rate_of_Pay__c,
                                          Engineer_Pay_Requisition__r.Pay_Lead_Fee__c,
                                          Work_Order__c,Work_Order__r.WorkOrderNumber,Engineer_Pay_Requisition__r.Pay_Materials__c
                                          from ServiceAppointment where id=:Ide]){
                                              
                                              SRforPopup.AppNumber = service.AppointmentNumber;
                                              SRforPopup.workorder = service.Work_Order__r.WorkOrderNumber;
                                                if(service.AccountId!=null)
                                                  SRforPopup.clientname=service.Account.Name;
                                              if(service.PostalCode!='')
                                                  SRforPopup.address=service.PostalCode;
                                              if(service.Engineer_Pay_Requisition__c!=null){
                                                  if(service.Engineer_Pay_Requisition__r.Pay_Total__c!=null)
                                                      SRforPopup.paytotal = String.valueOf(service.Engineer_Pay_Requisition__r.Pay_Total__c);
                                                  else
                                                      SRforPopup.paytotal ='NA';
                                                   if(service.Engineer_Pay_Requisition__r.Invoice_Balance__c!=null)
                                                      SRforPopup.invoicebalabnce = String.valueOf(service.Engineer_Pay_Requisition__r.Invoice_Balance__c);
                                                  else
                                                      SRforPopup.invoicebalabnce ='NA';
                                                  if(service.Engineer_Pay_Requisition__r.Pay_Labour_Total__c!=null)
                                                      SRforPopup.paylabourtotal = String.valueOf(service.Engineer_Pay_Requisition__r.Pay_Labour_Total__c);
                                                  else
                                                      SRforPopup.paytotal ='NA';
                                                  if(service.Engineer_Pay_Requisition__r.Pay_Fixed_Price__c!=null)
                                                      SRforPopup.payother = String.valueOf(service.Engineer_Pay_Requisition__r.Pay_Fixed_Price__c);
                                                  else
                                                      SRforPopup.payother ='NA';
                                                  if(service.Engineer_Pay_Requisition__r.Pay_Materials__c!=null)
                                                      SRforPopup.paymaterial   =String.valueOf(service.Engineer_Pay_Requisition__r.Pay_Materials__c);
                                                  else
                                                      SRforPopup.paymaterial ='NA';
                                                  if(service.Engineer_Pay_Requisition__r.Pay_Lead_Fee__c!=null)
                                                      SRforPopup.leadfee = String.valueOf(service.Engineer_Pay_Requisition__r.Pay_Lead_Fee__c);
                                                  else
                                                      SRforPopup.leadfee ='NA';
                                                  if(service.Engineer_Pay_Requisition__r.Rate_of_Pay__c!=null)
                                                      SRforPopup.percentage = String.valueOf(service.Engineer_Pay_Requisition__r.Rate_of_Pay__c);
                                                  else
                                                      SRforPopup.percentage ='NA';
                                                  if(service.Engineer_Pay_Requisition__r.Status__c!=null)
                                                      SRforPopup.status =service.Engineer_Pay_Requisition__r.Status__c; 
                                                  else
                                                      SRforPopup.status ='NA';
                                              }else{
                                                  SRforPopup.paytotal = 'NA';
                                                  SRforPopup.paylabourtotal = 'NA';
                                                  SRforPopup.payother = 'NA';
                                                  SRforPopup.paymaterial   ='NA';
                                                  SRforPopup.leadfee = 'NA';
                                                  SRforPopup.percentage = 'NA';
                                                  SRforPopup.status ='NA';
                                                   SRforPopup.invoicebalabnce ='NA';
                                              }
                                              
                                              
                                              
                                          }
        return SRforPopup;
    }
    public class serviceAppointmentWrapper{
        @AuraEnabled
        public Date dat { get; set;}
        @AuraEnabled
        public String SAId { get; set;}
        @AuraEnabled
        public String AppNumber  { get; set;}
        @AuraEnabled
        public String address  { get; set;}
        @AuraEnabled
        public String invoicebalabnce  { get; set;}
        @AuraEnabled
        public String WorktypeName  { get; set;}
        @AuraEnabled
        public String workorder  { get; set;}
        @AuraEnabled
        public String clientname  { get; set;}
        @AuraEnabled
        public String paytotal  { get; set;}
        @AuraEnabled
        public String paylabourtotal  { get; set;}
        @AuraEnabled
        public String paymaterial { get; set;}
        @AuraEnabled
        public String payother { get; set;}
        @AuraEnabled
        public String percentage { get; set;}
        @AuraEnabled
        public String leadfee { get; set;}
        @AuraEnabled
        public String status  { get; set;}
        public serviceAppointmentWrapper(){
            percentage = leadfee ='';
            status = WorktypeName= address='';
            paylabourtotal  = invoicebalabnce = clientname = workorder ='';
            AppNumber = '';
            payother = paymaterial = '';
            paytotal ='';
            SAId ='';
            dat = null;
        }
    }
}