unpackaged/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>Purchase Order for Material and Sub Contractor.</description>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Purchase_Order__c/fields/Delivery_Options__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Options__c</fullName>
    <description>This is the options for delivering the Purchase Orders</description>
    <label>Delivery Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Options</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Purchase_Order__c/fields/Supplier_Account__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Supplier fulfilling the order</description>
    <label>Supplier Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Purchase_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This is type of  Purchase Order e.g Materials, Sub-Contractor</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Purchase_Ledger_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/Supplier_Invoice__c.object-meta.xml
<CustomObject>
    <description>Supplier Invoice</description>
    <label>Supplier Invoice</label>
    <nameField>
        <displayFormat>SI-{000000}</displayFormat>
        <label>Salesforce Internal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Supplier Invoices</relationshipLabel>
    <relationshipName>Supplier_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/fields/Supplier_Account__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Account__c</fullName>
    <formula>Purchase_Order__r.Supplier_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Supplier_Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

unpackaged/main/default/globalValueSets/Delivery_Options.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Engineer to Collect</fullName>
    </customValue>
    <customValue>
        <fullName>Deliver to Office</fullName>
    </customValue>
    <customValue>
        <fullName>Deliver to Client</fullName>
    </customValue>
    <customValue>
        <fullName>Deliver to Engineer</fullName>
    </customValue>
    <description>This is the options for delivering the Purchase Orders</description>
    <masterLabel>Delivery Options</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Purchase_Ledger_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Materials</fullName>
    </customValue>
    <customValue>
        <fullName>Sub-Contractor</fullName>
    </customValue>
    <customValue>
        <fullName>Hire</fullName>
    </customValue>
    <description>This is type of  Purchase Order e.g Materials, Sub-Contractor</description>
    <masterLabel>Purchase Ledger Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ContentDocumentURL_Test.cls
@isTest
private class ContentDocumentURL_Test {
 static testMethod void insertDoctest1() {
       
        List<Account> accountslist= TestDataFactory.createAccounts(1);
        
        /*
        Supplier_Invoice__c supInv = new Supplier_Invoice__c();
        supInv.Type__c = 'Invoice';
        supInv.Supplier_Account__c = accountslist[0].id;
        supInv.Total_Actual_Invoice_Amount_excl_VAT__c = 123.00;
        supInv.Total_Actual_Invoice_Amount_incl_VAT__c = 173.00;   
        supInv.Total_Actual_VAT_Amount__c = 50;
        insert supInv;
        */
        
         Purchase_Order__c po = new Purchase_Order__c();
         //po.Supplier_Invoice__c = supInv.Id;
         po.Delivery_Options__c = 'Deliver to Office';
         po.Supplier_Account__c = accountslist[0].id;
         insert po;
     
     
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        ContentVersion contentVersion_1 = new ContentVersion(
            Title='Header_Picture1', 
            PathOnClient ='/Header_Picture1.jpg',
            VersionData = bodyBlob, 
            origin = 'H'
        );
        insert contentVersion_1;
       
        ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1];
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
     
     ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = po.id;
        contentlink.contentdocumentid = contentVersion_2.contentdocumentid;
        contentlink.ShareType = 'V';
        Test.startTest();
        insert contentlink; 
        Test.stopTest();
 }
}