unpackaged/main/default/objects/Costs_and_Charges__c/Costs_and_Charges__c.object-meta.xml
<CustomObject>
    <label>Costs and Charges</label>
    <nameField>
        <displayFormat>CandC-{000000}</displayFormat>
        <label>Costs and Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Costs_and_Charges__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Costs and Charges</relationshipLabel>
    <relationshipName>Costs_and_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Authorisation__c.field-meta.xml
<CustomField>
    <fullName>Authorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Valid Authorisation record (at time of booking)</description>
    <inlineHelpText>Valid Authorisation record (at time of booking)</inlineHelpText>
    <label>Authorisation</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You can only add a card if it is linked to this jobs account.</errorMessage>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>asp04__Authorisation__c.Customer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>asp04__Authorisation__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <label>Access Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Arrival_Window_End__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Window_End__c</fullName>
    <label>Arrival Window End</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Arrival_Window_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Window_End_Date_Time__c</fullName>
    <label>Arrival Window End Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Arrival_Window_Start__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Window_Start__c</fullName>
    <label>Arrival Window Start</label>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Arrival_Window_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Arrival_Window_Start_Date_Time__c</fullName>
    <label>Arrival Window Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Costs_and_Charges__c.field-meta.xml
<CustomField>
    <fullName>Costs_and_Charges__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Costs and Charges</label>
    <referenceTo>Costs_and_Charges__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Online_Booking__c.field-meta.xml
<CustomField>
    <fullName>Online_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Online Booking</label>
    <referenceTo>Online_Bookings__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <label>Requested Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Schedule_Slot_End__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Slot_End__c</fullName>
    <formula>IF(
  OR(
DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp; Arrival_Window_End_TEXT__c ) &lt;
DATETIMEVALUE(DATE(YEAR(DATEVALUE(DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp; Arrival_Window_End_TEXT__c ) )),3,31)-(WEEKDAY(DATE(YEAR(DATEVALUE( DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp; Arrival_Window_End_TEXT__c ))),3,31))-1) +1/24),
DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp; Arrival_Window_End_TEXT__c ) &gt; DATETIMEVALUE(DATE(YEAR(DATEVALUE(
DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp; Arrival_Window_End_TEXT__c ))),10,31)- (WEEKDAY(DATE(YEAR(DATEVALUE(
DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp; Arrival_Window_End_TEXT__c))),10,31))-1)+1/24)

 

 

),
DATETIMEVALUE(Requested_Date__c)
+
( MFLOOR((Duration/8))*16)/24
+
 IF(Arrival_Window_End__c &lt; Arrival_Window_Start__c , 1, 0) 
+
(HOUR( Arrival_Window_End__c )*60)/1440
+
(MINUTE( Arrival_Window_End__c ))/1440
+ (60*Duration)/1440,

DATETIMEVALUE(Requested_Date__c)
+
( MFLOOR((Duration/8))*16)/24
+
 IF(Arrival_Window_End__c &lt; Arrival_Window_Start__c , 1, 0) 
+
(HOUR( Arrival_Window_End__c )*60)/1440
+
(MINUTE( Arrival_Window_End__c ))/1440
+ (60*Duration)/1440 -1/24
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latest End Permitted</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Schedule_Slot_Start__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Slot_Start__c</fullName>
    <description>DATETIMEVALUE(  
Requested_Date__c   
)- 60/1440

 +

 (HOUR( Arrival_Window_Start__c )*60)/1440

+
 (MINUTE( Arrival_Window_Start__c ))/1440</description>
    <formula>IF( 
    OR(
        DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp;  Arrival_Window_Start_TEXT__c ) &lt; 
		DATETIMEVALUE(DATE(YEAR(DATEVALUE(DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp;  Arrival_Window_Start_TEXT__c ) )),3,31)-(WEEKDAY(DATE(YEAR(DATEVALUE( DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp;  Arrival_Window_Start_TEXT__c ))),3,31))-1) +1/24),
        DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp;  Arrival_Window_Start_TEXT__c ) &gt; DATETIMEVALUE(DATE(YEAR(DATEVALUE( 
		DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp;  Arrival_Window_Start_TEXT__c ))),10,31)- (WEEKDAY(DATE(YEAR(DATEVALUE( 
		DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp;  Arrival_Window_Start_TEXT__c))),10,31))-1)+1/24)

 

    ),
    DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp;  Arrival_Window_Start_TEXT__c ),
    DATETIMEVALUE(TEXT(Requested_Date__c)&amp; &quot; &quot; &amp;  Arrival_Window_Start_TEXT__c ) -1/24
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Earliest Start Permitted</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/ProcessInforceAuthorizations.cls
public class ProcessInforceAuthorizations {
    
    
  @InvocableMethod
    public static void processInforceAuthorizations(List<Id> authinforceId){
        
        OnlineBookingProcessHelper.accountWorkOrderMap = new Map<Id,list<WorkOrder>>();
        List<Job__c> joblist = new List<Job__c>();
        List<asp04__Authorisation__c> authlist = new List<asp04__Authorisation__c>();
        List<WorkOrder> woList = new List<WorkOrder>();
        List<Id> receivedwoList = new List<Id>();
        List<Id> serviceAppwoList = new List<Id>();
        List<Id> woListToProcess = new List<Id>();
        
        for(asp04__Authorisation__c authrec : [select id,Online_Booking__c from asp04__Authorisation__c where Id in: authinforceId]){
            authrec.Online_Booking__c = FALSE;
            authlist.add(authrec);
        }
        update authlist;
        
        for(Job__c jobrec : [select id,Authorisation__c,Account__c from Job__c where Authorisation__c in: authinforceId]){
            joblist.add(jobrec);
        }
        
        for(WorkOrder wo : [select id from WorkOrder where Job__c in: joblist]){
            receivedwoList.add(wo.Id);
        }
        
        //checking if any workorders have previous service appointments
        for(ServiceAppointment sa : [select id,Work_Order__c from ServiceAppointment where Work_Order__c in: receivedwoList]){
            serviceAppwoList.add(sa.Work_Order__c);
        }
        
        //Create a list of new WorkOrder to process
        for(Id woId : receivedwoList){
            if(!serviceAppwoList.contains(woId)){
               woListToProcess.add(woId);   
            }
          }
        
        for(WorkOrder wo : [select id,Job__c,Schedule_Slot_Start__c,Schedule_Slot_End__c,Duration,WorkTypeId,Description,Requested_Date__c,Arrival_Window_Start__c,Arrival_Window_End__c,Access_Details__c,ContactId,AccountId,Costs_and_Charges__c,Arrival_Window_Start_Date_Time__c,Arrival_Window_End_Date_Time__c from WorkOrder where Id in: woListToProcess]){
            
            if(OnlineBookingProcessHelper.accountWorkOrderMap.containsKey(wo.AccountId)) {
                      List<WorkOrder> wolistexist = OnlineBookingProcessHelper.accountWorkOrderMap.get(wo.AccountId);
                      wolistexist.add(wo);
                      OnlineBookingProcessHelper.accountWorkOrderMap.put(wo.AccountId, wolistexist);
                }else{
                        List<WorkOrder> wolistnew = new List<WorkOrder>();
                        wolistnew.add(wo);
                        OnlineBookingProcessHelper.accountWorkOrderMap.put(wo.AccountId, wolistnew);
                 } 
        }
        system.debug('size' + OnlineBookingProcessHelper.accountWorkOrderMap.keySet());
        OnlineBookingProcessHelper.createServiceAppointments(OnlineBookingProcessHelper.accountWorkOrderMap.KeySet());
    }
}