unpackaged/main/default/objects/WorkOrder/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>DELETE</description>
    <label>Date (delete)</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Scheduled_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date_Time__c</fullName>
    <description>Service Appointment Scheduled Date Time</description>
    <label>Scheduled Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <description>Deletion Candidate</description>
    <label>Time (delete)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1AM</fullName>
            </value>
            <value>
                <fullName>2AM</fullName>
            </value>
            <value>
                <fullName>3AM</fullName>
            </value>
            <value>
                <fullName>4AM</fullName>
            </value>
            <value>
                <fullName>5AM</fullName>
            </value>
            <value>
                <fullName>6AM</fullName>
            </value>
            <value>
                <fullName>7AM</fullName>
            </value>
            <value>
                <fullName>8AM</fullName>
            </value>
            <value>
                <fullName>9AM</fullName>
            </value>
            <value>
                <fullName>10AM</fullName>
            </value>
            <value>
                <fullName>11AM</fullName>
            </value>
            <value>
                <fullName>12PM</fullName>
            </value>
            <value>
                <fullName>1PM</fullName>
            </value>
            <value>
                <fullName>2PM</fullName>
            </value>
            <value>
                <fullName>3PM</fullName>
            </value>
            <value>
                <fullName>4PM</fullName>
            </value>
            <value>
                <fullName>5PM</fullName>
            </value>
            <value>
                <fullName>6PM</fullName>
            </value>
            <value>
                <fullName>7PM</fullName>
            </value>
            <value>
                <fullName>8PM</fullName>
            </value>
            <value>
                <fullName>9PM</fullName>
            </value>
            <value>
                <fullName>10PM</fullName>
            </value>
            <value>
                <fullName>11PM</fullName>
            </value>
            <value>
                <fullName>12AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/WorkOrderHandlerTest.cls
/**
 *	@author: Andrey Gavrikov (westbrook)
 *	@date: 2018-11-26 13:07:52 
 *	@description:
 *	    Test methods for WorkOrderHandler
 *	
 *	Version History :   
 *		
 */
@isTest(isParallel=true)
public class WorkOrderHandlerTest  {
    final static String WorkOrder_KEY_PREFIX = Schema.SObjectType.WorkOrder.getKeyPrefix();
    final static String WorkOrder_ID_1 = WorkOrder_KEY_PREFIX + '000000000001';
    /**
     *  3. "Date' & 'Time' fields on the Work Order should be populated based on the following fields
     *  - 1.Date - Date from Scheduled/DateTime 
     *  - 2.Time - Time from Scheduled/DateTime (10.03) - should be 10 am" 
     *
     */
    @isTest
    static void testSetTimeFromScheduledDateTime () {
        final List<WorkOrder> orders = new List<WorkOrder>{
            new WorkOrder(Scheduled_Date_Time__c = null),
            new WorkOrder(Scheduled_Date_Time__c = DateTime.newInstance(2018, 11, 26, 1, 2, 3))
        };
        WorkOrderHandler handler = new WorkOrderHandler();
        handler.setTimeFromScheduledDateTime(orders);
        System.assertEquals(null, orders[0].Date__c, 'did not expect value to be set');
        System.assertEquals(null, orders[0].Time__c, 'did not expect value to be set');

        System.assertNotEquals(null, orders[1].Date__c, 'expected value to be set');
        System.assertEquals('1AM', orders[1].Time__c, 'did not expect value to be set');

        // code coverage for places without logic
        // force trigger handler to get called
        try { Database.insert(new WorkOrder(), false); } catch (Exception eIgnore){}
    }
}