unpackaged/main/default/objects/WorkOrder/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>DELETE</description>
    <label>Date (delete)</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Scheduled_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date_Time__c</fullName>
    <description>Service Appointment Scheduled Date Time</description>
    <label>Scheduled Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <description>Deletion Candidate</description>
    <label>Time (delete)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1AM</fullName>
            </value>
            <value>
                <fullName>2AM</fullName>
            </value>
            <value>
                <fullName>3AM</fullName>
            </value>
            <value>
                <fullName>4AM</fullName>
            </value>
            <value>
                <fullName>5AM</fullName>
            </value>
            <value>
                <fullName>6AM</fullName>
            </value>
            <value>
                <fullName>7AM</fullName>
            </value>
            <value>
                <fullName>8AM</fullName>
            </value>
            <value>
                <fullName>9AM</fullName>
            </value>
            <value>
                <fullName>10AM</fullName>
            </value>
            <value>
                <fullName>11AM</fullName>
            </value>
            <value>
                <fullName>12PM</fullName>
            </value>
            <value>
                <fullName>1PM</fullName>
            </value>
            <value>
                <fullName>2PM</fullName>
            </value>
            <value>
                <fullName>3PM</fullName>
            </value>
            <value>
                <fullName>4PM</fullName>
            </value>
            <value>
                <fullName>5PM</fullName>
            </value>
            <value>
                <fullName>6PM</fullName>
            </value>
            <value>
                <fullName>7PM</fullName>
            </value>
            <value>
                <fullName>8PM</fullName>
            </value>
            <value>
                <fullName>9PM</fullName>
            </value>
            <value>
                <fullName>10PM</fullName>
            </value>
            <value>
                <fullName>11PM</fullName>
            </value>
            <value>
                <fullName>12AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/WorkOrderHandler.cls
public without sharing class WorkOrderHandler extends BaseTriggerHandler {
    override public void beforeInsert () {
        //... your code here
        setTimeFromScheduledDateTime((List<WorkOrder>)Trigger.new);
    }

    override public void beforeUpdate () {
        setTimeFromScheduledDateTime((List<WorkOrder>)Trigger.new);
    }

    //override public void beforeDelete () {
        //... your code here
    //}

    //override public void afterInsert () {
    //    //... your code here
    //}

    //override public void afterUpdate () {
        //... your code here
    //}

    //override public void afterDelete () {
        //... your code here
    //}

    //override public void afterUnDelete () {
        //... your code here
    //}
    
    /**
     *  3. "Date' & 'Time' fields on the Work Order should be populated based on the following fields
     *  - 1.Date - Date from Scheduled/DateTime 
     *  - 2.Time - Time from Scheduled/DateTime (10.03) - should be 10 am" 
     *
     */
    @TestVisible void setTimeFromScheduledDateTime(final List<WorkOrder> newList) {
        if (hasSkipReason('setTimeFromScheduledDateTime')) {
            return;
        }

        BaseTriggerHandler.addSkipReason('setTimeFromScheduledDateTime', 'no reason to visit thos method second time');
        for(WorkOrder wo : newList) {
            if (null != wo.Scheduled_Date_Time__c) {
                wo.Date__c =  wo.Scheduled_Date_Time__c.date();
                Integer hour = wo.Scheduled_Date_Time__c.hour();
                wo.Time__c = hoursToAmPm(hour);
            }
        }
    }
    public static String hoursToAmPm(final Integer hour) {
        final String timeStr = hour < 12 ? hour + 'AM' : hour > 12 ? (hour - 12) + 'PM' : '12PM';
        return '0AM' == timeStr ? '12AM' : timeStr;
    }
}