unpackaged/main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Site related to the Contact</description>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/BuyapowaReferralReconciliationAPI_Test.cls
/*
* Class  : BuyapowaReferralReconciliationAPI_Test
* Use    : This test class is written to get coverage for class BuyapowaReferralReconciliationAPI.
* Auther : Bharat Vyas, 18/5/2022.
*/

@isTest
private class BuyapowaReferralReconciliationAPI_Test {

     @isTest static void testCallout() {
        
        Account acc = AspectTestDataFactory.createAccount();
        Contact cont = AspectTestDataFactory.createContact(acc);
        Site__c site = AspectTestDataFactory.createSite(acc, Cont);
        WorkType wType = AspectTestDataFactory.createWorkType();
        Job__c job = AspectTestDataFactory.createJob(acc, wType, site);
        
        List<BuyapowaReferralReconciliationAPI.orderDetails> orderDetailList = new List<BuyapowaReferralReconciliationAPI.orderDetails>();
        BuyapowaReferralReconciliationAPI.orderDetails ordrDetail = new BuyapowaReferralReconciliationAPI.orderDetails();
        ordrDetail.jobId = job.Id;
        ordrDetail.jobName = job.Name;
        ordrDetail.jobStatus = 'Confirmed';
         orderDetailList.add(ordrDetail);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BuyapowaRefReconciliationMockHttep()); 
        BuyapowaReferralReconciliationAPI.getOrderDetails(orderDetailList);
        Test.stopTest();
    }
}