unpackaged/main/default/objects/Customer_Invoice__c/Customer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Exchequer_Export__c.field-meta.xml
<CustomField>
    <fullName>Exchequer_Export__c</fullName>
    <label>Exchequer Export</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Sent</fullName>
                <default>true</default>
                <label>Not Sent</label>
            </value>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Number of days credit given on Customer Invoices</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

unpackaged/main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ready to Send</fullName>
    </customValue>
    <customValue>
        <fullName>Part Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Paid</fullName>
    </customValue>
    <customValue>
        <fullName>Outstanding</fullName>
        <default>true</default>
        <label>Outstanding</label>
    </customValue>
    <customValue>
        <fullName>In Post</fullName>
        <isActive>false</isActive>
        <label>In Post</label>
    </customValue>
    <customValue>
        <fullName>Reconciled</fullName>
        <isActive>false</isActive>
        <label>Reconciled</label>
    </customValue>
    <customValue>
        <fullName>Received</fullName>
        <isActive>false</isActive>
        <label>Received</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
        <isActive>false</isActive>
        <label>Draft</label>
    </customValue>
    <customValue>
        <fullName>With Engineer</fullName>
        <isActive>false</isActive>
        <label>With Engineer</label>
    </customValue>
    <description>Number of days credit given on Customer Invoices</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/UpdateCustomerInvoices_Batch.cls
global class UpdateCustomerInvoices_Batch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) { 
        String query = System.Label.CIBatchCriteria;  
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Customer_Invoice__c> invlist) {
        
        
            System.debug('Total invoice size==='+invlist.size());
            for(Customer_Invoice__c invrec : invlist){
                //invrec.Status__c = 'Ready to Send';
                // MR - changed outbound maessage trigger
                invrec.Exchequer_Export__c = 'Ready to Send';
            }  
          try{
              system.debug('updating the invoice');
              //system.debug('status'+invlist[0].Status__c);
              system.debug('status'+invlist[0].Exchequer_Export__c);
              update invlist;
          }catch(Exception e){system.debug('BatchFailure : '+e);}
    }
    
    global void finish(Database.BatchableContext BC) {
    
    }
}