unpackaged/main/default/objects/Customer_Invoice__c/Customer_Invoice__c.object-meta.xml
<CustomObject>
    <label>Customer Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipName>Customer_Invoices_Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Customer_Invoice__c/fields/Sum_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>Sum_of_Payments__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Populated via a Flow due to lack of Master-Detail relationship between Customer Inv and Payment (managed package)</description>
    <inlineHelpText>Sum of the Payments for a Customer Invoice</inlineHelpText>
    <label>Sum of Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Customer_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Customer_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Invoice</label>
    <referenceTo>Customer_Invoice__c</referenceTo>
    <relationshipLabel>Jobs (Customer Invoice)</relationshipLabel>
    <relationshipName>Consolidated_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Payment_Value__c.field-meta.xml
<CustomField>
    <fullName>Payment_Value__c</fullName>
    <label>Payment Value</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/job_sum_payments_controller.cls
public class job_sum_payments_controller {


    public static void job_sum_payments(id job_id) {

        Decimal total_payments = 0;
        for ( Customer_Invoice__c ci:[
            SELECT Sum_of_Payments__c 
            FROM Customer_Invoice__c 
            WHERE Job__c = :job_id 
        ]) 
        {
            if(ci.Sum_of_Payments__c != NULL) 
            {
                total_payments += ci.Sum_of_Payments__c;
            }
        }
        Job__c job = [SELECT Payment_Value__c FROM Job__c WHERE id=:job_id ];
        job.Payment_Value__c = total_payments;
        update job;

    }

}