unpackaged/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Job__c/fields/Attendance_Notes_for_Office__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Notes_for_Office__c</fullName>
    <description>Summary of all &quot;attendance notes&quot; for this Job.
Attendance notes are recorded on each Service Appointment at the end of the attendance.</description>
    <label>Attendance Notes for Office</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Job__c/fields/Attendance_Report_for_Customer__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Report_for_Customer__c</fullName>
    <inlineHelpText>Summary of all &quot;attendance reports&quot; for this Job.
Attendance reports are recorded on each Service Appointment at the end of the attendance.</inlineHelpText>
    <label>Attendance Report for Customer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Allocated_Engineer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Engineer_First_Name__c</fullName>
    <formula>Allocated_Engineer__r.FirstName__c</formula>
    <label>Allocated Engineer First Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Allocated_Engineer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Engineer_Last_Name__c</fullName>
    <formula>Allocated_Engineer__r.LastName__c</formula>
    <label>Allocated Engineer Last Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Attendance_Notes_for_Office__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Notes_for_Office__c</fullName>
    <label>Attendance Notes for Office</label>
    <length>2010</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Attendance_Report_for_Customer__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Report_for_Customer__c</fullName>
    <label>Attendance Report for Customer</label>
    <length>2010</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Attendance_Notes_for_Office__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Notes_for_Office__c</fullName>
    <inlineHelpText>Summary of all &quot;attendance notes&quot; for this Work Order.
Attendance notes are recorded on each Service Appointment at the end of the attendance.</inlineHelpText>
    <label>Attendance Notes for Office</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Attendance_Report_for_Customer__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Report_for_Customer__c</fullName>
    <inlineHelpText>Summary of all &quot;attendance reports&quot; for this Work Order.
Attendance reports are recorded on each Service Appointment at the end of the attendance.</inlineHelpText>
    <label>Attendance Report for Customer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Work_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Work_Type_Name__c</fullName>
    <description>Required for Flow Create Fixed Cost Work Order</description>
    <formula>WorkType.Name</formula>
    <label>Work Type Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Phase_2_SA_Attendance_Notes_Rollup.cls
public class Phase_2_SA_Attendance_Notes_Rollup
{

    public Phase_2_SA_Attendance_Notes_Rollup(id wo_id, id job_id){
        wo_rollup(wo_id);
        job_rollup(job_id);
    }

    public void wo_rollup(id wo_id) {
        List<ServiceAppointment> sas = [
            SELECT AppointmentNumber, ActualEndTime, ActualStartTime, Allocated_Engineer_First_Name__c, 
            Allocated_Engineer_Last_Name__c, Attendance_Notes_for_Office__c, Attendance_Report_for_Customer__c
            FROM ServiceAppointment
            WHERE Work_Order__c = :wo_id  
        ];

        WorkOrder wo = [
            SELECT id, Work_Type_Name__c, WorkOrderNumber, Attendance_Notes_for_Office__c, Attendance_Report_for_Customer__c
            FROM WorkOrder
            WHERE id = :wo_id 
        ];

        String wo_office_note = '', wo_customer_note='';
        for (ServiceAppointment sa:sas) {
            try{
                String sa_header = 
                    '\r\n' + sa.ActualStartTime.format('dd/MM/yyyy HH:mm') + ' - '+ sa.ActualEndTime.format('dd/MM/yyyy HH:mm') +
                    '\r\n'+ sa.Allocated_Engineer_First_Name__c+' '+sa.Allocated_Engineer_Last_Name__c+'\r\n';
                wo_office_note += sa_header+sa.Attendance_Notes_for_Office__c+'\r\n' ;
                wo_customer_note += sa_header+ sa.Attendance_Report_for_Customer__c + '\r\n';
            } catch (Exception e) {}
        }
        wo.Attendance_Report_for_Customer__c = wo_customer_note;
        wo.Attendance_Notes_for_Office__c = wo_office_note;
        update wo;
    }

    public void job_rollup(id job_id) {

        List<WorkOrder> wos = [
            SELECT id, Attendance_Notes_for_Office__c, Attendance_Report_for_Customer__c
            FROM WorkOrder
            WHERE Job__c = :job_id
        ];

        String job_office_note = '', job_customer_note='';

        for (WorkOrder wo:wos)
        {
            if(!String.isBlank(wo.Attendance_Notes_for_Office__c)){
	            job_office_note += wo.Attendance_Notes_for_Office__c + '\r\n\r\n';
            }
            if(!String.isBlank(wo.Attendance_Report_for_Customer__c)){
                job_customer_note += wo.Attendance_Report_for_Customer__c + '\r\n\r\n';
            }
        }
        Job__c job = [
            SELECT id, Attendance_Notes_for_Office__c, Attendance_Report_for_Customer__c 
            FROM Job__c 
            WHERE id = :job_id
        ];

        job.Attendance_Notes_for_Office__c = job_office_note;
        job.Attendance_Report_for_Customer__c = job_customer_note;
        update job;
    }


}