unpackaged/main/default/objects/Exchequer_Export_Job__c/Exchequer_Export_Job__c.object-meta.xml
<CustomObject>
    <label>Exchequer Export Job</label>
    <nameField>
        <label>Exchequer_Export_Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchequer_Export_Job</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Exchequer_Export_Job__c/fields/Job_Category__c.field-meta.xml
<CustomField>
    <fullName>Job_Category__c</fullName>
    <label>Job Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchases</fullName>
            </value>
            <value>
                <fullName>Engineer Costs</fullName>
            </value>
            <value>
                <fullName>Sales Cash</fullName>
            </value>
            <value>
                <fullName>Sales Credit</fullName>
            </value>
            <value>
                <fullName>Sales Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Exchequer_Export_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Exchequer_Export_Job__c/fields/Submitted__c.field-meta.xml
<CustomField>
    <fullName>Submitted__c</fullName>
    <label>Submitted</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Exchequer_Export_Job__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exchequer_Export_Job</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FinanceAppControllerTest.cls
@IsTest
public with sharing class FinanceAppControllerTest {
    @IsTest
    public static void getJobsTest() {
        FinanceAppController.createExportJob('Purchases', Date.today(), Date.today() + 2);
        Test.startTest();
        List<Exchequer_Export_Job__c> jobs = FinanceAppController.getJobs();
        System.assertEquals(1, jobs.size());
        System.assertEquals('Purchases', jobs.get(0).Job_Category__c);
        System.assertEquals(Date.today(), jobs.get(0).Start_Date__c);
        System.assertEquals(Date.today() + 2, jobs.get(0).End_Date__c);
        Test.stopTest();
    }

    @IsTest
    public static void getDataFromDateRangeTest() {
        Test.startTest();
        Map<String, Integer> data = FinanceAppController.getDataFromDateRange('Sales Key',Date.today(), Date.today() + 2);
        System.assertEquals(6, data.size());
        Test.stopTest();
    }

    @IsTest
    public static void getStartDateFromMetadataTest() {
        Test.startTest();
        Date resultDate = FinanceAppController.getStartDateFromMetadata('Purchases');
        Test.stopTest();
    }

    @IsTest
    public static void createExportJobTest() {
        Test.startTest();
        FinanceAppController.createExportJob('Purchases', Date.today(), Date.today() + 2);
        List<Exchequer_Export_Job__c> jobs = [SELECT Id, Name, Job_Category__c, Status__c, User__r.Name, Completed__c, Submitted__c, Start_Date__c, End_Date__c FROM Exchequer_Export_Job__c];
        System.assertEquals(1, jobs.size());
        System.assertEquals('Purchases', jobs.get(0).Job_Category__c);
        System.assertEquals(Date.today(), jobs.get(0).Start_Date__c);
        System.assertEquals(Date.today() + 2, jobs.get(0).End_Date__c);
        Test.stopTest();
    }

    @IsTest
    public static void updateMetadataDateTest() {
        Test.startTest();
        FinanceAppController.updateMetadataDate(Date.today(), 'Purchases');
        Test.stopTest();
    }

    @IsTest
    public static void handleResultTest() {
        FinanceAppController metadata = new FinanceAppController();
        Test.startTest();
        metadata.handleResult(new Metadata.DeployResult(), new Metadata.DeployCallbackContext());
        Test.stopTest();
    }
}