unpackaged/main/default/objects/Deduction__c/Deduction__c.object-meta.xml
<CustomObject>
    <description>All deductions to the Engineer will be logged here. This will affect the Engineer wages</description>
    <label>Engineer Deduction</label>
    <nameField>
        <displayFormat>ED-{000000}</displayFormat>
        <label>Deduction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineer Deductions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Deduction__c/fields/Engineer_Pay_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Engineer_Pay_Requisition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engineer Pay Requisition</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Service_Resource__c</field>
            <operation>equals</operation>
            <valueField>Engineer_Pay_Requisition__c.Service_Resource__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Engineer_Pay_Requisition__c</referenceTo>
    <relationshipLabel>Engineer Deductions</relationshipLabel>
    <relationshipName>Engineer_Deductions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Deduction__c/fields/Payroll_month__c.field-meta.xml
<CustomField>
    <fullName>Payroll_month__c</fullName>
    <label>Payroll month</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Deduction__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <description>The service resource associated with the deduction</description>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Engineer Deductions</relationshipLabel>
    <relationshipName>Deductions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Deduction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Deducted</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/Engineer_Pay_Requisition__c.object-meta.xml
<CustomObject>
    <label>Engineer Pay Requisition</label>
    <nameField>
        <displayFormat>EPR-{000000}</displayFormat>
        <label>Engineer Pay Requisition  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engineer Pay Requisitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Payroll_month__c.field-meta.xml
<CustomField>
    <fullName>Payroll_month__c</fullName>
    <label>Payroll month</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Date__c</fullName>
    <formula>Work_Order__r.Requested_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Engineer Pay Requisitions</relationshipLabel>
    <relationshipName>Engineer_Pay_Requisitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Engineer_Pay_Requisition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>FOC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Deduction__c.field-meta.xml
<CustomField>
    <fullName>Deduction__c</fullName>
    <label>Deduction</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/BatchProcessDeduction.cls
Global class BatchProcessDeduction Implements Database.batchable<sobject>{
    global final string query;
    global final date payrollDate;
    global BatchProcessDeduction(string payrollQuery,Date payrollDate){
        query = payrollQuery;
        payrollDate = payrollDate;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug(query);
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC,List<Deduction__c> procesDed){
        System.debug('eprs'+procesDed);
        System.debug('eprs.szie'+procesDed.size());
        list<Deduction__c> procesDeds = new List<Deduction__c>();
        if(procesDed.size()!=0){
            for(Deduction__c pd:procesDed){
                pd.Status__c = 'Paid'; 
                pd.Payroll_Month__c = payrollDate; 
                procesDeds.add(pd);
            }
        }
        if(procesDeds.size()!=0){
            Database.UpsertResult[] records =Database.upsert(procesDeds,false);
            string header = ' Details  \n';
            string finalstr = header ;
            Boolean hasError = false;
            for(Integer i = 0 ; i<records.size();i++){
                Database.UpsertResult record =records.get(i);
                Map<String,Object> recordMap = (Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(record));
                Boolean isSUccess = record.isSuccess();
                if(!isSUccess){
                    String recordDetails = JSON.serialize(recordMap);
                    string recordString = recordDetails +'\n';
                    System.debug('recordDetails'+recordDetails);
                    finalstr = finalstr +recordString;
                    hasError = true;
                }
            }
            if(hasError){
                sendEmailCLass.sendEmail(finalstr,'Process deduction');
            }
        }
    }
    global void finish(Database.BatchableContext BC){
        
    }
    
    
}

/*String keyStatus = 'New';
String accQuery = 'SELECT CreatedDate,Id,Name,Payroll_month__c,Scheduled_Date__c,Status__c FROM Engineer_Pay_Requisition__c WHERE  Scheduled_Date__c >= 2021-06-26 AND Scheduled_Date__c <= 2022-04-03 AND Service_Resource__r.IsActive = TRUE AND Status__c = \''+keyStatus+'\'';
BatchMssUpdateEpr bdt = new BatchMssUpdateEpr(accQuery);
dataBase.executeBatch(bdt);
*/